// Generated by kin from the source named below. Do not edit.
// source: flint.rt.byteslice

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::hash::*;
use crate::kgen::rt::pike::*;
use crate::kgen::rt::casetable::*;
use crate::kgen::rt::hamt::*;

impl Rt {
    /// `v` from `from` to `to`, exclusive.
    /// 
    /// Bounds are CLAMPED to the value's length, which is what a caller asking
    /// for more than there is means. They are not clamped at zero: `from` and
    /// `to` are `I32`, whose contract is that the high bit is never set, and a
    /// negative bound is refused by the builtin before it reaches here.
    /// 
    /// The whole range answers `v` ITSELF, which is worth stating because it is
    /// the case a caller hits most and the one that must not allocate.
    pub fn b_slice(&mut self, v: Value, from: u32, to: u32) -> Value {
        let n: u32 = self.b_count(v);
        let mut lo: u32;
        let mut hi: u32;
        lo = from;
        if lo > n {
            lo = n;
        }
        hi = to;
        if hi > n {
            hi = n;
        }
        if hi < lo {
            hi = lo;
        }
        if lo == 0 {
            if hi == n {
                return v;
            }
        }
        // SMALL, OR A LEAF: copy. Sharing a three-byte slice would keep
        // the section it came from alive, which is the leak `SLICE_MIN`
        // names. The copy needs a byte sink, so it lives in the
        // hand-written half.
        if (hi - lo) < crate::rope::SLICE_MIN {
            return self.b_copy_range(v, lo, hi);
        }
        if !self.is_brope(v) {
            return self.b_copy_range(v, lo, hi);
        }
        let base: usize = self.mark();
        let vi: usize = self.push(v);
        let kids: u32 = self.olen(self.r(vi)) - crate::bytes::BB_KIDS;
        let out: usize = self.mark();
        let mut made: u32;
        let mut at: u32;
        made = 0;
        at = 0;
        for i in 0..kids {
            let k: Value = self.slot(self.r(vi), crate::bytes::BB_KIDS + i);
            let w: u32 = self.b_count(k);
            if (at + w) > lo {
                if at < hi {
                    // The part of this child the range covers. `klo` is 0
                    // when the range began before it, `khi` its whole width
                    // when the range runs past it -- and when both, the
                    // child is WHOLLY INSIDE and is shared as itself.
                    let mut klo: u32;
                    let mut khi: u32;
                    klo = 0;
                    if lo > at {
                        klo = lo - at;
                    }
                    khi = hi - at;
                    if khi > w {
                        khi = w;
                    }
                    let mut piece: Value;
                    if klo == 0 {
                        if khi == w {
                            piece = k;
                        } else {
                            piece = self.b_slice(k, klo, khi);
                        }
                    } else {
                        piece = self.b_slice(k, klo, khi);
                    }
                    if piece.is_nil() {
                        self.pop_to(base);
                        return NIL;
                    }
                    if self.b_count(piece) > 0 {
                        self.push(piece);
                        made += 1;
                    }
                }
            }
            at += w;
            if at >= hi {
                break;
            }
        }
        let out_v: Value = self.b_from_roots(out, made);
        self.pop_to(base);
        return out_v;
    }
}
