// Generated by kin from the source named below. Do not edit.
// source: flint.rt.byteat

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::hash::*;
use crate::kgen::rt::pike::*;
use crate::kgen::rt::casetable::*;

impl Rt {
    /// The byte at `i`, as a fixnum, or `dflt` when there is no such byte.
    /// 
    /// `dflt` rather than a sentinel, because a byte is 0..255 and every value
    /// in that range is a real answer -- there is no number left over to mean
    /// `absent`. The ports used -1, which works in a signed `int` and does not
    /// survive the trip to Rust, where this index type is unsigned.
    /// 
    /// THE RANGE CHECK IS UP FRONT and costs nothing: `b-count` is O(1) in both
    /// tiers, so asking first is cheaper than descending and discovering.
    /// 
    /// `i` IS AN `I32`, whose contract is that the high bit is never set, and a
    /// NEGATIVE INDEX IS THE CALLER'S TO REJECT. This cannot screen one: Rust
    /// spells the type `u32`, where -1 arrives as four billion and the range
    /// check above refuses it, and both ports spell it `int`, where -1 sails
    /// past a `>=` test and indexes backwards out of the leaf. Writing `i < 0`
    /// here would be dead code in Rust and the only live check in the ports,
    /// which is a divergence wearing one spelling. The builtins screen it.
    pub fn b_at(&self, v: Value, i: u32, dflt: Value) -> Value {
        if !v.is_heap() {
            return dflt;
        }
        if i >= self.b_count(v) {
            return dflt;
        }
        let mut cur: Value;
        let mut idx: u32;
        cur = v;
        idx = i;
        loop {
            let t: u8 = ty(&self.gc.sp, cur.as_heap());
            if t == TY_BYTES {
                return Value::fixnum((self.gc.sp.read_u8((cur.as_heap() + crate::obj::HDR) + (idx as Addr)) as u32) as i64);
            }
            if t != TY_BROPE {
                return dflt;
            }
            // THE CACHED FLATTENING, if this subtree has one. Rust took this
            // and neither port did, though all three WRITE it in `b-flatten`
            // -- so the ports walked a tree that had already been flattened
            // beside them. Same shape as the `count-hint` fast path that was
            // missing from `seq-count`.
            let flat: Value = self.slot(cur, crate::bytes::BB_FLAT);
            if !flat.is_nil() {
                cur = flat;
                continue;
            }
            // Down the child that contains `idx`, subtracting the ones it is
            // past on the way. `next` staying nil means the counts do not add
            // up to the length -- unreachable while the tree is well formed,
            // and answered rather than asserted.
            let n: u32 = self.olen(cur) - crate::bytes::BB_KIDS;
            let mut next: Value;
            next = NIL;
            for k in 0..n {
                if next.is_nil() {
                    let kid: Value = self.slot(cur, crate::bytes::BB_KIDS + k);
                    let kn: u32 = self.b_count(kid);
                    if idx < kn {
                        next = kid;
                    } else {
                        idx -= kn;
                    }
                }
            }
            if next.is_nil() {
                return dflt;
            }
            cur = next;
        }
    }
}
