// Generated by kin from the source named below. Do not edit.
// source: flint.rt.champ

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};

impl Rt {
    #[inline]
    pub fn bn_datamap(&self, n: Value) -> u32 {
        return self.slot(n, BN_DATAMAP).as_fixnum() as u32;
    }
    #[inline]
    pub fn bn_nodemap(&self, n: Value) -> u32 {
        return self.slot(n, BN_NODEMAP).as_fixnum() as u32;
    }
    #[inline]
    pub fn bn_key(&self, n: Value, i: u32) -> Value {
        return self.slot(n, BN_BASE + (2 * i));
    }
    #[inline]
    pub fn bn_val(&self, n: Value, i: u32) -> Value {
        return self.slot(n, BN_BASE + ((2 * i) + 1));
    }
    #[inline]
    pub fn bn_set_key(&mut self, n: Value, i: u32, v: Value) {
        self.set(n, BN_BASE + (2 * i), v);
    }
    #[inline]
    pub fn bn_set_val(&mut self, n: Value, i: u32, v: Value) {
        self.set(n, BN_BASE + ((2 * i) + 1), v);
    }
    /// Sub-nodes live at the END, in DESCENDING bit order.
    #[inline]
    pub fn bn_node(&self, n: Value, j: u32) -> Value {
        return self.slot(n, (self.olen(n) - 1) - j);
    }
    #[inline]
    pub fn bn_set_node(&mut self, n: Value, j: u32, v: Value) {
        self.set(n, (self.olen(n) - 1) - j, v);
    }
}
