// Generated by kin from the source named below. Do not edit.
// source: flint.rt.control

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::portdrain::*;
use crate::kgen::rt::portinstall::*;
use crate::kgen::rt::portpark::*;
use crate::kgen::rt::portring::*;
use crate::kgen::rt::sched::*;
use crate::kgen::rt::vecread::*;
use crate::kgen::rt::vecwrite::*;
use crate::kgen::rt::wirecore::*;
use crate::kgen::rt::wirescan::*;

impl Rt {
    /// Is the control plane still WAITING ON THE HOST?
    /// 
    /// True while the image has a call loop, there is a system port, and no
    /// `:close` has been served, nor the port ended. `sched-needs-host` asks this, because nothing is parked
    /// on the system port any more: the green thread that used to be -- which
    /// is what made a sandbox with a door answer 2, "the host is needed" --
    /// does not exist. Without this a sandbox with nothing bound would read as
    /// settled and close its own system port before the host had said a word.
    pub fn control_waiting(&mut self) -> bool {
        // NO CALL LOOP, NO CONTROL PLANE. An image built before the compiler
        // put one in every image has none, as one built before `flint.system`
        // existed had no control plane: it is a sandbox nothing can call, a
        // coherent thing to be, and it must SETTLE when its program is done
        // rather than wait on a host for messages it cannot serve.
        if !crate::conc::has_call_loop(self) {
            return false;
        }
        let sp: Value = self.conc_system_port();
        if sp.is_nil() {
            return false;
        }
        let s: Value = self.sched();
        if s.is_nil() {
            return false;
        }
        return !(self.slot(s, crate::conc::SC_CTRL) == TRUE);
    }
    /// Close every bound port and forget them. What `:close` does, and what
    /// the end of the system port does: a call thread parked on a port nobody
    /// can reach any more would be a thread nothing can ever wake.
    pub fn close_bound(&mut self) -> Value {
        let base: usize = self.mark();
        let s0: Value = self.sched();
        let si: usize = self.push(s0);
        let b0: Value = self.slot(self.r(si), crate::conc::SC_BOUND);
        let bi: usize = self.push(b0);
        if !self.r(bi).is_nil() {
            let n: u32 = self.vec_count(self.r(bi));
            let mut i: u32;
            i = 0;
            while i < n {
                let p: Value = self.vec_nth(self.r(bi), i, NIL);
                if self.is_port(p) {
                    self.close_at(p);
                }
                i += 1;
            }
        }
        self.set(self.r(si), crate::conc::SC_BOUND, NIL);
        self.pop_to(base);
        return NIL;
    }
    /// `:unbind p`: close it -- the call thread's receive then answers
    /// end-of-stream and its loop ends -- and drop it from the bound list,
    /// by identity.
    pub fn unbind_port(&mut self, p: Value) -> Value {
        let base: usize = self.mark();
        let pi: usize = self.push(p);
        let si: usize = self.push(self.sched());
        self.close_at(self.r(pi));
        let bi: usize = self.push(self.slot(self.r(si), crate::conc::SC_BOUND));
        let oi: usize = self.push(self.empty_vec());
        if !self.r(bi).is_nil() {
            let n: u32 = self.vec_count(self.r(bi));
            let mut i: u32;
            i = 0;
            while i < n {
                let q: Value = self.vec_nth(self.r(bi), i, NIL);
                if q != self.r(pi) {
                    let grown: Value = self.vec_conj(self.r(oi), q);
                    self.set_r(oi, grown);
                }
                i += 1;
            }
        }
        self.set(self.r(si), crate::conc::SC_BOUND, self.r(oi));
        self.pop_to(base);
        return NIL;
    }
    /// `:bind p`: start the call loop on `p` and remember `p`, so `:close`
    /// can stop it. Nothing is remembered when there is no call loop to start
    /// -- an image built before there was one.
    pub fn bind_port(&mut self, p: Value) -> Value {
        let base: usize = self.mark();
        let pi: usize = self.push(p);
        if crate::conc::spawn_call(self, self.r(pi)) {
            let si: usize = self.push(self.sched());
            let bi: usize = self.push(self.slot(self.r(si), crate::conc::SC_BOUND));
            if self.r(bi).is_nil() {
                self.set_r(bi, self.empty_vec());
            }
            let grown: Value = self.vec_conj(self.r(bi), self.r(pi));
            self.set(self.r(si), crate::conc::SC_BOUND, grown);
        }
        self.pop_to(base);
        return NIL;
    }
    /// Serve the system port: every control message waiting, in order.
    /// 
    /// CALLED BY `drive` AT THE TOP OF EVERY ITERATION, between turns. Nothing
    /// here runs flint code and nothing parks, so a whole queue is served in one
    /// go -- where a control plane on a green thread took one message per turn.
    /// 
    /// A SNAPSHOT IN FLIGHT COMES FIRST, and control waits behind it, as it did
    /// when the control plane streamed it itself: `snapshot-idle` pumps what the
    /// destination has room for and says whether the stream is done.
    /// 
    /// THE BYTE REFUND is `receive-at`'s: a bridge queues `[len bytes ports]` and
    /// `len` is what the deliver CHARGED. The message stays rooted until it has
    /// been served, because its `ports` are what hold the port it names -- the
    /// intern table is weak.
    /// 
    /// THE END OF THE SYSTEM PORT is the end of the control plane: once it is
    /// closed and drained, every bound port is closed, as `flint.system/serve`
    /// did when its receive answered nil.
    pub fn serve_control_at(&mut self) -> Value {
        if !crate::snap::idle(self) {
            return NIL;
        }
        let sp0: Value = self.conc_system_port();
        if sp0.is_nil() {
            return NIL;
        }
        if !self.control_waiting() {
            return NIL;
        }
        // THE PROGRAM'S INITIALISERS RUN BEFORE ANY CONTROL MESSAGE is
        // served, on the first drive that finds a system port -- which is
        // when booting `flint.system` ran them. A call resolves its `:fn` to
        // a var's value, and a var is nil until they have.
        if !self.ensure_started() {
            return NIL;
        }
        let base: usize = self.mark();
        let spi: usize = self.push(sp0);
        loop {
            if self.ring_inbox_count(self.r(spi)) == 0 {
                if self.receive_drained(self.r(spi)) != 0 {
                    self.close_bound();
                    self.set(self.sched(), crate::conc::SC_CTRL, TRUE);
                }
                self.pop_to(base);
                return NIL;
            }
            let got: Value = self.ring_dequeue(self.r(spi));
            let ii: usize = self.push(got);
            if crate::conc::crosses_a_heap(self.slot(self.r(spi), crate::conc::PT_KIND).as_fixnum()) {
                let n: i64 = self.vec_nth(self.r(ii), 0, NIL).as_fixnum();
                let queued: i64 = self.slot(self.r(spi), crate::conc::PT_BYTES).as_fixnum();
                if queued > n {
                    self.set(self.r(spi), crate::conc::PT_BYTES, Value::fixnum((queued - n) as i64));
                }
                if !(queued > n) {
                    self.set(self.r(spi), crate::conc::PT_BYTES, Value::fixnum(0 as i64));
                }
            }
            self.wake_on(self.r(spi));
            let e: Value = self.empty_vec();
            let ai: usize = self.push(e);
            let body: Value = self.vec_nth(self.r(ii), 1, NIL);
            let rd: Value = self.wire_reader(body, false);
            let rdi: usize = self.push(rd);
            let code: i64 = self.wire_control_op(self.r(rdi), ai);
            let op: i64 = code % 8;
            let id: i64 = (code / 8) - 1;
            let mut p: Value;
            p = NIL;
            if (code >= 0) && (id >= 0) {
                p = self.port_by_id(id);
            }
            if (op == 1) && self.is_port(p) {
                self.bind_port(p);
            }
            if (op == 2) && self.is_port(p) {
                self.unbind_port(p);
            }
            if op == 3 {
                self.close_bound();
                self.set(self.sched(), crate::conc::SC_CTRL, TRUE);
                self.pop_to(base);
                return NIL;
            }
            if (op == 4) && self.is_port(p) {
                crate::snap::begin(self, p);
                if !crate::snap::idle(self) {
                    self.pop_to(base);
                    return NIL;
                }
            }
            self.pop_to(ii);
        }
    }
}
