// Generated by kin from the source named below. Do not edit.
// source: flint.rt.mainanswer

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::vecread::*;

impl Rt {
    /// The answer the thread a host started left behind.
    /// 
    /// THREAD 0 SPEAKS FOR THE PROGRAM. It is the thread the host started, so
    /// its outcome is the program's outcome; anything else still parked when
    /// the scheduler settles is waiting for something that is never coming.
    /// 
    /// A FAILURE GOES BACK ON `thrown`, AND THE ANSWER IS NIL. That is the
    /// whole point: `TH_RESULT` holds the error for a failed thread and the
    /// value for a finished one, so returning it either way hands the host a
    /// value it cannot classify. The boundary looks at `thrown` to decide
    /// status, and this is what puts it there.
    /// 
    /// NO SCHEDULER, OR NO THREAD 0, IS NIL rather than a throw. A program
    /// that never started a thread has no outcome to report, and inventing a
    /// failure for it would make an empty program look like a broken one.
    pub fn main_answer(&mut self) -> Value {
        let s: Value = self.sched();
        if s.is_nil() {
            return NIL;
        }
        let ts: Value = self.slot(s, crate::conc::SC_THREADS);
        let th: Value = self.vec_nth(ts, 0, NIL);
        if th.is_nil() {
            return NIL;
        }
        let r: Value = self.slot(th, crate::conc::TH_RESULT);
        let st: i64 = self.slot(th, crate::conc::TH_STATUS).as_fixnum();
        if st == crate::conc::ST_FAILED {
            // STRAIGHT ACROSS, unwrapped. Nothing allocates between
            // the read and the write, which is what lets a heap value
            // pass through a field no root walk visits.
            self.thrown = r;
            return NIL;
        }
        return r;
    }
}
