// Generated by kin from the source named below. Do not edit.
// source: flint.rt.mapmake

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::seqwalk::*;

impl Rt {
    /// An ARRAY MAP from a flat sequence of keys and values, in order.
    pub fn ordered_map(&mut self, kvs: Value) -> Value {
        let base: usize = self.mark();
        let s0: Value = self.seq(kvs);
        let si: usize = self.push(s0);
        let vals_at: usize = self.mark();
        let mut count: u32;
        count = 0;
        loop {
            if self.r(si).is_nil() {
                break;
            }
            // PUSHED BEFORE THE NEXT STEP, because `next` can collect
            // and a value held anywhere but the shadow stack does not
            // survive that (`a-vec-of-values-is-not-a-root`).
            let x: Value = self.first(self.r(si));
            self.push(x);
            count += 1;
            let nx: Value = self.next(self.r(si));
            self.set_r(si, nx);
        }
        if (count % 2) != 0 {
            self.pop_to(base);
            return self.throw_str("IllegalArgumentException", &"array-map needs an even number of forms");
        }
        let n: u32 = count / 2;
        let a: Addr = self.alloc(TY_ARRAYMAP, AM_BASE + (2 * n));
        if a == 0 {
            self.pop_to(base);
            return NIL;
        }
        self.set_slot(a, AM_META, NIL);
        self.set_slot(a, AM_HASH, NIL);
        let mut i: u32;
        i = 0;
        while i < (2 * n) {
            self.set_slot(a, AM_BASE + i, self.r(vals_at + i as usize));
            i += 1;
        }
        self.pop_to(base);
        return Value::heap(a);
    }
    /// A VOLATILE box holding `v`.
    /// 
    /// One slot, and the box is what a program holds: `volatile!` exists so a
    /// single thread can mutate without the atomicity an atom pays for.
    pub fn new_volatile(&mut self, v: Value) -> Value {
        let base: usize = self.mark();
        let vi: usize = self.push(v);
        let a: Addr = self.alloc(TY_VOLATILE, 1);
        if a == 0 {
            self.pop_to(base);
            return NIL;
        }
        // READ BACK FROM THE ROOT: the allocation may have moved it.
        self.set_slot(a, 0, self.r(vi));
        self.pop_to(base);
        return Value::heap(a);
    }
}
