// Generated by kin from the source named below. Do not edit.
// source: flint.rt.meta

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};

impl Rt {
    /// Can `v` carry metadata at all?
    /// 
    /// A PREDICATE AND A TOTAL ACCESSOR rather than an optional slot index, the
    /// same shape `is-int` and `i64-of` take. Rust answered `Option<u32>` and
    /// there is no slot number free to mean `nowhere` -- slot 0 is a real slot
    /// for an empty list.
    pub fn has_meta(&self, v: Value) -> bool {
        if !v.is_heap() {
            return false;
        }
        let t: u8 = ty(&self.gc.sp, v.as_heap());
        if t == TY_SYM {
            return true;
        }
        if t == TY_VEC {
            return true;
        }
        if t == TY_ARRAYMAP {
            return true;
        }
        if t == TY_HASHMAP {
            return true;
        }
        if t == TY_SET {
            return true;
        }
        if t == TY_CONS {
            return true;
        }
        if t == TY_EMPTY_LIST {
            return true;
        }
        if t == TY_LAZYSEQ {
            return true;
        }
        if t == TY_ATOM {
            return true;
        }
        if t == TY_CLOSURE {
            return true;
        }
        if t == TY_TAGGED {
            return true;
        }
        return false;
    }
    /// WHICH slot holds `v`'s metadata. Ask `has-meta` first.
    pub fn meta_slot(&mut self, v: Value) -> u32 {
        let t: u8 = ty(&self.gc.sp, v.as_heap());
        if t == TY_SYM {
            return 2;
        }
        if t == TY_VEC {
            return V_META;
        }
        if t == TY_ARRAYMAP {
            return AM_META;
        }
        if t == TY_HASHMAP {
            return HM_META;
        }
        if t == TY_SET {
            return crate::set::S_META;
        }
        if t == TY_CONS {
            return C_META;
        }
        if t == TY_EMPTY_LIST {
            return 0;
        }
        if t == TY_LAZYSEQ {
            return 2;
        }
        if t == TY_ATOM {
            return 1;
        }
        // THE LAST SLOT for a closure -- see the header.
        if t == TY_CLOSURE {
            return self.olen(v) - 1;
        }
        // A TAGGED FORM keeps the tag at 0 and the form at 1, so metadata
        // goes after them. A raw 2, like `TY_SYM` and `TY_LAZYSEQ` above:
        // this function is where the slot numbers live.
        if t == TY_TAGGED {
            return 2;
        }
        return 0;
    }
    /// The metadata, or nil when the value cannot carry any.
    pub fn meta_of(&mut self, v: Value) -> Value {
        if !self.has_meta(v) {
            return NIL;
        }
        // HOISTED: `slot` borrows and `meta-slot` takes `&mut self`, so
        // nesting them is an immutable and a mutable borrow at once.
        let at: u32 = self.meta_slot(v);
        return self.slot(v, at);
    }
    /// A COPY of `v` with `m` as its metadata, or `v` unchanged when it cannot
    /// carry any.
    /// 
    /// A COPY, because metadata is part of the value: two vectors that differ
    /// only in their metadata are still `=`, but they are not the same object,
    /// and changing one must not change the other.
    pub fn with_meta(&mut self, v: Value, m: Value) -> Value {
        if !self.has_meta(v) {
            return v;
        }
        let idx: u32 = self.meta_slot(v);
        let base: usize = self.mark();
        let vi: usize = self.push(v);
        let mi: usize = self.push(m);
        let t: u8 = ty(&self.gc.sp, v.as_heap());
        let n: u32 = self.olen(v);
        let out: Value = self.new_obj(t, n);
        if out.is_nil() {
            self.pop_to(base);
            return NIL;
        }
        // COPIED FROM THE ROOT, not from the host local: the allocation
        // may have moved `v` (0031).
        for i in 0..n {
            self.set(out, i, self.slot(self.r(vi), i));
        }
        self.set(out, idx, self.r(mi));
        self.pop_to(base);
        return out;
    }
}
