// Generated by kin from the source named below. Do not edit.
// source: flint.rt.names

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::hash::*;
use crate::kgen::rt::pike::*;

impl Rt {
    /// Is `v` a symbol?
    /// 
    /// NO INLINE TIER, unlike a keyword. A symbol carries a hash it cannot
    /// recompute cheaply, so it is always a heap object.
    pub fn is_symbol(&self, v: Value) -> bool {
        if !v.is_heap() {
            return false;
        }
        return ty(&self.gc.sp, v.as_heap()) == TY_SYM;
    }
    /// Is `v` a keyword, either tier?
    /// 
    /// TWO TIERS, unlike a symbol: a short bare keyword lives in the value word
    /// itself, so the inline test comes first and costs nothing.
    /// 
    /// The ports grew this to serve the generated tree -- they had only
    /// `typeP(5, v)`, a magic number in a dispatch switch -- and then all three
    /// carried the same four lines. `type-p` asks it here now, and so do
    /// `tablekind`, `tablemake` and `valcmp`.
    pub fn is_keyword(&self, v: Value) -> bool {
        if v.is_inline_kw() {
            return true;
        }
        if !v.is_heap() {
            return false;
        }
        return ty(&self.gc.sp, v.as_heap()) == TY_KW;
    }
    /// The `name` part of a string, keyword or symbol, as a string.
    pub fn name_of(&mut self, v: Value) -> Value {
        if v.is_inline_kw() {
            return v.kw_to_str();
        }
        if v.is_heap() {
            let t: u8 = ty(&self.gc.sp, v.as_heap());
            if t == TY_KW {
                return self.slot(v, 1);
            }
            if t == TY_SYM {
                return self.slot(v, 1);
            }
        }
        // A STRING IS ITS OWN NAME, and so is anything else: this is asked
        // while building a message about a value whose shape is already in
        // question, and a refusal here would replace that message with one
        // about the message.
        return v;
    }
    /// The `namespace` part, or nil.
    pub fn ns_of(&self, v: Value) -> Value {
        if v.is_inline_kw() {
            return NIL;
        }
        if v.is_heap() {
            let t: u8 = ty(&self.gc.sp, v.as_heap());
            if t == TY_KW {
                return self.slot(v, 0);
            }
            if t == TY_SYM {
                return self.slot(v, 0);
            }
        }
        return NIL;
    }
    /// A symbol's hash, which it carries.
    /// 
    /// COMPUTED ONCE at construction and read here. A symbol's hash combines
    /// its namespace and its name, and recomputing it would mean walking two
    /// strings on every map lookup.
    pub fn symbol_hash(&self, v: Value) -> u32 {
        return self.slot(v, 3).as_fixnum() as u32;
    }
}
