// Generated by kin from the source named below. Do not edit.
// source: flint.rt.nouns

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};

impl Rt {
    /// The literal noun phrase for `v`, or the empty one when there is none.
    /// 
    /// BORROWED, not built. Every answer here is a string literal, which is a
    /// `&'
    /// '
    /// 'static str` in Rust and already a `String` in both ports, so naming
    /// one costs nothing anywhere -- the conversion happens once, in `describe`.
    /// 
    /// The empty answer means `no literal fits`, which only a heap value with a
    /// tag this function does not know can produce.
    pub(crate) fn describe_literal(&self, v: Value) -> &'static str {
        if v.is_nil() {
            return "nil";
        }
        if v.is_fixnum() {
            return "an integer";
        }
        if v.is_double() {
            return "a double";
        }
        if v == TRUE {
            return "a boolean";
        }
        if v == FALSE {
            return "a boolean";
        }
        if v.is_inline_str() {
            return "a string";
        }
        if v.is_inline_kw() {
            return "a keyword";
        }
        if !v.is_heap() {
            return "an unknown immediate";
        }
        let t: u8 = ty(&self.gc.sp, v.as_heap());
        if t == TY_STR {
            return "a string";
        }
        if t == TY_SYM {
            return "a symbol";
        }
        if t == TY_KW {
            return "a keyword";
        }
        if t == TY_CONS {
            return "a list";
        }
        if t == TY_EMPTY_LIST {
            return "an empty list";
        }
        if t == TY_LAZYSEQ {
            return "a lazy seq";
        }
        if t == TY_VEC {
            return "a vector";
        }
        if t == TY_VECSEQ {
            return "a vector seq";
        }
        if t == TY_RANGE {
            return "a range";
        }
        if t == TY_ARRAYMAP {
            return "an array-map";
        }
        if t == TY_HASHMAP {
            return "a hash-map";
        }
        if t == TY_SET {
            return "a set";
        }
        if t == TY_MAPENTRY {
            return "a map entry";
        }
        if t == TY_CLOSURE {
            return "a function";
        }
        if t == TY_NATIVEFN {
            return "a builtin";
        }
        if t == TY_TVEC {
            return "a transient vector";
        }
        if t == TY_TMAP {
            return "a transient map";
        }
        if t == TY_TSET {
            return "a transient set";
        }
        if t == TY_ROPE {
            return "a rope";
        }
        if t == TY_BYTES {
            return "a byte string";
        }
        if t == TY_RECORD {
            return "a record";
        }
        if t == TY_ATOM {
            return "an atom";
        }
        if t == TY_VAR {
            return "a var";
        }
        if t == TY_DELAY {
            return "a delay";
        }
        if t == TY_REGEX {
            return "a regex";
        }
        if t == TY_MULTIFN {
            return "a multimethod";
        }
        if t == TY_REDUCED {
            return "a reduced";
        }
        if t == TY_EXINFO {
            return "an ex-info";
        }
        // NO LITERAL FOR THIS ONE, which is the single case that has to
        // BUILD a string. Answering the empty literal says so without
        // needing an `Option`, and the empty string is not a noun phrase
        // any other arm could return.
        return "";
    }
    /// What `v` is, as the noun phrase an error message needs.
    /// 
    /// `"a keyword"`, `"an empty list"` -- with the article, because every
    /// call site reads `"seq over " + describe(v) + " ..."` and an article
    /// chosen at the call site would have to know what the noun begins with.
    /// 
    /// ONE ALLOCATION, AND USUALLY NONE OF THE STRING. Forty of the forty-one
    /// answers are literals, so they are borrowed and converted once here rather
    /// than each built where it is named -- in Rust that is one `String::from`
    /// instead of forty, and in both ports it is nothing at all, because a
    /// literal there is already the type this returns.
    /// 
    /// THE TIER IS INVISIBLE, as it is everywhere else. An inline string and a
    /// heap string are both `"a string"`, and an inline keyword and a heap one
    /// are both `"a keyword"` -- these used to say `"an inline keyword"`, which
    /// tells a reader about a representation they cannot see from the language
    /// and cannot act on. `DECISIONS.md#strings-and-matching` makes the tiers invisible to
    /// every other operation; an error message is not the place to leak them.
    /// 
    /// The last arm names the NUMBER of a tag it does not know. A tag added to
    /// one runtime and not to this function still produces something a person
    /// can act on, which is the only arm here that could ever be reached by a
    /// correct program and the reason it builds a string instead of refusing.
    pub fn describe(&self, v: Value) -> alloc::string::String {
        let lit: &'static str = self.describe_literal(v);
        if !lit.is_empty() {
            return alloc::string::String::from(lit);
        }
        // HOLE 5's one live use in this file: `str-cat` is variadic, so its
        // Rust side constructs the format string from the argument count,
        // which no template can do.
        return alloc::format!("{}{}", "object type ", ty(&self.gc.sp, v.as_heap()));
    }
}
