// Generated by kin from the source named below. Do not edit.
// source: flint.rt.numf64

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::numkind::*;
use crate::kgen::rt::valtag::*;

impl Rt {
    /// Any number as a double; NaN when `v` is not a number.
    /// 
    /// The double first, because it is the test on the value word and needs no
    /// tag read. `double-value` is a REINTERPRETATION of the bits and not a
    /// conversion -- the number is already there.
    /// 
    /// `f64-of-bits` is `Double.longBitsToDouble` on the jvm, which is the
    /// SAFE direction of that pair: it hands back the pattern it was given.
    /// Its opposite, `doubleToLongBits`, canonicalises every NaN it is shown
    /// and produced a generated-code divergence of its own -- see the
    /// `f64-bits` record in DECISIONS.md. Reading bits into a double is not
    /// the hazard; writing a double out to bits is.
    pub fn number_f64(&self, v: Value) -> f64 {
        if v.is_double() {
            return double_value(v);
        }
        if self.is_int(v) {
            return self.i64_of(v) as f64;
        }
        return f64::from_bits(crate::value::CANONICAL_NAN as u64);
    }
    /// -1, 0 or 1. NaN sorts as EQUAL to everything, matching the use of
    /// `Double.compare` inside Clojure's `compare`.
    /// 
    /// BOTH INTEGERS TAKE THE INTEGER PATH, and the reason is not speed: two
    /// i64s past 2^53 are not distinguishable once promoted to double, so
    /// comparing them as doubles would call unequal integers equal.
    /// 
    /// The branch is spelled out rather than delegated to a host comparator.
    /// `Long.compare` and `CompareTo` are each documented to return only the
    /// SIGN, and both happen to return -1/0/1; native already wrote the
    /// branch. Three hosts with three idioms is three chances to decide an
    /// edge differently, which is what `(quot MIN -1)` did.
    pub fn number_cmp(&self, a: Value, b: Value) -> i32 {
        if self.is_int(a) && self.is_int(b) {
            let x: i64 = self.i64_of(a);
            let y: i64 = self.i64_of(b);
            if x < y {
                return -1;
            }
            if x > y {
                return 1;
            }
            return 0;
        }
        let p: f64 = self.number_f64(a);
        let q: f64 = self.number_f64(b);
        if p < q {
            return -1;
        }
        if p > q {
            return 1;
        }
        return 0;
    }
}
