// Generated by kin from the source named below. Do not edit.
// source: flint.rt.objsize

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::objhdr::*;

/// Which of the three shapes `ty` has.
/// 
/// SLOTS UNLESS NAMED OTHERWISE, and the default is the safe one: a type
/// the allocator has not heard of is laid out as values, so the collector
/// traces it. Defaulting to RAW would hide a new type's references from
/// the collector, and the failure would be a freed live object rather than
/// a wasted word.
/// 
/// A STRING IS ITS OWN SHAPE because its bytes do not begin where every
/// other object's body does -- `STR_DATA` and not `HDR`.
/// 
/// THE RAW FIVE ARE THE ALLOCATOR'S OWN, three of which no guest ever
/// sees: `TY_FREE` is a hole in the old space and `TY_FWD` an object that
/// has moved. Both are walked by the sweeper, so both must size correctly
/// or the walk steps into the middle of the next object.
pub fn layout_of(ty: u8) -> crate::obj::Layout {
    if ty == TY_STR {
        return crate::obj::Layout::Str;
    }
    if (ty == TY_BIGINT) || ((ty == TY_RAW) || ((ty == TY_BYTES) || ((ty == TY_FREE) || (ty == TY_FWD)))) {
        return crate::obj::Layout::Raw;
    }
    return crate::obj::Layout::Vals;
}
/// How many BYTES an object of `ty` with `len` occupies.
/// 
/// `len` MEANS DIFFERENT THINGS PER LAYOUT, which is the whole reason this
/// is one function and not three call sites. For slots it is a COUNT and
/// each is eight bytes wide; for the other two it is already a byte count.
/// Reading it as bytes for a vector would size a ten-element vector at
/// ten bytes and hand back an object the collector walks off the end of.
/// 
/// ONLY THE BYTE LAYOUTS ROUND. A slot count multiplied by eight is
/// already a multiple of eight, so rounding it is a no-op that would only
/// hide a mistake in the multiply; the two byte layouts round because a
/// caller may ask for any length at all.
/// 
/// THE ANSWER IS BYTES AND THE CHARGE IS `>> 3`. The caller divides; this
/// does not, because the sweeper walks in bytes and would step wrong on a
/// size already divided.
pub fn size_for(ty: u8, len: u32) -> Addr {
    let lay: crate::obj::Layout = layout_of(ty);
    // WIDENED BEFORE THE ARITHMETIC. A length is 32-bit and an
    // address is 64; Java and C# widen silently and Rust does not,
    // so the conversion is said here rather than left to whichever
    // target happens to tolerate it. Native's copy says `len as
    // Addr` in the same three places.
    if lay == crate::obj::Layout::Vals {
        return crate::obj::HDR + ((len as Addr) * 8);
    }
    if lay == crate::obj::Layout::Str {
        return crate::obj::align8(crate::obj::STR_DATA + (len as Addr));
    }
    return crate::obj::align8(crate::obj::HDR + (len as Addr));
}
/// How many bytes this object occupies, header included.
/// 
/// IN THIS FILE AND NOT `objhdr.kin`, which is where it was written
/// first and where it did not compile: the generated module globs both
/// the hand-written `Obj` and its own siblings, and `size-for` exists in
/// BOTH -- once here and once as the delegator `Obj` keeps for its four
/// callers. Two globs offering one name make it ambiguous rather than
/// resolving it. Beside `size-for` the call is to a LOCAL definition,
/// which shadows a glob on all three targets, and the two belong
/// together anyway: they must agree for every type, since one measures
/// a live object and the other reserves room for a new one.
/// 
/// TWO SPECIAL CASES AND THEN `size-for`, which is the point. This used to
/// carry its own copy of the layout match, and a type added to `layout-of`
/// but not to that copy was sized as `HDR + len * 8` -- a 513-byte
/// `TY_BYTES` measured as 4112. The collector then walked from-space with
/// the wrong stride and blamed an object that was perfectly fine. Deriving
/// the size from one table removes the second one.
/// 
/// A FREE BLOCK'S LENGTH IS ITS SIZE IN BYTES, and it is the one length
/// that can genuinely set the high bit -- which is why it is widened with
/// `addr-of-u32` rather than `to-addr`. All three runtimes already did this
/// by three different routes: `len as Addr`, `Integer.toUnsignedLong(len)`
/// and `(uint) len`.
pub fn obj_size_of(sp: &Space, addr: Addr) -> Addr {
    let ty: u8 = obj_ty(sp, addr) as u8;
    let len: u32 = obj_len(sp, addr);
    if ty == TY_FREE {
        return len as Addr;
    }
    if ty == TY_FWD {
        return crate::obj::HDR;
    }
    return size_for(ty, len);
}
/// Would allocating a `ty`/`len` object trigger a collection?
/// 
/// Asked BEFORE allocating, because under several executors a collection
/// has to be staged -- everyone stopped -- and staging one around every
/// allocation would be a stop-the-world per allocation. Conservative on
/// purpose: a false yes costs one needless safepoint, a false no would let
/// the collector move objects while another thread was running.
/// 
/// IN THIS FILE for the reason `size-of` is: it calls `size-for`, and
/// beside `size-for` that is a LOCAL call. From anywhere else the
/// generated module globs both the hand-written `Obj` and its siblings,
/// both of which offer a `size_for`, and two globs offering one name make
/// it ambiguous rather than resolving it.
/// 
/// NATIVE SATURATED HERE AND THE PORTS DID NOT -- `bump.saturating_add`
/// against a plain `+`. That is a real difference and it is unreachable:
/// `max_heap` is built from a `u32`, so every operand is at most 4 GiB and
/// the sum is at most about 2^33, nowhere near where a 64-bit add wraps.
/// Plain addition IS the saturating answer over that range, so the three
/// converge on the simpler body rather than on a guard that cannot fire.
/// If the heap limit ever stops being a `u32`, this is the line that has
/// to change with it.
pub fn gc_would_collect(gc: &Gc, ty: u8, len: u32) -> bool {
    let size: Addr = size_for(ty, len);
    if size >= (crate::gc::LARGE_OBJECT as Addr) {
        return true;
    }
    return (gc.bump + size) > (gc.from + gc.half);
}
