// Generated by kin from the source named below. Do not edit.
// source: flint.rt.portbytes

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};

impl Rt {
    /// DOES `len` MORE FIT, given `queued` already there and a bound of `cap`?
    /// 
    /// THE RULE WAS WRITTEN SIX TIMES -- twice in each runtime, once on the
    /// guest's send path and once on the host's deliver path -- and the two
    /// paths differ in everything EXCEPT this: one parks and one refuses, one
    /// claims atomically and one does not. What they must never differ in is
    /// which messages fit, because a message accepted one way and refused the
    /// other is a bridge that behaves differently depending on which end spoke.
    /// 
    /// IT TAKES THE NUMBERS, not the port, for that reason: the deliver path
    /// must test the value it is about to compare-and-swap AGAINST, and a
    /// version that re-read the port here would test one number and swap on
    /// another.
    /// 
    /// AN EMPTY QUEUE ALWAYS FITS, however large the message. Without that
    /// there is no state of the queue in which an oversized message fits, so it
    /// is refused for ever rather than delayed -- back-pressure silently
    /// becoming a permanent rejection. The bound exists to stop messages
    /// ACCUMULATING; a maximum message size is a different rule and is not
    /// this one.
    /// 
    /// THE BOUND IS INCLUSIVE: filling it exactly is allowed.
    pub fn fits_in_budget(&mut self, queued: i64, len: i64, cap: i64) -> bool {
        return (queued == 0) || ((queued + len) <= cap);
    }
    /// CLAIM `len` BYTES on `p`, or refuse. True when the claim was made.
    /// 
    /// AN EMPTY QUEUE ALWAYS ACCEPTS, however large the message, and the
    /// `queued > 0` in the test is what says so. Without it a message bigger
    /// than the whole budget could never be delivered AT ALL: there would be no
    /// state of the queue in which it fits, so it would be refused for ever
    /// rather than merely delayed, and back-pressure would have turned into a
    /// permanent rejection. The bound's job is to stop messages ACCUMULATING,
    /// not to impose a maximum message size -- that is a different rule and
    /// would have to be stated somewhere a caller can see it.
    /// 
    /// THE BOUNDARY IS INCLUSIVE: filling the budget exactly is allowed, and
    /// only going PAST it is refused. `>` rather than `>=` is the whole of it.
    /// 
    /// A REFUSAL TOUCHES NOTHING. It returns before the compare-and-swap, so a
    /// host that is told no has not moved the counter -- which matters because
    /// the refusal is retried, and a refusal that charged would drain the
    /// budget by being asked.
    /// 
    /// THE READ IS INSIDE THE LOOP. Hoisting it would retry with the value the
    /// race was already lost against: the compare would keep failing, or worse
    /// succeed later against a stale number and write a total that never
    /// accounted for the other thread's claim.
    pub fn claim_bytes(&mut self, p: Value, len: i64) -> bool {
        let cap: i64 = self.slot(p, crate::conc::PT_CAP).as_fixnum();
        loop {
            let queued: i64 = self.slot_atomic(p, crate::conc::PT_BYTES).as_fixnum();
            if !self.fits_in_budget(queued, len, cap) {
                return false;
            }
            if self.cas_slot(p, crate::conc::PT_BYTES, Value::fixnum(queued), Value::fixnum(queued + len)) {
                return true;
            }
        }
    }
    /// GIVE `len` BYTES BACK, for a message that was charged and never arrived.
    /// 
    /// A delivery claims its bytes BEFORE it can fail -- the ring may be full,
    /// or the message may not scan -- and a message the guest never saw must
    /// not go on counting against its bound. Otherwise a host that offers a
    /// message repeatedly into a full ring drains the budget with traffic that
    /// was never accepted, and the port wedges.
    /// 
    /// CLAMPED AT ZERO rather than trusting the arithmetic. The counter is
    /// unsigned on one target and signed on the others, so a refund larger than
    /// the balance is a huge positive number in one runtime and a negative in
    /// the other two -- the kind of disagreement that shows up as a port that
    /// will not accept anything on exactly one runtime.
    /// 
    /// RE-READ IN THE LOOP for the same reason as the claim.
    pub fn give_back(&mut self, p: Value, len: i64) -> Value {
        loop {
            let q: i64 = self.slot_atomic(p, crate::conc::PT_BYTES).as_fixnum();
            let mut back: i64;
            back = 0;
            if q > len {
                back = q - len;
            }
            if self.cas_slot(p, crate::conc::PT_BYTES, Value::fixnum(q), Value::fixnum(back)) {
                return NIL;
            }
        }
    }
}
