// Generated by kin from the source named below. Do not edit.
// source: flint.rt.portmake

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::vecwrite::*;

impl Rt {
    /// A NEW PORT, with every slot of it set.
    /// 
    /// `id` BELOW ZERO means "choose one", and only then is `SC_NEXTID`
    /// consumed. A host-assigned id is the host's own and must leave the
    /// counter alone, or the same number is handed out twice later.
    /// 
    /// THE RING IS ALLOCATED ONCE AND NEVER AGAIN, because a send must not
    /// allocate -- allocation is where the old inbox lost messages. Its size is
    /// the channel's cap, floored at one: a zero-capacity channel with a
    /// zero-length ring can never accept anything, and `channel` is allowed to
    /// ask for nothing. A bridge takes `RING_MESSAGES` instead, its own cap
    /// being a byte budget rather than a message count.
    /// 
    /// EVERY SLOT IS FILLED even where the value is the type's zero, and that
    /// is deliberate: a fresh object's slots are whatever `new-obj` left, and
    /// every reader downstream treats these as initialised.
    /// 
    /// `PT_PEER` IS AN ID AND STARTS AT -1. A field holding the peer OBJECT
    /// would keep it alive, and an unreachable flint end is precisely what says
    /// the script is done with it.
    pub fn new_port_at(&mut self, cap: i64, label: Value, kind: i64, state: i64, id: i64) -> Value {
        let base: usize = self.mark();
        let li: usize = self.push(label);
        let p0: Value = self.new_obj(TY_PORT, crate::conc::PT_LEN);
        if p0.is_nil() {
            self.pop_to(base);
            return NIL;
        }
        let pi: usize = self.push(p0);
        let si: usize = self.push(self.sched());
        let mut use_id: i64;
        use_id = id;
        if id < 0 {
            use_id = self.slot(self.r(si), crate::conc::SC_NEXTID).as_fixnum();
            self.set(self.r(si), crate::conc::SC_NEXTID, Value::fixnum(use_id + 1));
        }
        self.set(self.r(pi), crate::conc::PT_ID, Value::fixnum(use_id));
        self.set(self.r(pi), crate::conc::PT_STATE, Value::fixnum(state));
        self.set(self.r(pi), crate::conc::PT_CAP, Value::fixnum(cap));
        let mut ring: i64;
        ring = crate::conc::RING_MESSAGES;
        if kind == crate::conc::K_CHANNEL {
            ring = cap;
            if ring < 1 {
                ring = 1;
            }
        }
        self.set(self.r(pi), crate::conc::PT_RING, Value::fixnum(ring));
        // THE ALLOCATION IS BOUND BEFORE IT IS PUSHED. Both `new-obj`
        // and `push` take the runtime mutably, so nesting them is two
        // overlapping mutable borrows in Rust -- the hand-written copy
        // hoisted it for the same reason.
        let slots: Value = self.new_obj(TY_NODE, ring as u32);
        let sli: usize = self.push(slots);
        for i in 0..ring as u32 {
            self.set(self.r(sli), i, crate::value::EMPTY);
        }
        self.set(self.r(pi), crate::conc::PT_INBOX, self.r(sli));
        self.set(self.r(pi), crate::conc::PT_READ, Value::fixnum(0));
        self.set(self.r(pi), crate::conc::PT_WRITE, Value::fixnum(0));
        self.set(self.r(pi), crate::conc::PT_BYTES, Value::fixnum(0));
        self.set(self.r(pi), crate::conc::PT_PEER, Value::fixnum(0 - 1));
        self.set(self.r(pi), crate::conc::PT_LABEL, self.r(li));
        self.set(self.r(pi), crate::conc::PT_KIND, Value::fixnum(kind));
        self.register_port(self.r(pi));
        let out: Value = self.r(pi);
        self.pop_to(base);
        return out;
    }
    /// ONE DIRECTION of a pairing, appended to `SC_PAIRS`.
    /// 
    /// Its own function because it is done TWICE and the two calls differ only
    /// in the order of their arguments -- which is exactly the shape a reader
    /// skims past when it is written out twice inline.
    pub fn pair_into(&mut self, si: usize, x: i64, y: i64) -> Value {
        let pi: usize = self.push(self.slot(self.r(si), crate::conc::SC_PAIRS));
        let ei: usize = self.push(self.empty_vec());
        // BOUND, THEN SET. `vec-conj` and `set-r` both take the runtime
        // mutably, so nesting them is two overlapping borrows in Rust --
        // the same hoist `reap-bridges` makes for the same reason.
        let e1: Value = self.vec_conj(self.r(ei), Value::fixnum(x));
        self.set_r(ei, e1);
        let e2: Value = self.vec_conj(self.r(ei), Value::fixnum(y));
        self.set_r(ei, e2);
        let np: Value = self.vec_conj(self.r(pi), self.r(ei));
        self.set(self.r(si), crate::conc::SC_PAIRS, np);
        self.pop_to(pi);
        return NIL;
    }
    /// WIRE TWO ENDS TOGETHER, in BOTH directions and in both places.
    /// 
    /// Each end learns the other's id, and the scheduler learns the pairing
    /// TWICE -- `[a b]` and `[b a]`. The lookup that uses it walks the list
    /// comparing the first element, so a pairing recorded one way only answers
    /// one way, and the end that was second would find no peer at all. That is
    /// indistinguishable from an orphaned port, which is the failure it would
    /// actually present as.
    pub fn link_peers_at(&mut self, a: Value, b: Value) -> Value {
        let ida: i64 = self.slot(a, crate::conc::PT_ID).as_fixnum();
        let idb: i64 = self.slot(b, crate::conc::PT_ID).as_fixnum();
        self.set(a, crate::conc::PT_PEER, Value::fixnum(idb));
        self.set(b, crate::conc::PT_PEER, Value::fixnum(ida));
        let base: usize = self.mark();
        let si: usize = self.push(self.sched());
        self.pair_into(si, ida, idb);
        self.pair_into(si, idb, ida);
        self.pop_to(base);
        return NIL;
    }
    /// A CHANNEL: two ends of one conversation, already wired.
    /// 
    /// BOTH ENDS GET THE SAME CAP AND THE SAME LABEL. The cap because a channel
    /// is one queue seen from two sides and a bound that differed by direction
    /// would be a channel that accepts more one way than the other; the label
    /// because it names the CHANNEL, and an end that reported a different name
    /// from its peer would make a diagnostic read as though two conversations
    /// were involved.
    /// 
    /// THE ENDS ARE RETURNED IN ORDER, `[a b]`, and the caller destructures
    /// them positionally. Nothing distinguishes the two ends otherwise -- they
    /// are symmetric, which is exactly why the order has to be fixed here
    /// rather than discovered.
    pub fn channel_at(&mut self, cap: i64, label: Value) -> Value {
        let base: usize = self.mark();
        let li: usize = self.push(label);
        // ROOTED FIRST, THEN THE SCHEDULER. `ensure-sched` ALLOCATES and
        // `label` arrives as a host local, so running it before the push
        // leaves that local naming the abandoned semispace. The
        // hand-written copies ran it before the mark.
        self.ensure_sched();
        let pa: Value = self.new_port_at(cap, self.r(li), crate::conc::K_CHANNEL, crate::conc::P_OPEN, 0 - 1);
        let ai: usize = self.push(pa);
        let pb: Value = self.new_port_at(cap, self.r(li), crate::conc::K_CHANNEL, crate::conc::P_OPEN, 0 - 1);
        let bi: usize = self.push(pb);
        self.link_peers_at(self.r(ai), self.r(bi));
        let vi: usize = self.push(self.empty_vec());
        let v1: Value = self.vec_conj(self.r(vi), self.r(ai));
        self.set_r(vi, v1);
        let v2: Value = self.vec_conj(self.r(vi), self.r(bi));
        self.set_r(vi, v2);
        let out: Value = self.r(vi);
        self.pop_to(base);
        return out;
    }
    /// A GREEN THREAD, NEW and not yet runnable.
    /// 
    /// `ST_NEW` AND NOT `ST_RUNNABLE`, and the difference is what `run-one`
    /// reads to decide between STARTING this thread at its entry and RESUMING
    /// one that parked. A thread marked runnable before it has ever run would
    /// be restored from a `TH_STACK` of nil and continue off the end of an
    /// empty value stack.
    /// 
    /// IT INHERITS THE BINDINGS LIVE AT THE MOMENT OF THE SPAWN, which is what
    /// makes a dynamic binding dynamic across a `spawn` rather than something
    /// the new thread has to be handed. `TH_BINDINGS` travels with the thread
    /// and `install-bindings` puts it back each time the thread is scheduled.
    /// 
    /// AND AN EMPTY MAP WHEN THERE ARE NONE. The singleton is nil before
    /// anything has bound, and a thread carrying nil there would have every
    /// later binding push onto nothing.
    /// 
    /// THE ID COMES FROM `SC_NEXTID`, the same counter a port's does: it is the
    /// sandbox's counter and not either table's index, so a thread and a port
    /// never share a number and neither is a position in anything.
    /// 
    /// THE ENTRY IS ROOTED FIRST. Everything below allocates.
    pub fn spawn_at(&mut self, f: Value) -> Value {
        let base: usize = self.mark();
        let fi: usize = self.push(f);
        // ROOTED FIRST, AND THIS IS THE ONE THAT BIT. `ensure-sched`
        // ALLOCATES and `f` is a host local; the hand-written copy carried
        // that warning in as many words. Moving the call out to three
        // wrappers put it BEFORE the push and made the ordering nobody's
        // to state -- `conform-hosts`'s GC-stress row caught it within the
        // hour, with `green` answering a raw address.
        self.ensure_sched();
        let th: Value = self.new_obj(TY_THREAD, crate::conc::TH_LEN);
        if th.is_nil() {
            self.pop_to(base);
            return NIL;
        }
        let ti: usize = self.push(th);
        let si: usize = self.push(self.sched());
        let id: i64 = self.slot(self.r(si), crate::conc::SC_NEXTID).as_fixnum();
        self.set(self.r(si), crate::conc::SC_NEXTID, Value::fixnum(id + 1));
        self.set(self.r(ti), crate::conc::TH_STATUS, Value::fixnum(crate::conc::ST_NEW));
        self.set(self.r(ti), crate::conc::TH_ID, Value::fixnum(id));
        self.set(self.r(ti), crate::conc::TH_TOKEN, Value::fixnum(0 - 1));
        self.set(self.r(ti), crate::conc::TH_ENTRY, self.r(fi));
        let binds: Value = self.current_bindings();
        if binds.is_nil() {
            self.set(self.r(ti), crate::conc::TH_BINDINGS, self.empty_map());
        } else {
            self.set(self.r(ti), crate::conc::TH_BINDINGS, binds);
        }
        let tsi: usize = self.push(self.slot(self.r(si), crate::conc::SC_THREADS));
        let nts: Value = self.vec_conj(self.r(tsi), self.r(ti));
        self.set(self.r(si), crate::conc::SC_THREADS, nts);
        let out: Value = self.r(ti);
        self.pop_to(base);
        return out;
    }
}
