// Generated by kin from the source named below. Do not edit.
// source: flint.rt.readtext

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::mapmake::*;
use crate::kgen::rt::numint::*;
use crate::kgen::rt::readconst::*;
use crate::kgen::rt::readcore::*;
use crate::kgen::rt::readnum::*;
use crate::kgen::rt::vecroots::*;

impl Rt {
    /// The digits `from`..`to` in `radix` as a code point, put into `sk`:
    /// `RS_OK`, or the error `from-code-point` gives -- "not a code point"
    /// when the digits are no integer, "not a code point: n" when the
    /// integer is no scalar value -- or "integer overflow" from the
    /// arithmetic before either, as the guest's reader met them.
    pub(crate) fn put_code(&mut self, sti: usize, sk: u32, from: u32, to: u32, radix: i64) -> u32 {
        let base: usize = self.mark();
        let st: u32 = self.parse_int_radix(sti, from, to, radix, false);
        if st == RS_NONE {
            return self.rd_fail_cp(sti, false, 0);
        }
        if st != RS_OK {
            return st;
        }
        let n: i64 = self.integer_value(self.r(base));
        self.pop_to(base);
        if !is_scalar(n) {
            return self.rd_fail_cp(sti, true, n);
        }
        self.sink_put_cp(sk, n as u32);
        return RS_OK;
    }
    /// One escape, after its backslash, into `sk`.
    pub(crate) fn read_escape(&mut self, sti: usize, sk: u32) -> u32 {
        let c: u32 = self.rd_next(sti);
        if c == 116 {
            self.sink_put(sk, 9);
            return RS_OK;
        }
        if c == 114 {
            self.sink_put(sk, 13);
            return RS_OK;
        }
        if c == 110 {
            self.sink_put(sk, 10);
            return RS_OK;
        }
        if c == 92 {
            self.sink_put(sk, 92);
            return RS_OK;
        }
        if c == 34 {
            self.sink_put(sk, 34);
            return RS_OK;
        }
        if c == 98 {
            self.sink_put(sk, 8);
            return RS_OK;
        }
        if c == 102 {
            self.sink_put(sk, 12);
            return RS_OK;
        }
        if c == 117 {
            // FOUR MORE CHARACTERS, or as many as the text has left.
            let from: u32 = self.rd_pos(sti);
            let mut k: u32;
            k = 0;
            while (k < 4) && (self.rd_next(sti) != NO_CP) {
                k += 1;
            }
            return self.put_code(sti, sk, from, from + k, 16);
        }
        if (c >= 48) && (c <= 55) {
            let ofrom: u32 = self.rd_pos(sti) - 1;
            let mut n: u32;
            n = 1;
            loop {
                let p: u32 = self.rd_peek(sti);
                if (n >= 3) || ((p < 48) || (p > 55)) {
                    break;
                }
                self.rd_next(sti);
                n += 1;
            }
            return self.put_code(sti, sk, ofrom, ofrom + n, 8);
        }
        let ek: u32 = self.sink_open();
        self.msg_lit(ek, "unsupported escape \\");
        self.msg_cp(ek, c);
        return self.rd_fail_sink(sti, ek);
    }
    /// A string literal, at its opening quote, pushed.
    pub fn read_string_lit(&mut self, sti: usize) -> u32 {
        self.rd_next(sti);
        let sk: u32 = self.sink_open();
        loop {
            let c: u32 = self.rd_next(sti);
            if c == NO_CP {
                self.sink_close(sk);
                return self.rd_fail_lit(sti, "unterminated string");
            }
            if c == 34 {
                break;
            }
            if c == 92 {
                let st: u32 = self.read_escape(sti, sk);
                if st != RS_OK {
                    self.sink_close(sk);
                    return st;
                }
            } else {
                self.sink_put_cp(sk, c);
            }
        }
        let out: Value = self.sink_string(sk);
        self.sink_close(sk);
        self.push(out);
        return RS_OK;
    }
    /// Push the string `name` names as a character, and answer true; false
    /// when it names none. `from`..`to` is the token.
    pub(crate) fn named_char(&mut self, sti: usize, from: u32, to: u32) -> bool {
        let mut code: u32;
        code = 0;
        let nl: Value = self.string("newline");
        if self.rd_range_is(sti, from, to, nl) {
            code = 10;
        }
        let sp: Value = self.string("space");
        if self.rd_range_is(sti, from, to, sp) {
            code = 32;
        }
        let tb: Value = self.string("tab");
        if self.rd_range_is(sti, from, to, tb) {
            code = 9;
        }
        let rn: Value = self.string("return");
        if self.rd_range_is(sti, from, to, rn) {
            code = 13;
        }
        let ff: Value = self.string("formfeed");
        if self.rd_range_is(sti, from, to, ff) {
            code = 12;
        }
        let bs: Value = self.string("backspace");
        if self.rd_range_is(sti, from, to, bs) {
            code = 8;
        }
        if code == 0 {
            return false;
        }
        let sk: u32 = self.sink_open();
        self.sink_put(sk, code);
        let out: Value = self.sink_string(sk);
        self.sink_close(sk);
        self.push(out);
        return true;
    }
    /// A character literal, at its backslash, pushed as a one-character string.
    pub fn read_char_lit(&mut self, sti: usize) -> u32 {
        self.rd_next(sti);
        let from: u32 = self.rd_pos(sti);
        let c: u32 = self.rd_next(sti);
        if c == NO_CP {
            return self.rd_fail_lit(sti, "unterminated character");
        }
        if !(is_ws(c) || is_term(c)) {
            self.rd_token(sti);
        }
        let to: u32 = self.rd_pos(sti);
        if (to - from) == 1 {
            let one: Value = self.rd_string(sti, from, to);
            self.push(one);
            return RS_OK;
        }
        if self.named_char(sti, from, to) {
            return RS_OK;
        }
        if c == 117 {
            let sk: u32 = self.sink_open();
            let st: u32 = self.put_code(sti, sk, from + 1, to, 16);
            if st != RS_OK {
                self.sink_close(sk);
                return st;
            }
            let out: Value = self.sink_string(sk);
            self.sink_close(sk);
            self.push(out);
            return RS_OK;
        }
        if c == 111 {
            let ok: u32 = self.sink_open();
            let ost: u32 = self.put_code(sti, ok, from + 1, to, 8);
            if ost != RS_OK {
                self.sink_close(ok);
                return ost;
            }
            let oout: Value = self.sink_string(ok);
            self.sink_close(ok);
            self.push(oout);
            return RS_OK;
        }
        let ek: u32 = self.sink_open();
        self.msg_lit(ek, "unknown character literal \\");
        let mut i: u32;
        i = from;
        while i < to {
            self.msg_cp(ek, self.rd_at(sti, i));
            i += 1;
        }
        return self.rd_fail_sink(sti, ek);
    }
    /// A regex literal, at its opening quote (the `#` already taken), pushed
    /// as `{:flint/regex "..."}` -- an ARRAY MAP built by call, because a
    /// map literal here would be one the analyzer rewrites. A backslash and
    /// whatever follows it are kept as written.
    pub fn read_regex_lit(&mut self, sti: usize) -> u32 {
        self.rd_next(sti);
        let sk: u32 = self.sink_open();
        loop {
            let c: u32 = self.rd_next(sti);
            if c == NO_CP {
                self.sink_close(sk);
                return self.rd_fail_lit(sti, "unterminated regex");
            }
            if c == 34 {
                break;
            }
            self.sink_put_cp(sk, c);
            if c == 92 {
                let d: u32 = self.rd_next(sti);
                if d != NO_CP {
                    self.sink_put_cp(sk, d);
                }
            }
        }
        let text: Value = self.sink_string(sk);
        self.sink_close(sk);
        let base: usize = self.mark();
        let ti: usize = self.push(text);
        let k: Value = self.lit_keyword("flint", "regex");
        // The key and the value, rooted IN ORDER, are the vector's
        // elements: `(base + 1, 2)`.
        self.push(k);
        self.push(self.r(ti));
        let kv: Value = self.vec_from_roots(base + 1, 2);
        let m: Value = self.ordered_map(kv);
        self.pop_to(base);
        self.push(m);
        return RS_OK;
    }
}
