// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropefind

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::ropecp::*;
use crate::kgen::rt::ropeflat::*;
use crate::kgen::rt::ropemeas::*;

impl Rt {
    /// Do the `nn` bytes of `nd` sit at (`leaf0`, `p0`) and onward?
    /// 
    /// A DUPLICATE CURSOR, which is what `walk-dup` exists for -- `tree-eq`
    /// uses it to peek the other side. The match may run off the end of the
    /// current leaf and into the next ones, and the outer walk must not move
    /// while it does, because a failed match resumes at the very next byte.
    /// 
    /// CHARGED PER BYTE COMPARED. The outer loop's `charge-tick` is what STOPS
    /// a scan that cannot be paid for; this bills the work the match itself
    /// does, which is bounded by the needle and would otherwise be the same
    /// kind of hole a collision scan was.
    pub(crate) fn match_at(&mut self, wh: u32, leaf0: Value, p0: u32, nd: Value, nn: u32) -> bool {
        // THE WHOLE NEEDLE INSIDE ONE LEAF, WITH NO CURSOR AT ALL, which is
        // almost every candidate and was the cost of the whole search.
        // `walk-dup` CLONES the cursor's stack, so taking one per candidate
        // allocated once per position where the first byte matched --
        // searching 34 KB for a needle starting with `p`, in a haystack of
        // `piece0-piece1-...`, is four thousand clones to answer four
        // thousand comparisons that never leave the leaf they started in.
        // 
        // So the boundary-crossing cursor below is now the RARE path, taken
        // only when the match would actually run off the end of this leaf.
        if (p0 + nn) <= self.leaf_len(leaf0) {
            let mut k: u32;
            let mut hit: bool;
            k = 0;
            hit = true;
            // A MEMCMP WHEN BOTH SIDES HAVE AN ADDRESS, which is what
            // `run-eq` is for and what `tree-eq` already does one file
            // along. The byte loop below was ~14 `leaf-byte` calls per
            // candidate -- searching 34 KB of `piece0-piece1-...` for a
            // needle starting with `p` means four thousand candidates, so
            // fifty-six thousand calls through the tier branch, and that
            // was the search.
            // 
            // AN INLINE LEAF HAS NO ADDRESS, so a pair with one on either
            // side still goes a byte at a time -- at most seven bytes, and
            // rare.
            if leaf0.is_heap() && nd.is_heap() {
                self.charge_work((nn as i64) as u64);
                return self.run_eq((leaf0.as_heap() + crate::obj::STR_DATA) + (p0 as Addr), nd.as_heap() + crate::obj::STR_DATA, nn);
            }
            while k < nn {
                // CHARGED PER BYTE COMPARED, exactly as the cursor path
                // below does. Billing `nn` flat would be simpler and would
                // over-charge every early mismatch, which is safe for a
                // budget and untrue about the work -- and `resource-limits` asks for
                // the second thing.
                self.charge_work(1 as u64);
                if self.leaf_byte(leaf0, p0 + k) != self.leaf_byte(nd, k) {
                    hit = false;
                    k = nn;
                } else {
                    k += 1;
                }
            }
            return hit;
        }
        let wd: u32 = self.walk_dup(wh);
        let mut ml: Value;
        let mut q: u32;
        let mut m: u32;
        let mut j: u32;
        let mut ok: bool;
        ml = leaf0;
        q = p0;
        m = self.leaf_len(leaf0);
        j = 0;
        ok = true;
        loop {
            if j == nn {
                break;
            }
            if q == m {
                let v: Value = self.walk_next(wd);
                if v.is_nil() {
                    ok = false;
                    break;
                }
                ml = v;
                q = 0;
                m = self.leaf_len(v);
                continue;
            }
            self.charge_work(1 as u64);
            if self.leaf_byte(ml, q) != self.leaf_byte(nd, j) {
                ok = false;
                break;
            }
            q += 1;
            j += 1;
        }
        self.walk_close(wd);
        return ok;
    }
    /// The CODE-POINT index of `needle` in `hay` at or after code point
    /// `from`, as a fixnum, or NIL when it is not there.
    /// 
    /// A VALUE RATHER THAN AN INT, because `I32` is UNSIGNED on all three
    /// targets: there is no -1 to return, and the first version of this tried
    /// to. A fixnum-or-nil is also exactly what the three builtins want to hand
    /// back, so the conversion disappears rather than moving.
    /// 
    /// `from` IS CLAMPED BY THE CALLER for the same reason -- a negative
    /// `from` arrives here as a very large number, so the builtins do the
    /// `max(from, 0)` where the sign still exists.
    /// 
    /// NOTHING ALLOCATES ONCE THE WALK IS OPEN. The needle is flattened first,
    /// before `walk-open`, so every read after that is a byte out of a leaf
    /// that cannot move -- which is why no leaf here is rooted (`a-vec-of-values-is-not-a-root`).
    pub fn s_index_of(&mut self, hay: Value, needle: Value, from: u32) -> Value {
        // A LOCAL AND A `set`, because kin's `if` is a statement: it cannot
        // sit in a `let` binding, which is what the first version tried.
        let mut nd: Value;
        let mut at: u32;
        nd = needle;
        if self.is_rope(needle) {
            nd = self.s_flatten(needle);
        }
        let skip: u32 = from;
        let nn: u32 = self.leaf_len(nd);
        // AN EMPTY NEEDLE IS FOUND WHERE THE SEARCH STARTS, CLAMPED TO
        // THE END -- `(str/index-of "abc" "" 100)` is 3 in Clojure, not
        // nil, because Java's `indexOf` answers the length when the needle
        // is empty and `from` is past it.
        // 
        // THE THREE RUNTIMES DISAGREED HERE and nothing caught it. Native's
        // ASCII path returned NIL, native's non-ASCII path returned the
        // count, and both ports returned the count -- so the answer
        // depended on whether the haystack happened to be ASCII, and
        // native contradicted its own ports for the ASCII half. Found by
        // differencing 1 560 cases against the old implementations; the
        // conformance probes had never asked.
        if nn == 0 {
            at = skip;
            if at > self.s_count(hay) {
                at = self.s_count(hay);
            }
            return Value::fixnum((at as i64) as i64);
        }
        // SEEK TO `from` BY DESCENT, NOT BY SCANNING, which is what made
        // `str/split` quadratic the moment this stopped flattening. Each
        // successive `index-of` starts further in, and a walk that opens
        // at the root and scans forward re-reads the whole prefix every
        // time: `test/scaling.clj` measured 3.56x for a doubled input
        // where linear is 2x, and caught it.
        // 
        // `rope-byte-of-cp` answers the byte offset in O(depth) using the
        // per-node code-point counts `strings-and-matching` created for this and which,
        // as `ropecp` notes, nothing used because every path flattened
        // first. Leaves entirely before that offset are then skipped by
        // LENGTH -- one `leaf-len` each, no bytes read.
        let wh: u32 = self.walk_open(hay);
        let ascii: bool = self.s_ascii(hay);
        let startbyte: u32 = self.rope_byte_of_cp(hay, skip);
        let mut base: u32;
        base = 0;
        let mut leaf: Value;
        let mut p: u32;
        let mut n: u32;
        let mut cp: u32;
        let mut out: Value;
        let mut ticks: u32;
        leaf = NIL;
        p = 0;
        n = 0;
        cp = 0;
        out = NIL;
        ticks = 0;
        loop {
            if p == n {
                let v: Value = self.walk_next(wh);
                if v.is_nil() {
                    break;
                }
                base += n;
                leaf = v;
                p = 0;
                n = self.leaf_len(v);
                // WHOLLY BEFORE THE START: skipped by length, without
                // reading a byte of it.
                if (base + n) <= startbyte {
                    p = n;
                    continue;
                }
                // THE LEAF THAT CONTAINS IT: jump in, and the code-point
                // index is `skip` by construction -- that is what
                // `rope-byte-of-cp` was asked.
                // 
                // `<=` AND NOT `<`. A leaf that begins exactly AT the
                // seek offset needs no jump but does need `cp` set, and
                // with `<` it did not get one -- the walk resumed
                // believing it was at code point zero, and `from=1` on
                // `abcabc` answered 2 instead of 3. Later leaves have
                // `base > startbyte`, so this fires once.
                if base <= startbyte {
                    p = startbyte - base;
                    cp = skip;
                }
                continue;
            }
            // BOUNDED HERE. A haystack is as long as the data says, so the
            // check has to be inside the walk rather than a pre-charge
            // against a length that is known but arbitrary.
            // THE TICK CHECKS AND DOES NOT CHARGE -- `charge-work` below
            // bills the bytes. Ticking once per LEAF and charging there
            // made the same bytes cost different gas in different shapes:
            // a three-leaf rope ticked three times where a flat string
            // ticked once, and the probe printed `gas=4,5` for what had
            // been `6,6`. The BYTES are what the work is, and they do not
            // depend on how the tree was built.
            if !self.charge_tick((ticks as i64) as u64, 0 as u64, "str-index-of") {
                break;
            }
            ticks += 1;
            // THE SKIP. Every byte between here and the next occurrence of
            // the needle's first byte can start no match, but each one
            // still has to be COUNTED if it is a code-point start. So the
            // run is found in one call and then counted, rather than
            // tested one byte at a time -- which is the difference between
            // a memchr and a call per byte, and was six times the runtime
            // of the flatten this replaced.
            let hit: u32 = self.leaf_find(leaf, self.leaf_byte(nd, 0), p);
            self.charge_work(((hit - p) as i64) as u64);
            // ASCII SKIPS THE COUNTING TOO, and this is most of the
            // cost. `leaf-find` jumps over a run in one call, and then
            // the run still had to be walked BYTE BY BYTE to count code
            // points -- 34 KB of flat ASCII took 142us, 4.2ns a byte,
            // for a scan that should be a memchr. When every byte is a
            // code point the count IS the distance, and the header
            // already knows (`s-ascii`, set once when the string was
            // built).
            if ascii {
                cp += hit - p;
                p = hit;
            } else {
                while p < hit {
                    if (self.leaf_byte(leaf, p) & 192) != 128 {
                        cp += 1;
                    }
                    p += 1;
                }
            }
            if p < n {
                self.charge_work(1 as u64);
                // A CONTINUATION BYTE IS 10xxxxxx and starts nothing, so
                // it advances the byte position and not the code-point
                // index. This is the whole of the multi-byte handling.
                if (self.leaf_byte(leaf, p) & 192) != 128 {
                    if cp >= skip {
                        if self.match_at(wh, leaf, p, nd, nn) {
                            out = Value::fixnum((cp as i64) as i64);
                            break;
                        }
                    }
                    cp += 1;
                }
                p += 1;
            }
        }
        self.walk_close(wh);
        return out;
    }
}
