// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropenode

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::hash::*;
use crate::kgen::rt::hashtext::*;
use crate::kgen::rt::pike::*;
use crate::kgen::rt::casetable::*;
use crate::kgen::rt::hamt::*;

impl Rt {
    /// A node over the `n` values already rooted at `base`.
    /// 
    /// THE CALLER PUSHES AND THE CALLER POPS. This roots nothing of its own, so
    /// the kids stay live across the allocation because the caller's mark holds
    /// them -- not because this pushed them a second time.
    /// 
    /// `RP_CPS` packs two answers into one slot: the code-point count shifted up
    /// by one, and the all-ASCII bit at the bottom. A node is ASCII only when
    /// every child is, which is why the fold is an `and` rather than a sum.
    pub fn rope_node(&mut self, base: usize, n: u32) -> Value {
        let mut bytes: u32;
        let mut cps: u32;
        let mut ascii: bool;
        bytes = 0;
        cps = 0;
        ascii = true;
        for i in 0..n {
            let k: Value = self.r(base + i as usize);
            bytes += self.s_bytes(k);
            cps += self.s_count(k);
            ascii = ascii && self.s_ascii(k);
        }
        let a: Addr = self.alloc(TY_ROPE, crate::obj::RP_KIDS + n);
        if a == 0 {
            return NIL;
        }
        self.set_slot(a, crate::obj::RP_BYTES, Value::fixnum(bytes as i64));
        self.set_slot(a, crate::obj::RP_CPS, Value::fixnum(((cps << 1) | (ascii as u32)) as i64));
        // NIL, not absent: both are computed on demand -- `RP_FLAT` the
        // cached flattening, `RP_HASH` the cached content hash.
        self.set_slot(a, crate::obj::RP_FLAT, NIL);
        self.set_slot(a, crate::obj::RP_HASH, NIL);
        for i in 0..n {
            self.set_slot(a, crate::obj::RP_KIDS + i, self.r(base + i as usize));
        }
        return Value::heap(a);
    }
    /// `v`, wrapped in single-child nodes until it stands `h` levels up.
    /// 
    /// A leaf beside a full subtree would make the tree RAGGED, and a ragged
    /// tree is how the depth grew linearly here before: the root filled with
    /// leaves, then the whole thing became child zero of a new root, every
    /// `FANOUT` appends.
    /// 
    /// The cursor lives in the ROOT. Rust used to carry it in a host local --
    /// correct, because the local was always overwritten by the result of the
    /// call that could have moved it, but correct by an argument the reader has
    /// to rebuild each time. Both ports already did it this way.
    pub fn rope_lift(&mut self, v: Value, h: u32) -> Value {
        let base: usize = self.mark();
        let ci: usize = self.push(v);
        for i in 0..h {
            let w: Value = self.rope_node(ci, 1);
            if w.is_nil() {
                self.pop_to(base);
                return NIL;
            }
            self.set_r(ci, w);
        }
        let out: Value = self.r(ci);
        self.pop_to(base);
        return out;
    }
    /// A balanced tree over the `n` values rooted at `base`.
    /// 
    /// Bottom-up in `FANOUT` groups, so the result is balanced BY CONSTRUCTION
    /// rather than by rebalancing afterwards -- which matters because the depth
    /// is what every index pays.
    pub fn rope_from_roots(&mut self, base: usize, n: u32) -> Value {
        // Nothing collected is the EMPTY STRING, so a caller that folded
        // zero pieces gets a string rather than nil and does not have to
        // test. It is interned rather than allocated, which is the one way
        // this differs from the byte fold.
        if n == 0 {
            return self.s_empty();
        }
        if n == 1 {
            return self.r(base);
        }
        let mut level: u32;
        let mut from: usize;
        level = n;
        from = base;
        loop {
            if level == 1 {
                return self.r(from);
            }
            let out: usize = self.mark();
            let mut made: u32;
            let mut i: u32;
            made = 0;
            i = 0;
            while i < level {
                let mut take: u32;
                take = crate::rope::FANOUT;
                if (level - i) < take {
                    take = level - i;
                }
                let node: Value = self.rope_node(from + i as usize, take);
                if node.is_nil() {
                    return NIL;
                }
                self.push(node);
                made += 1;
                i += take;
            }
            from = out;
            level = made;
        }
    }
}
