// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropemeas

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::hash::*;
use crate::kgen::rt::hashtext::*;
use crate::kgen::rt::pike::*;
use crate::kgen::rt::casetable::*;
use crate::kgen::rt::hamt::*;

impl Rt {
    /// Is `v` the NODE tier -- a tree rather than a leaf or an inline string?
    pub fn is_rope(&self, v: Value) -> bool {
        if !v.is_heap() {
            return false;
        }
        return ty(&self.gc.sp, v.as_heap()) == TY_ROPE;
    }
    /// Is `v` a STRING -- any of the three tiers?
    /// 
    /// Inline first, because it is a test on the value word and the other two
    /// need a tag read. Then the two heap tags: a flat string and a ROPE are
    /// both strings, and every caller that forgot the second one was a bug
    /// waiting for a string long enough to become a rope.
    /// 
    /// This is what `type-p` asks for code 4, and it was written three times
    /// until it was written here.
    pub fn is_string(&self, v: Value) -> bool {
        if v.is_inline_str() {
            return true;
        }
        if !v.is_heap() {
            return false;
        }
        let t: u8 = ty(&self.gc.sp, v.as_heap());
        return (t == TY_STR) || (t == TY_ROPE);
    }
    /// How many BYTES the string holds. O(1) on all three tiers.
    pub fn s_bytes(&self, v: Value) -> u32 {
        if v.is_inline_str() {
            return self.leaf_len(v);
        }
        if self.is_rope(v) {
            return self.slot(v, crate::obj::RP_BYTES).as_fixnum() as u32;
        }
        return self.leaf_len(v);
    }
    /// Is every byte below 0x80? All three tiers, O(1).
    /// 
    /// A ROPE READS BIT 0 of `RP_CPS`, where the count sits above it. A flat
    /// string reads the header bit the allocator set. Only an inline string is
    /// scanned, and it is at most seven bytes.
    pub fn s_ascii(&self, v: Value) -> bool {
        if v.is_inline_str() {
            let n: u32 = self.leaf_len(v);
            for i in 0..n {
                if self.leaf_byte(v, i) >= 128 {
                    return false;
                }
            }
            return true;
        }
        if self.is_rope(v) {
            return ((self.slot(v, crate::obj::RP_CPS).as_fixnum() as u32) & 1) != 0;
        }
        return crate::obj::str_is_ascii(&self.gc.sp, v.as_heap());
    }
    /// How many CODE POINTS the string holds.
    /// 
    /// O(1) for a rope and for an ASCII leaf; a scan bounded by the leaf
    /// otherwise. COUNTING NON-CONTINUATION BYTES rather than decoding: a
    /// continuation byte is exactly `10xxxxxx`, so every other byte starts a
    /// code point and nothing has to be assembled to be counted.
    pub fn s_count(&self, v: Value) -> u32 {
        if self.is_rope(v) {
            return (self.slot(v, crate::obj::RP_CPS).as_fixnum() as u32) >> 1;
        }
        let n: u32 = self.leaf_len(v);
        if self.s_ascii(v) {
            return n;
        }
        let mut c: u32;
        c = 0;
        for i in 0..n {
            if (self.leaf_byte(v, i) & 192) != 128 {
                c += 1;
            }
        }
        return c;
    }
}
