// Generated by kin from the source named below. Do not edit.
// source: flint.rt.tablerow

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::numkind::*;
use crate::kgen::rt::seqwalk::*;
use crate::kgen::rt::tablebuild::*;
use crate::kgen::rt::tablecell::*;
use crate::kgen::rt::tablefill::*;
use crate::kgen::rt::tablekind::*;
use crate::kgen::rt::tablemeta::*;
use crate::kgen::rt::tablesay::*;
use crate::kgen::rt::vecassoc::*;
use crate::kgen::rt::vecread::*;
use crate::kgen::rt::vecwrite::*;

impl Rt {
    /// `(assoc table i row)`. `i` may be `count`, which appends.
    pub fn table_assoc(&mut self, t: Value, k: Value, row: Value) -> Value {
        if !self.is_int(k) {
            // NOT A ROW NUMBER AT ALL. The message says what the key WAS and
            // what to write instead, because reaching for a column by name is
            // the mistake this refusal is almost always catching.
            let kind: Value = self.kind_of(k);
            let kn: alloc::string::String = self.kw_name(kind);
            return self.throw_str("IllegalArgumentException", &alloc::format!("{}{}{}", "a table is indexed by row number and this key is a ", kn, "; to reach a column, index the row first: (assoc-in t [row :column] v)"));
        }
        let i: i64 = self.i64_of(k);
        let n: i64 = self.table_count(t) as i64;
        // `i < 0` IS A LIVE TEST HERE and not the dead one the `I32` trap
        // makes of it: `i` is an `I64`, signed in all three runtimes, and
        // a program may genuinely hand over -1.
        if (i < 0) || (i > n) {
            return self.throw_str("IndexOutOfBoundsException", &alloc::format!("{}{}{}{}{}{}", "row ", i, " is out of range for a table of ", n, " rows; assoc may replace any row or append at ", n));
        }
        let base: usize = self.mark();
        let ti: usize = self.push(t);
        let ri: usize = self.push(row);
        let sch: Value = self.slot(self.r(ti), crate::table::TB_SCHEMA);
        let si: usize = self.push(sch);
        if !self.check_row(self.r(si), self.r(ri), i as u32) {
            self.pop_to(base);
            return NIL;
        }
        let idx: u32 = i as u32;
        let chunks: Value = self.slot(self.r(ti), crate::table::TB_CHUNKS);
        let ci: usize = self.push(chunks);
        let phys: u32 = idx + self.table_offset(self.r(ti));
        let which: u32 = phys >> crate::table::CHUNK_SHIFT;
        let within: u32 = phys & (crate::table::CHUNK - 1);
        let append: bool = idx == self.table_count(self.r(ti));
        let nchunks: u32 = self.vec_count(self.r(ci));
        if append && (which >= nchunks) {
            // A NEW CHUNK, one row wide. `chunk-with-row` grows an
            // existing one; an empty table has none to grow.
            let w: u32 = self.schema_width(self.r(si));
            let ch: Value = self.new_chunk(w, 1);
            let chi: usize = self.push(ch);
            let ncols: u32 = self.schema_len(self.r(si));
            for c in 0..ncols {
                let id: u32 = self.schema_id_at(self.r(si), c);
                let col: Value = self.new_obj(TY_NODE, 1);
                self.set(self.r(chi), crate::table::CH_BASE + id, col);
            }
            self.write_row(self.r(si), self.r(chi), 0, self.r(ri));
            // A ONE-ROW COLUMN IS TRIVIALLY CONSTANT, so a table grown
            // row by row starts every chunk collapsed and expands only
            // where the rows actually differ. Skipping this would make
            // the append path the one path that never encodes.
            for c in 0..ncols {
                let id: u32 = self.schema_id_at(self.r(si), c);
                self.collapse(self.r(chi), id);
            }
            let nv: Value = self.vec_conj(self.r(ci), self.r(chi));
            self.set_r(ci, nv);
            self.pop_to(chi);
        } else {
            let ch: Value = self.vec_nth(self.r(ci), which, NIL);
            let chi: usize = self.push(ch);
            let nch: Value = self.chunk_with_row(self.r(si), self.r(chi), within, self.r(ri), append);
            let nj: usize = self.push(nch);
            let nv: Value = self.vec_assoc(self.r(ci), which, self.r(nj));
            self.set_r(ci, nv);
            self.pop_to(chi);
        }
        let mut count: u32;
        count = self.table_count(self.r(ti));
        if append {
            count += 1;
        }
        let nt: Value = Value::heap(self.alloc(TY_TABLE, crate::table::TB_LEN));
        let ni: usize = self.push(nt);
        self.set(self.r(ni), crate::table::TB_SCHEMA, self.r(si));
        self.set(self.r(ni), crate::table::TB_CHUNKS, self.r(ci));
        self.set(self.r(ni), crate::table::TB_COUNT, Value::fixnum(count as i64));
        self.set(self.r(ni), crate::table::TB_OFFSET, self.slot(self.r(ti), crate::table::TB_OFFSET));
        let out: Value = self.r(ni);
        self.pop_to(base);
        return out;
    }
    /// `(conj table row)` -- appending is `assoc` at `count`.
    pub fn table_conj(&mut self, t: Value, row: Value) -> Value {
        let n: u32 = self.table_count(t);
        return self.table_assoc(t, Value::fixnum(n as i64), row);
    }
    /// Rows `[from, to)` as a table of their own.
    /// 
    /// A SLICE SHARES ITS CHUNKS. Only the ones the range touches are carried,
    /// and the offset within the first of them is where the slice begins -- so
    /// slicing costs a head, not a copy, and `table-ref` is the single place
    /// that has to know about it.
    /// 
    /// `from` AND `to` ARE `I64`s for the same reason `assoc`'s index is: a
    /// program supplies them, and a negative one is a thing to refuse rather
    /// than a thing that cannot be represented.
    pub fn table_slice(&mut self, t: Value, from: i64, to: i64) -> Value {
        let n: i64 = self.table_count(t) as i64;
        if (from < 0) || ((to > n) || (from > to)) {
            return self.throw_str("IndexOutOfBoundsException", &alloc::format!("{}{}{}{}{}{}{}", "slice [", from, " ", to, ") is outside a table of ", n, " rows"));
        }
        let base: usize = self.mark();
        let ti: usize = self.push(t);
        if from == to {
            // AN EMPTY SLICE IS A FRESH EMPTY TABLE, not a window of no
            // rows onto the old chunks: keeping them would hold a whole
            // table alive to say nothing.
            let sch0: Value = self.slot(self.r(ti), crate::table::TB_SCHEMA);
            let ei: usize = self.push(sch0);
            let none: Value = self.empty_vec();
            let fresh: Value = self.new_table(self.r(ei), none);
            // `fresh`, `ei` and `sch0` rather than `out`, `si` and
            // `sch`: C# refuses a local whose name is used in an
            // enclosing scope, even from a SIBLING branch, and the main
            // path below binds all three. One name per function is the
            // portable rule.
            self.pop_to(base);
            return fresh;
        }
        let off: u32 = self.table_offset(self.r(ti));
        let lo: u32 = from as u32;
        let hi: u32 = to as u32;
        let first: u32 = (off + lo) >> crate::table::CHUNK_SHIFT;
        let last: u32 = ((off + hi) - 1) >> crate::table::CHUNK_SHIFT;
        let ci: usize = self.push(self.slot(self.r(ti), crate::table::TB_CHUNKS));
        let kept0: Value = self.empty_vec();
        let ki: usize = self.push(kept0);
        for k in first..last + 1 {
            let ch: Value = self.vec_nth(self.r(ci), k, NIL);
            let nv: Value = self.vec_conj(self.r(ki), ch);
            self.set_r(ki, nv);
        }
        let sch: Value = self.slot(self.r(ti), crate::table::TB_SCHEMA);
        let si: usize = self.push(sch);
        let nt: Value = Value::heap(self.alloc(TY_TABLE, crate::table::TB_LEN));
        let ni: usize = self.push(nt);
        self.set(self.r(ni), crate::table::TB_SCHEMA, self.r(si));
        self.set(self.r(ni), crate::table::TB_CHUNKS, self.r(ki));
        self.set(self.r(ni), crate::table::TB_COUNT, Value::fixnum(((to - from) as u32) as i64));
        self.set(self.r(ni), crate::table::TB_OFFSET, Value::fixnum(((off + lo) & (crate::table::CHUNK - 1)) as i64));
        let out: Value = self.r(ni);
        self.pop_to(base);
        return out;
    }
}
