// Generated by kin from the source named below. Do not edit.
// source: flint.rt.vectrans

#![allow(unused_imports)]
use crate::gc::InternTable;
use crate::hash;
use crate::eq::*;
use crate::map::*;
use crate::mem::Addr;
use crate::mem::Space;
use crate::gc::Gc;
use crate::obj::*;
use crate::rt::Rt;
use crate::seqs::*;
use crate::strs::INTERN_MAX;
use crate::vector::*;
use crate::value::{Value, FALSE, NIL, NOT_FOUND, TRUE};
use crate::kgen::rt::vecnode::*;
use crate::kgen::rt::vecread::*;

impl Rt {
    /// A fresh ownership token: an object whose IDENTITY is the whole of it.
    /// 
    /// `TY_VOLATILE` with one slot, and the slot is never read. What matters is
    /// that no two transients can be handed the same address, which is what
    /// makes `node-edit node == edit` a safe test for `this is mine`.
    pub fn new_edit_token(&mut self) -> Value {
        let a: Addr = self.alloc(TY_VOLATILE, 1);
        if a == 0 {
            return NIL;
        }
        return Value::heap(a);
    }
    pub fn is_transient_vector(&self, v: Value) -> bool {
        if !v.is_heap() {
            return false;
        }
        return ty(&self.gc.sp, v.as_heap()) == TY_TVEC;
    }
    /// THE FOUR READERS BELOW ARE THE VECTOR'S, AND THAT IS DELIBERATE.
    /// 
    /// A TRANSIENT'S HEADER IS A VECTOR'S HEADER, PREFIX-WISE. A `TY_VEC` is
    /// `cnt, shift, root, tail, meta, hash` and a `TY_TVEC` is
    /// `cnt, shift, root, tail, edit`.
    /// 
    /// NOT WRITTEN AS AN INDENTED BLOCK, which is what it was first. Four
    /// leading spaces in a Rust doc comment is a CODE FENCE, so rustdoc tried
    /// to compile the layout diagram as Rust and `cargo test` failed on a
    /// doctest nobody wrote. Kin doc strings become `///` on one target and
    /// `/// <summary>` on the others, so an indented line is a different thing
    /// in each.
    /// 
    /// `T_CNT`, `T_SHIFT`, `T_ROOT` and `T_TAIL` are 0, 1, 2 and 3 -- the same
    /// numbers as `V_CNT`, `V_SHIFT`, `V_ROOT` and `V_TAIL`. The layouts part
    /// company only at slot 4, where a vector keeps its metadata and a
    /// transient its edit token, and no reader below looks that far.
    /// 
    /// SO THE BODIES WERE IDENTICAL, four of them, differing only in whether
    /// the parameter was called `v` or `t` -- `tvec-shift` was a byte-for-byte
    /// copy of `vec-shift` in a file that ALREADY IMPORTED `vec-shift` and used
    /// it eleven lines further down. The names stay, because `(tvec-count rt t)`
    /// says what `(vec-count rt t)` would only imply, and `^:inline` means
    /// saying it costs nothing.
    /// 
    /// THE PREFIX IS NOW LOAD-BEARING, and it was not written down anywhere
    /// before this comment. `runtime/src/vector.rs` asserts it at COMPILE TIME
    /// rather than trusting the reader: put `T_EDIT` in front of `T_TAIL` one
    /// day and the build stops, instead of four readers quietly returning the
    /// wrong slot.
    #[inline]
    pub fn tvec_count(&self, t: Value) -> u32 {
        return self.vec_count(t);
    }
    #[inline]
    pub fn tvec_shift(&self, t: Value) -> u32 {
        return self.vec_shift(t);
    }
    /// Where the transient's tail starts, on the same rule as a vector's --
    /// which is now the same CODE as a vector's.
    #[inline]
    pub fn tvec_tail_off(&self, t: Value) -> u32 {
        return self.tail_off(t);
    }
    /// Is this transient still usable? `persistent!` clears the token, and a
    /// transient without one has been handed over and must not be written.
    #[inline]
    pub fn tvec_alive(&self, t: Value) -> bool {
        return !self.slot(t, T_EDIT).is_nil();
    }
    /// `transient`: O(1), because nothing is copied until the first write that
    /// reaches a node this transient does not already own.
    /// 
    /// The TAIL is the exception and is widened to a full 32 here, so that
    /// `conj!` can write into it in place rather than copying it one longer on
    /// every append -- which is the copy transients exist to avoid.
    pub fn vec_transient(&mut self, v: Value) -> Value {
        let base: usize = self.mark();
        let vi: usize = self.push(v);
        let edit: Value = self.new_edit_token();
        let ei: usize = self.push(edit);
        let tail: Value = self.node_clone(self.slot(self.r(vi), V_TAIL), WIDTH, self.r(ei));
        let ti: usize = self.push(tail);
        let ri: usize = self.push(self.slot(self.r(vi), V_ROOT));
        let a: Addr = self.alloc(TY_TVEC, 5);
        if a == 0 {
            self.pop_to(base);
            return NIL;
        }
        let vv: Value = self.r(vi);
        let cnt: u32 = self.vec_count(vv);
        let shift: u32 = self.vec_shift(vv);
        self.set_slot(a, T_CNT, Value::fixnum(cnt as i64));
        self.set_slot(a, T_SHIFT, Value::fixnum(shift as i64));
        self.set_slot(a, T_ROOT, self.r(ri));
        self.set_slot(a, T_TAIL, self.r(ti));
        self.set_slot(a, T_EDIT, self.r(ei));
        self.pop_to(base);
        return Value::heap(a);
    }
    /// `node` if this transient already owns it, else an owned copy.
    /// 
    /// The one test the whole transient design rests on. A node whose token is
    /// this transient's was made by it and nobody else can see it, so writing
    /// in place is safe; any other node may be shared with a persistent vector
    /// and is copied ONCE, after which the copy is owned.
    pub fn ensure_editable(&mut self, node: Value, edit: Value) -> Value {
        if self.node_edit(node) == edit {
            return node;
        }
        return self.node_clone(node, WIDTH, edit);
    }
    /// The leaf holding index `i` of a transient -- the vector's descent, for
    /// the reason at the top of this file.
    pub fn t_array_for(&self, t: Value, i: u32) -> Value {
        return self.array_for(t, i);
    }
    /// Element `i` of a transient, or `dflt`. Same convergence as `vec-nth`.
    pub fn tvec_nth(&self, t: Value, i: u32, dflt: Value) -> Value {
        return self.vec_nth(t, i, dflt);
    }
}
