// Generated by kin from the source named below. Do not edit.
// source: flint.rt.atoms

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Nouns;
using static global::_3sln.Flint.Kgen.Rt.Seqwalk;

public static class Atoms {
    /// A fresh atom holding `v`.
    public static long NewAtom(Rt rt, long v) {
        int @base = rt.Mark();
        int vi = rt.Push(v);
        long a = Conc.NewObj(rt, Obj.TyAtom, 2);
        if (Val.IsNil(a)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        // READ BACK FROM THE ROOT: the allocation may have moved it (0031).
        rt.SetSlot(Val.AsHeap(a), 0, rt.R(vi));
        rt.SetSlot(Val.AsHeap(a), 1, Val.Nil);
        rt.PopTo(@base);
        return a;
    }
    /// Is `at` a box that can be reset -- an atom or a volatile?
    /// 
    /// A DELAY IS NOT. It has no set operation: the whole point is that it is
    /// computed once and then fixed, so `reset!` on one would be undoing the
    /// only guarantee it makes.
    internal static bool IsResettable(Rt rt, long at) {
        if (!Val.IsHeap(at)) {
            return false;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(at));
        return (t == Obj.TyAtom) || (t == Obj.TyVolatile);
    }
    /// Read the box.
    /// 
    /// A DELAY RUNS ITS THUNK ONCE. The thunk slot is cleared BEFORE the result
    /// is stored, so a delay that has run holds no reference to the code that
    /// produced it -- and the cleared slot is also how the next `deref` knows
    /// not to run it again.
    public static long Deref(Rt rt, long v) {
        if (Val.IsHeap(v)) {
            int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
            if ((t == Obj.TyAtom) || (t == Obj.TyVolatile)) {
                return rt.Slot(v, 0);
            }
            if (t == Obj.TyDelay) {
                long thunk = rt.Slot(v, 0);
                if (Val.IsNil(thunk)) {
                    return rt.Slot(v, 1);
                }
                int @base = rt.Mark();
                int vi = rt.Push(v);
                int ti = rt.Push(thunk);
                long res = rt.InvokeRoots(rt.R(ti), ti, 0);
                if (!Val.IsNil(rt.thrown)) {
                    rt.PopTo(@base);
                    return Val.Nil;
                }
                // THE DELAY IS RE-READ FROM ITS ROOT: running the
                // thunk may have collected, and the box could have
                // moved under a host local.
                rt.SetSlot(Val.AsHeap(rt.R(vi)), 0, Val.Nil);
                rt.SetSlot(Val.AsHeap(rt.R(vi)), 1, res);
                rt.PopTo(@base);
                return res;
            }
        }
        string what = Describe(rt, v);
        return rt.ThrowStr("ClassCastException", "cannot deref " + what);
    }
    /// Set the atom to `next` only if it still holds `expect`.
    /// 
    /// THE PRIMITIVE `swap!` IS BUILT FROM. `swap!` used to be `(reset! a (f
    /// (deref a)))` -- a read-modify-write with no atomicity, which loses
    /// updates the moment two threads are inside it at once, and loses them
    /// SILENTLY: the counter is simply smaller than it should be. That was
    /// invisible while one thread ran a sandbox and became reachable the day two
    /// could (`0028`).
    /// 
    /// COMPARES BY IDENTITY, as Clojure's does. A value-equal but distinct
    /// object means someone else has been here, and the retry is cheaper than a
    /// deep comparison on every attempt.
    public static long CompareAndSetAtom(Rt rt, long at, long expect, long next) {
        if (!IsResettable(rt, at)) {
            string what = Describe(rt, at);
            return rt.ThrowStr("ClassCastException", "not an atom: " + what);
        }
        if (rt.Slot(at, 0) == expect) {
            rt.SetSlot(Val.AsHeap(at), 0, next);
            return Val.True;
        }
        return Val.False;
    }
    /// Set the atom, and answer what was set.
    public static long ResetAtom(Rt rt, long at, long v) {
        if (!IsResettable(rt, at)) {
            string what = Describe(rt, at);
            return rt.ThrowStr("ClassCastException", "not an atom: " + what);
        }
        rt.SetSlot(Val.AsHeap(at), 0, v);
        return v;
    }
}
