// Generated by kin from the source named below. Do not edit.
// source: flint.rt.byteconcat

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Bytecore;
using static global::_3sln.Flint.Kgen.Rt.Byteflat;
using static global::_3sln.Flint.Kgen.Rt.Bytenode;

public static class Byteconcat {
    /// Merge `b` into `a`'s RIGHTMOST LEAF if the two fit in one leaf.
    /// 
    /// NIL when they do not, or when there is no leaf to merge with. The copy is
    /// bounded by `FLAT_MAX`, which is what makes doing it at all worth while.
    public static long BMergeRight(Rt rt, long a, long b) {
        if (!Val.IsHeap(a)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(a));
        if (t == Obj.TyBytes) {
            if ((Olen(rt, a) + BCount(rt, b)) <= global::Flint.Rt.Str.FLAT_MAX) {
                return BCopyConcat(rt, a, b);
            }
            return Val.Nil;
        }
        if (t != Obj.TyBrope) {
            return Val.Nil;
        }
        int n = Olen(rt, a) - global::Flint.Rt.Bytes.BB_KIDS;
        int @base = rt.Mark();
        rt.Push(a);
        rt.Push(b);
        long last = rt.Slot(rt.R(@base), global::Flint.Rt.Bytes.BB_KIDS + (n - 1));
        long merged = BMergeRight(rt, last, rt.R(@base + 1));
        if (Val.IsNil(merged)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        rt.Push(merged);
        // The kids the new node keeps: `a`'s first n-1, then the
        // merged tail. They go on the shadow stack because that is
        // what `b-node` takes now.
        int kbase = rt.Mark();
        for (int i = 0; i < n - 1; i++) {
            rt.Push(rt.Slot(rt.R(@base), global::Flint.Rt.Bytes.BB_KIDS + i));
        }
        rt.Push(rt.R(@base + 2));
        long @out = BNode(rt, kbase, n);
        rt.PopTo(@base);
        return @out;
    }
    /// Put `b` in the deepest node on `a`'s right spine that has room.
    /// 
    /// NIL if there is none. Depth is UNCHANGED when this succeeds, which is the
    /// whole point: a join that deepens the tree every time is the left spine
    /// this exists to avoid.
    public static long BAbsorb(Rt rt, long a, long b) {
        if (!Val.IsHeap(a)) {
            return Val.Nil;
        }
        if (Obj.Ty(rt.gc.sp, Val.AsHeap(a)) != Obj.TyBrope) {
            return Val.Nil;
        }
        int n = Olen(rt, a) - global::Flint.Rt.Bytes.BB_KIDS;
        int da = BDepth(rt, a);
        // A node's children are all the same depth, so anything as deep as
        // this node cannot go inside it.
        if (BDepth(rt, b) >= da) {
            return Val.Nil;
        }
        int @base = rt.Mark();
        rt.Push(a);
        rt.Push(b);
        // DEEPEST FIRST. Only if the last child cannot take it does this
        // node take it, and only if neither can does the caller wrap.
        long last = rt.Slot(rt.R(@base), global::Flint.Rt.Bytes.BB_KIDS + (n - 1));
        long down = BAbsorb(rt, last, rt.R(@base + 1));
        if (!Val.IsNil(down)) {
            rt.Push(down);
            int kbase = rt.Mark();
            for (int i = 0; i < n - 1; i++) {
                rt.Push(rt.Slot(rt.R(@base), global::Flint.Rt.Bytes.BB_KIDS + i));
            }
            rt.Push(rt.R(@base + 2));
            long @out = BNode(rt, kbase, n);
            rt.PopTo(@base);
            return @out;
        }
        if (n < global::Flint.Rt.Str.FANOUT) {
            // Promoted to this node's CHILD depth, so every child
            // stays the same depth and the next append can descend.
            long bb = BWrapTo(rt, rt.R(@base + 1), da - 1);
            // NIL means the heap is full. Pushing it would put a
            // non-value in the tree as a child; `b-wrap-to` used to
            // hang here instead of answering it at all.
            if (Val.IsNil(bb)) {
                rt.PopTo(@base);
                return Val.Nil;
            }
            rt.Push(bb);
            int kbase = rt.Mark();
            for (int i = 0; i < n; i++) {
                rt.Push(rt.Slot(rt.R(@base), global::Flint.Rt.Bytes.BB_KIDS + i));
            }
            rt.Push(rt.R(@base + 2));
            long @out = BNode(rt, kbase, n + 1);
            rt.PopTo(@base);
            return @out;
        }
        rt.PopTo(@base);
        return Val.Nil;
    }
    /// `a` followed by `b`, as a byte string.
    public static long BConcat(Rt rt, long a, long b) {
        if (BCount(rt, a) == 0) {
            return b;
        }
        if (BCount(rt, b) == 0) {
            return a;
        }
        // Below the threshold a tree costs more in metadata than the copy
        // saves. This is the tier that must NOT be skipped -- and it is also
        // the tier that makes incremental building quadratic, which is what
        // the transient is for.
        if ((BCount(rt, a) + BCount(rt, b)) <= global::Flint.Rt.Str.FLAT_MAX) {
            return BCopyConcat(rt, a, b);
        }
        if (BCount(rt, b) <= (global::Flint.Rt.Str.FLAT_MAX / 2)) {
            long merged = BMergeRight(rt, a, b);
            if (!Val.IsNil(merged)) {
                return merged;
            }
        }
        long absorbed = BAbsorb(rt, a, b);
        if (!Val.IsNil(absorbed)) {
            return absorbed;
        }
        // Neither side had room, so a NEW LEVEL. Both sides are promoted to
        // the same depth first: `b-node` reads the depth off child zero, so
        // pairing a deep node with a bare leaf makes the node claim a depth
        // one child does not have, and later appends descend into the wrong
        // place. That is the invariant the absorb above depends on.
        int @base = rt.Mark();
        rt.Push(a);
        rt.Push(b);
        int d = BDepth(rt, rt.R(@base));
        int dd;
        dd = d;
        if (dd < BDepth(rt, rt.R(@base + 1))) {
            dd = BDepth(rt, rt.R(@base + 1));
        }
        long pa = BWrapTo(rt, rt.R(@base), dd);
        if (Val.IsNil(pa)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        rt.Push(pa);
        long pb = BWrapTo(rt, rt.R(@base + 1), dd);
        if (Val.IsNil(pb)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        rt.Push(pb);
        long @out = BNode(rt, @base + 2, 2);
        rt.PopTo(@base);
        return @out;
    }
}
