// Generated by kin from the source named below. Do not edit.
// source: flint.rt.bytehash

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Bytecore;

public static class Bytehash {
    /// 31 to the power of `n`, wrapping.
    /// 
    /// `^:method` WITH THE RECEIVER UNUSED, and that is deliberate. Without it
    /// this is a function with no receiver, which Java and C# put beside its
    /// siblings in one class -- the bare name finds it -- while Rust puts it in
    /// an `impl` block where the bare name is not in scope. Whether `Self::` is
    /// right depends on whether the emitted unit opened an impl at all, which
    /// the call site cannot know: `hash.kin` has no receiver anywhere and emits
    /// at module level, where `Self::` does not compile. Taking the receiver
    /// and ignoring it costs one unused parameter in the ports and is the same
    /// in all three.
    /// 
    /// By SQUARING, not by looping `n` times: `n` is the byte length of a
    /// subtree, and looping over it would make combining two hashes cost what
    /// walking the bytes costs -- which is the walk the cached hash exists to
    /// avoid.
    public static int Pow31(Rt rt, int n) {
        int left;
        int @base;
        int acc;
        left = n;
        @base = 31;
        acc = 1;
        while (left > 0) {
            if ((left & 1) == 1) {
                acc = unchecked(acc * @base);
            }
            @base = unchecked(@base * @base);
            left = (int)((uint) left >> 1);
        }
        return acc;
    }
    /// The content hash of `v`, cached in every node it descends through.
    /// 
    /// A LEAF is hashed byte by byte. A node combines its children's hashes,
    /// which are themselves cached -- so the second ask of a big tree is a slot
    /// read, and the first is one pass over the bytes rather than one per node.
    /// 
    /// The cache is checked with `is-fixnum` rather than against nil, because
    /// zero is a legitimate hash and `NIL` is what an uncomputed slot holds.
    public static int BHash(Rt rt, long v) {
        if (!IsBrope(rt, v)) {
            // `lh` and not `h`: C# refuses a local whose name is used in an
            // enclosing scope, even from a sibling branch. One name per
            // function is the portable rule.
            int lh;
            lh = 0;
            if (Val.IsHeap(v)) {
                if (Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyBytes) {
                    int n = Olen(rt, v);
                    for (int i = 0; i < n; i++) {
                        lh = unchecked(unchecked(lh * 31) + rt.gc.sp.ReadU8((Val.AsHeap(v) + Obj.Hdr) + i));
                    }
                }
            }
            return lh;
        }
        long cached = rt.Slot(v, global::Flint.Rt.Bytes.BB_HASH);
        if (Val.IsFixnum(cached)) {
            return (int) Val.AsFixnum(cached);
        }
        // `v` LIVES IN THE ROOT: hashing a child recurses and writes a cache
        // slot, and nothing here allocates -- but the child hash below does
        // root its own, and a host local held across that is the habit this
        // port is trying not to have.
        int @base = rt.Mark();
        int vi = rt.Push(v);
        int kids = Olen(rt, rt.R(vi)) - global::Flint.Rt.Bytes.BB_KIDS;
        int h;
        h = 0;
        for (int i = 0; i < kids; i++) {
            long k = rt.Slot(rt.R(vi), global::Flint.Rt.Bytes.BB_KIDS + i);
            int ki = rt.Push(k);
            int kh = BHash(rt, rt.R(ki));
            int kb = BCount(rt, rt.R(ki));
            h = unchecked(unchecked(h * Pow31(rt, kb)) + kh);
            rt.PopTo(ki);
        }
        rt.SetSlot(Val.AsHeap(rt.R(vi)), global::Flint.Rt.Bytes.BB_HASH, Val.Fixnum(h & 0xFFFFFFFFL));
        rt.PopTo(@base);
        return h;
    }
}
