// Generated by kin from the source named below. Do not edit.
// source: flint.rt.bytecore

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Bytecore {
    /// Is `v` a byte string -- either tier?
    public static bool IsBytes(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        return (t == Obj.TyBytes) || (t == Obj.TyBrope);
    }
    /// How many bytes, whatever tier it is.
    /// 
    /// A LEAF DOES NOT STORE ITS COUNT: the object's own length is the count,
    /// which is what makes the flat tier free. A node stores one, because
    /// adding up its children's would be the walk the tier exists to avoid.
    public static int BCount(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return 0;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if (t == Obj.TyBytes) {
            return Olen(rt, v);
        }
        if (t == Obj.TyBrope) {
            return (int) Val.AsFixnum(rt.Slot(v, global::Flint.Rt.Bytes.BB_BYTES));
        }
        // Not a byte string at all. Zero rather than a refusal, because
        // every caller here is already asking `how long is this` about a
        // value it has not checked.
        return 0;
    }
    /// How deep the tree is; a leaf and a non-byte-string are both 0.
    public static int BDepth(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return 0;
        }
        if (Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyBrope) {
            return (int) Val.AsFixnum(rt.Slot(v, global::Flint.Rt.Bytes.BB_DEPTH));
        }
        return 0;
    }
    /// Is `v` the NODE tier specifically -- a tree rather than a leaf?
    public static bool IsBrope(Rt rt, long v) {
        return Val.IsHeap(v) && (Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyBrope);
    }
    /// Is `v` a transient byte string?
    public static bool IsTbytes(Rt rt, long v) {
        return Val.IsHeap(v) && (Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyTbytes);
    }
    /// Is `t` a transient that has NOT been made persistent yet?
    /// 
    /// A transient is invalidated by `persistent!` rather than freed, so the
    /// check is a slot and not a liveness question about memory.
    public static bool TbLive(Rt rt, long t) {
        return IsTbytes(rt, t) && (rt.Slot(t, global::Flint.Rt.Bytes.TB_LIVE) == Val.True);
    }
    /// How many bytes a transient holds: the sealed tree plus the open tail.
    public static int BTcount(Rt rt, long t) {
        if (!IsTbytes(rt, t)) {
            return 0;
        }
        return BCount(rt, rt.Slot(t, global::Flint.Rt.Bytes.TB_TREE)) + ((int) Val.AsFixnum(rt.Slot(t, global::Flint.Rt.Bytes.TB_FILL)));
    }
}
