// Generated by kin from the source named below. Do not edit.
// source: flint.rt.casechange

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Casemap;
using static global::_3sln.Flint.Kgen.Rt.Codepoints;
using static global::_3sln.Flint.Kgen.Rt.Ropemeas;

public static class Casechange {
    /// Write `cp` to `sk` as UTF-8, and answer how many bytes that took.
    /// 
    /// Four widths and no validation: every code point here came out of
    /// `code-points`, which decoded it from a string a constructor had already
    /// validated. A second opinion about what a string is would be the drift
    /// this whole file exists to remove.
    internal static int PutUtf8(Rt rt, int sk, int cp) {
        if (cp < 128) {
            rt.SinkPut(sk, cp);
            return 1;
        }
        if (cp < 2048) {
            rt.SinkPut(sk, 192 | ((int)((uint) cp >> 6)));
            rt.SinkPut(sk, 128 | (cp & 63));
            return 2;
        }
        if (cp < 65536) {
            rt.SinkPut(sk, 224 | ((int)((uint) cp >> 12)));
            rt.SinkPut(sk, 128 | (((int)((uint) cp >> 6)) & 63));
            rt.SinkPut(sk, 128 | (cp & 63));
            return 3;
        }
        rt.SinkPut(sk, 240 | ((int)((uint) cp >> 18)));
        rt.SinkPut(sk, 128 | (((int)((uint) cp >> 12)) & 63));
        rt.SinkPut(sk, 128 | (((int)((uint) cp >> 6)) & 63));
        rt.SinkPut(sk, 128 | (cp & 63));
        return 4;
    }
    /// `s` with every code point mapped to upper case, or to lower.
    /// 
    /// CHARGED BEFORE THE WORK and refused if it cannot be paid for. The length
    /// is known here, so this is a better bound than a per-iteration tick: it
    /// never begins work the budget cannot cover, and costs nothing inside the
    /// loop. `charge-bytes` alone billed 48 097 steps past an exhausted budget,
    /// because billing is not bounding.
    /// 
    /// EVERY TIER, and no ASCII shortcut. The Rust this replaces answered `nil`
    /// for a string with any byte over 127, which is not a terse answer but a
    /// wrong one.
    public static long ChangeCase(Rt rt, long s, bool up) {
        if (!IsString(rt, s)) {
            return rt.ThrowStr("ClassCastException", "not a string");
        }
        int c = CodePoints(rt, s);
        int n = rt.CpsLen(c);
        if (!rt.ChargeChecked(n + 1, "case conversion")) {
            rt.CpsClose(c);
            return Val.Nil;
        }
        int sk = rt.SinkOpen();
        int i;
        i = 0;
        for (;;) {
            if (i == n) {
                break;
            }
            // HOISTED, and not style: `put-utf8` takes the runtime
            // mutably while `cps-at` and `case-map` take it shared, so
            // nesting them in the argument list is two borrows at once --
            // the shape `0031` is about.
            int cp = rt.CpsAt(c, i);
            int fx = FullIndex(rt, cp, up);
            if (fx < 0) {
                int m = CaseMap(rt, cp, up);
                PutUtf8(rt, sk, m);
            } else {
                // A FULL mapping: one code point out to as many as
                // three, so the count comes from the table too.
                int k;
                k = 0;
                for (;;) {
                    if (k == rt.FullAt(up, fx, 1)) {
                        break;
                    }
                    int e = rt.FullAt(up, fx, k + 2);
                    PutUtf8(rt, sk, e);
                    k += 1;
                }
            }
            i += 1;
        }
        long @out = rt.SinkString(sk);
        rt.SinkClose(sk);
        rt.CpsClose(c);
        return @out;
    }
}
