// Generated by kin from the source named below. Do not edit.
// source: flint.rt.collgen

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Bytecore;
using static global::_3sln.Flint.Kgen.Rt.Mapcore;
using static global::_3sln.Flint.Kgen.Rt.Maptrans;
using static global::_3sln.Flint.Kgen.Rt.Nouns;
using static global::_3sln.Flint.Kgen.Rt.Seqcore;
using static global::_3sln.Flint.Kgen.Rt.Seqwalk;
using static global::_3sln.Flint.Kgen.Rt.Setcore;
using static global::_3sln.Flint.Kgen.Rt.Tablemeta;
using static global::_3sln.Flint.Kgen.Rt.Tabletrans;
using static global::_3sln.Flint.Kgen.Rt.Vecassoc;
using static global::_3sln.Flint.Kgen.Rt.Vecread;
using static global::_3sln.Flint.Kgen.Rt.Vectrans;

public static class Collgen {
    /// How many things are in it.
    /// 
    /// NIL COUNTS 0, which is the first arm because it is the common one and
    /// because nil is not a heap value: everything below would have to say so
    /// again.
    public static int CountOf(Rt rt, long v) {
        if (Val.IsNil(v)) {
            return 0;
        }
        if (Str.IsString(rt, v)) {
            return Str.CharLen(rt, v);
        }
        if (Val.IsHeap(v)) {
            int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
            if (t == Obj.TyVec) {
                return Vec.Count(rt, v);
            }
            // A MAP ENTRY COUNTS 2, and so does a tagged literal, which
            // reads like a two-key map (`0034`). The ports threw for a map
            // entry -- a value `(seq some-map)` hands out -- so ordinary
            // guest code could not count one.
            if ((t == Obj.TyMapentry) || (t == Obj.TyTagged)) {
                return 2;
            }
            if (t == Obj.TyTable) {
                return TableCount(rt, v);
            }
            if (t == Obj.TyTtable) {
                return TtableCount(rt, v);
            }
            // A REF COUNTS ITS COLUMNS, because it is a map of them.
            if (t == Obj.TyTableref) {
                return global::Flint.Rt.Table.schemaLen(rt, rt.Slot(v, global::Flint.Rt.Table.RF_SCHEMA));
            }
            if ((t == Obj.TyArraymap) || (t == Obj.TyHashmap)) {
                return MapCount(rt, v);
            }
            if (t == Obj.TySet) {
                return SetCount(rt, v);
            }
            if ((t == Obj.TyBytes) || (t == Obj.TyBrope)) {
                return BCount(rt, v);
            }
            if (t == Obj.TyTvec) {
                return TvecCount(rt, v);
            }
            if (t == Obj.TyTmap) {
                return TmapCount(rt, v);
            }
            if (t == Obj.TyTset) {
                return TsetCount(rt, v);
            }
            if (t == Obj.TyEmptyList) {
                return 0;
            }
            if (IsSeq(rt, v)) {
                return SeqCount(rt, v);
            }
        }
        string what = Describe(rt, v);
        rt.ThrowStr("UnsupportedOperationException", "count over " + what + " needs more of the data structures");
        return 0;
    }
    /// The collection one shorter at the end it is written from.
    /// 
    /// A VECTOR POPS ITS LAST and a list its first, which is the same word for
    /// two ends because it is the same word in Clojure: `pop` takes off
    /// whichever end `conj` puts on.
    public static long PopOf(Rt rt, long coll) {
        if (Val.IsNil(coll)) {
            return rt.ThrowStr("IllegalStateException", "cannot pop nil");
        }
        if (Val.IsHeap(coll)) {
            int t = Obj.Ty(rt.gc.sp, Val.AsHeap(coll));
            if (t == Obj.TyVec) {
                if (Vec.Count(rt, coll) == 0) {
                    return rt.ThrowStr("IllegalStateException", "cannot pop an empty vector");
                }
                return Vec.Pop(rt, coll);
            }
            if (t == Obj.TyEmptyList) {
                return rt.ThrowStr("IllegalStateException", "cannot pop an empty list");
            }
        }
        return Rest(rt, coll);
    }
    /// The thing `pop` would take off, without taking it.
    /// 
    /// ANSWERS NIL RATHER THAN THROWING on an empty collection, which is the
    /// difference between it and `pop`: peeking at nothing is a question with
    /// an answer.
    public static long PeekOf(Rt rt, long coll) {
        if (Val.IsNil(coll)) {
            return Val.Nil;
        }
        if (Val.IsHeap(coll)) {
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyVec) {
                int n = Vec.Count(rt, coll);
                if (n == 0) {
                    return Val.Nil;
                }
                return Vec.Nth(rt, coll, n - 1, Val.Nil);
            }
        }
        return First(rt, coll);
    }
    /// An empty collection of the same KIND, and NIL when there is no kind.
    /// 
    /// The shared singleton in each case, not a fresh allocation: an empty
    /// vector is three objects, and `(empty v)` is asked for exactly when a
    /// program is about to build something else.
    /// 
    /// A ROW REF ANSWERS THE EMPTY MAP, because a ref is a map. Native sent it
    /// to the empty LIST -- its arm named the two map tags and a ref is
    /// neither -- so `(empty row)` was `{}` on both ports and `()` on wasm.
    /// 
    /// AND THE LIST IS ONLY FOR A SEQ. Native answered `()` for any heap value
    /// it did not otherwise name, so `(empty "abc")` was `()` there and nil
    /// on both ports. Clojure answers nil, which is what a value with no empty
    /// of its own has.
    public static long EmptyOf(Rt rt, long coll) {
        if (Val.IsHeap(coll)) {
            int t = Obj.Ty(rt.gc.sp, Val.AsHeap(coll));
            if (t == Obj.TyVec) {
                return Vec.Empty(rt);
            }
            if ((t == Obj.TyArraymap) || (t == Obj.TyHashmap)) {
                return global::Flint.Rt.Maps.Empty(rt);
            }
            if (t == Obj.TyTableref) {
                return global::Flint.Rt.Maps.Empty(rt);
            }
            if (t == Obj.TySet) {
                return global::Flint.Rt.Sets.Empty(rt);
            }
            if (IsSeq(rt, coll)) {
                return global::Flint.Rt.Seqs.EmptyList(rt);
            }
        }
        return Val.Nil;
    }
}
