// Generated by kin from the source named below. Do not edit.
// source: flint.rt.exinfo

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Exinfo {
    /// Is `v` an exception value?
    /// 
    /// The tag test, and every accessor below is guarded by it -- reading a
    /// slot off something that is not an exception reads whatever is at that
    /// offset, which is the class of bug `(conj 1 2)` was.
    public static bool IsException(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        return Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyExinfo;
    }
    /// Build an exception value WITHOUT throwing it.
    /// 
    /// The scheduler needs this: it hands an error to a PARKED thread, to be
    /// raised when that thread next resumes rather than in whatever thread
    /// noticed the problem.
    /// 
    /// A FAILED ALLOCATION ANSWERS NIL rather than throwing, because throwing
    /// is what the caller is in the middle of arranging.
    public static long ExInfo(Rt rt, long kind, long msg, long data, long cause) {
        int @base = rt.Mark();
        int k = rt.Push(kind);
        int m = rt.Push(msg);
        int d = rt.Push(data);
        int c = rt.Push(cause);
        long a = rt.Alloc(Obj.TyExinfo, 4);
        if (a == 0) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        // READ BACK THROUGH `r`, because `alloc` may have moved all four.
        rt.SetSlot(Val.AsHeap(Val.Heap(a)), global::Flint.Rt.Rt.ExKindSlot, rt.R(k));
        rt.SetSlot(Val.AsHeap(Val.Heap(a)), global::Flint.Rt.Rt.ExMsgSlot, rt.R(m));
        rt.SetSlot(Val.AsHeap(Val.Heap(a)), global::Flint.Rt.Rt.ExDataSlot, rt.R(d));
        rt.SetSlot(Val.AsHeap(Val.Heap(a)), global::Flint.Rt.Rt.ExCauseSlot, rt.R(c));
        rt.PopTo(@base);
        return Val.Heap(a);
    }
    /// The message, or nil when `e` is not an exception.
    public static long ExMessage(Rt rt, long e) {
        if (IsException(rt, e)) {
            return rt.Slot(e, global::Flint.Rt.Rt.ExMsgSlot);
        }
        return Val.Nil;
    }
    /// The data map, or nil.
    public static long ExData(Rt rt, long e) {
        if (IsException(rt, e)) {
            return rt.Slot(e, global::Flint.Rt.Rt.ExDataSlot);
        }
        return Val.Nil;
    }
    /// The kind -- the class name a `catch` selects on -- or nil.
    public static long ExKind(Rt rt, long e) {
        if (IsException(rt, e)) {
            return rt.Slot(e, global::Flint.Rt.Rt.ExKindSlot);
        }
        return Val.Nil;
    }
}
