// Generated by kin from the source named below. Do not edit.
// source: flint.rt.formsenc

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Byteconcat;
using static global::_3sln.Flint.Kgen.Rt.Collvec;
using static global::_3sln.Flint.Kgen.Rt.Dblstr;
using static global::_3sln.Flint.Kgen.Rt.Mapcore;
using static global::_3sln.Flint.Kgen.Rt.Mapmake;
using static global::_3sln.Flint.Kgen.Rt.Mapread;
using static global::_3sln.Flint.Kgen.Rt.Maptrans;
using static global::_3sln.Flint.Kgen.Rt.Mapwrite;
using static global::_3sln.Flint.Kgen.Rt.Meta;
using static global::_3sln.Flint.Kgen.Rt.Names;
using static global::_3sln.Flint.Kgen.Rt.Numint;
using static global::_3sln.Flint.Kgen.Rt.Numkind;
using static global::_3sln.Flint.Kgen.Rt.Opaque;
using static global::_3sln.Flint.Kgen.Rt.Readconst;
using static global::_3sln.Flint.Kgen.Rt.Readcore;
using static global::_3sln.Flint.Kgen.Rt.Readform;
using static global::_3sln.Flint.Kgen.Rt.Ropeflat;
using static global::_3sln.Flint.Kgen.Rt.Ropemeas;
using static global::_3sln.Flint.Kgen.Rt.Seqcore;
using static global::_3sln.Flint.Kgen.Rt.Seqwalk;
using static global::_3sln.Flint.Kgen.Rt.Setcore;
using static global::_3sln.Flint.Kgen.Rt.Transients;
using static global::_3sln.Flint.Kgen.Rt.Valeq;
using static global::_3sln.Flint.Kgen.Rt.Vecnode;
using static global::_3sln.Flint.Kgen.Rt.Vecread;
using static global::_3sln.Flint.Kgen.Rt.Vecroots;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;

public static class Formsenc {
    internal static long Eget(Rt rt, int esi, int s) {
        return NodeGet(rt, rt.R(esi), s);
    }
    internal static void Eput(Rt rt, int esi, int s, long v) {
        NodeSet(rt, rt.R(esi), s, v);
    }
    internal static int Ebody(Rt rt, int esi) {
        return (int) Val.AsFixnum(Eget(rt, esi, FeBody));
    }
    /// `n`, non-negative, as a varint: seven bits a byte, low first.
    public static void PutVarint(Rt rt, int sk, long n) {
        long v;
        v = n;
        while (v >= 128) {
            rt.SinkPut(sk, (int) (128 + (v % 128)));
            v = v / 128;
        }
        rt.SinkPut(sk, (int) v);
    }
    /// The index of `v` in one of the two tables (`FE_STRS`/`FE_STRXS` or
    /// `FE_NAMES`/`FE_NAMEXS`), adding it when it is new.
    internal static long Intern(Rt rt, int esi, int ix, int xs, long v) {
        int @base = rt.Mark();
        int vi = rt.Push(v);
        long hit = TmapGet(rt, Eget(rt, esi, ix), rt.R(vi), Val.NotFound);
        if (hit != Val.NotFound) {
            rt.PopTo(@base);
            return Val.AsFixnum(hit);
        }
        int i = VecCount(rt, Eget(rt, esi, xs));
        long t2 = TransientAssoc(rt, Eget(rt, esi, ix), rt.R(vi), Val.Fixnum(i & 0xFFFFFFFFL));
        Eput(rt, esi, ix, t2);
        long v2 = VecConj(rt, Eget(rt, esi, xs), rt.R(vi));
        Eput(rt, esi, xs, v2);
        rt.PopTo(@base);
        return (long) i;
    }
    /// `{:line l :column c :file f}` as the decoder's literal builds it,
    /// pushed; with `:child-pos` (rooted at `cpi`) before `:file` when
    /// `cp-first`, after it otherwise, or not at all when `cpi` holds nil.
    internal static void PushLiteral(Rt rt, int esi, long line, long col, int cpi) {
        int @base = rt.Mark();
        long e = global::Flint.Rt.Maps.Empty(rt);
        int mi = rt.Push(e);
        bool hasCp = !Val.IsNil(rt.R(cpi));
        bool cpf = Eget(rt, esi, FeCpfirst) == Val.True;
        long m1 = MapAssoc(rt, rt.R(mi), Eget(rt, esi, FeKline), Val.Fixnum(line));
        rt.SetR(mi, m1);
        long m2 = MapAssoc(rt, rt.R(mi), Eget(rt, esi, FeKcol), Val.Fixnum(col));
        rt.SetR(mi, m2);
        if (hasCp && cpf) {
            long m3 = MapAssoc(rt, rt.R(mi), Eget(rt, esi, FeKcp), rt.R(cpi));
            rt.SetR(mi, m3);
        }
        long m4 = MapAssoc(rt, rt.R(mi), Eget(rt, esi, FeKfile), Eget(rt, esi, FeFile));
        rt.SetR(mi, m4);
        if (hasCp && !cpf) {
            long m5 = MapAssoc(rt, rt.R(mi), Eget(rt, esi, FeKcp), rt.R(cpi));
            rt.SetR(mi, m5);
        }
        long @out = rt.R(mi);
        rt.PopTo(@base);
        rt.Push(@out);
    }
    /// `flint.forms/pos-map`, pushed: the literal when there are no extra
    /// keys, and otherwise `position-meta` -- the literal, the child positions
    /// and the extra keys as an array map, MERGED.
    internal static void PushPosMap(Rt rt, int esi, long line, long col, int cpi, int extrai) {
        if (VecCount(rt, rt.R(extrai)) == 0) {
            PushLiteral(rt, esi, line, col, cpi);
            return;
        }
        int @base = rt.Mark();
        int nocp = rt.Push(Val.Nil);
        PushLiteral(rt, esi, line, col, nocp);
        // `(when (seq children) {:child-pos children})`.
        if (Val.IsNil(rt.R(cpi))) {
            rt.Push(Val.Nil);
        } else if (VecCount(rt, rt.R(cpi)) == 0) {
            rt.Push(Val.Nil);
        } else {
            long e = global::Flint.Rt.Maps.Empty(rt);
            long m = MapAssoc(rt, e, Eget(rt, esi, FeKcp), rt.R(cpi));
            rt.Push(m);
        }
        long am = OrderedMap(rt, rt.R(extrai));
        rt.Push(am);
        Merge3(rt, @base + 1, @base + 2, @base + 3);
        long @out = rt.R(@base + 4);
        rt.PopTo(@base);
        rt.Push(@out);
    }
    /// Do the maps at `ai` and `bi` hold equal entries IN THE SAME KEY ORDER?
    internal static bool SameMap(Rt rt, int ai, int bi) {
        if (!ValEq(rt, rt.R(ai), rt.R(bi))) {
            return false;
        }
        int @base = rt.Mark();
        long ea = MapEntryVector(rt, rt.R(ai));
        int eai = rt.Push(ea);
        long eb = MapEntryVector(rt, rt.R(bi));
        int ebi = rt.Push(eb);
        int n = VecCount(rt, rt.R(eai));
        for (int i = 0; i < n; i++) {
            long ka = rt.Slot(VecNth(rt, rt.R(eai), i, Val.Nil), 0);
            int kai = rt.Push(ka);
            long kb = rt.Slot(VecNth(rt, rt.R(ebi), i, Val.Nil), 0);
            bool same = ValEq(rt, rt.R(kai), kb);
            rt.PopTo(kai);
            if (!same) {
                rt.PopTo(@base);
                return false;
            }
        }
        rt.PopTo(@base);
        return true;
    }
    /// The integer at the key in slot `k` of the metadata rooted at `mi`.
    internal static long MetaInt(Rt rt, int esi, int mi, int k) {
        long v = MapGet(rt, rt.R(mi), Eget(rt, esi, k), Val.Nil);
        return IntegerValue(rt, v);
    }
    /// Is `v` a non-negative integer?
    internal static bool IsNat(Rt rt, long v) {
        if (!IsInt(rt, v)) {
            return false;
        }
        return IntegerValue(rt, v) >= 0;
    }
    /// `flint.forms/pos-parts` of the metadata rooted at `mi`: true when the
    /// decoder's construction rebuilds it EXACTLY, with the child positions and
    /// the extra keys -- a flat `[k v ..]` vector, in the map's order --
    /// pushed in that order. False pushes nothing.
    internal static bool PosParts(Rt rt, int esi, int mi) {
        long lv = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKline), Val.Nil);
        long cv = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKcol), Val.Nil);
        if (!(IsInt(rt, lv) && IsNat(rt, cv))) {
            return false;
        }
        long fv = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKfile), Val.Nil);
        if (!ValEq(rt, Eget(rt, esi, FeFile), fv)) {
            return false;
        }
        int @base = rt.Mark();
        long cp = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKcp), Val.Nil);
        int cpi = rt.Push(cp);
        if (!Val.IsNil(rt.R(cpi))) {
            if (!IsVectorLike(rt, rt.R(cpi))) {
                rt.PopTo(@base);
                return false;
            }
            int cn = VecCount(rt, rt.R(cpi));
            if ((cn % 2) != 0) {
                rt.PopTo(@base);
                return false;
            }
            for (int i = 0; i < cn; i++) {
                if (!IsNat(rt, VecNth(rt, rt.R(cpi), i, Val.Nil))) {
                    rt.PopTo(@base);
                    return false;
                }
            }
        }
        // THE EXTRA KEYS: everything but the four the reader writes.
        long ev = MapEntryVector(rt, rt.R(mi));
        int evi = rt.Push(ev);
        int flat = rt.Mark();
        int n = VecCount(rt, rt.R(evi));
        for (int j = 0; j < n; j++) {
            long en = VecNth(rt, rt.R(evi), j, Val.Nil);
            int eni = rt.Push(en);
            long k = rt.Slot(rt.R(eni), 0);
            if (ValEq(rt, k, Eget(rt, esi, FeKline)) || (ValEq(rt, rt.Slot(rt.R(eni), 0), Eget(rt, esi, FeKcol)) || (ValEq(rt, rt.Slot(rt.R(eni), 0), Eget(rt, esi, FeKfile)) || ValEq(rt, rt.Slot(rt.R(eni), 0), Eget(rt, esi, FeKcp))))) {
                rt.PopTo(eni);
            } else {
                long vv = rt.Slot(rt.R(eni), 1);
                rt.SetR(eni, rt.Slot(rt.R(eni), 0));
                rt.Push(vv);
            }
        }
        long extra = VecFromRoots(rt, flat, (int) (rt.Mark() - flat));
        rt.PopTo(flat);
        rt.SetR(evi, extra);
        long line = MetaInt(rt, esi, mi, FeKline);
        long col = MetaInt(rt, esi, mi, FeKcol);
        PushPosMap(rt, esi, line, col, cpi, evi);
        int bi = evi + 1;
        if (!SameMap(rt, bi, mi)) {
            rt.PopTo(@base);
            return false;
        }
        rt.PopTo(bi);
        // Leave exactly `cp extra`, which is what is at `base`.
        return true;
    }
    /// A child's own `[line col]`, when its metadata has both as integers:
    /// true and pushed, or false and nothing.
    internal static bool OwnPos(Rt rt, int esi, long x) {
        if (!(IsSymbol(rt, x) || (IsVectorLike(rt, x) || (IsMap(rt, x) || (IsSet(rt, x) || IsSeq(rt, x)))))) {
            return false;
        }
        long m = MetaOf(rt, x);
        if (Val.IsNil(m)) {
            return false;
        }
        int @base = rt.Mark();
        int mi = rt.Push(m);
        long l = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKline), Val.Nil);
        long c = MapGet(rt, rt.R(mi), Eget(rt, esi, FeKcol), Val.Nil);
        if (IsInt(rt, l) && IsInt(rt, c)) {
            rt.PopTo(@base);
            rt.Push(l);
            rt.Push(c);
            return true;
        }
        rt.PopTo(@base);
        return false;
    }
    /// Can the child positions rooted at `cpi` be rebuilt from the children
    /// (the vector at `xsi`) and the pairs written for those without their own?
    internal static bool Derivable(Rt rt, int esi, int cpi, int xsi) {
        int n = VecCount(rt, rt.R(xsi));
        if (VecCount(rt, rt.R(cpi)) != (2 * n)) {
            return false;
        }
        for (int i = 0; i < n; i++) {
            int @base = rt.Mark();
            if (OwnPos(rt, esi, VecNth(rt, rt.R(xsi), i, Val.Nil))) {
                bool same = ValEq(rt, rt.R(@base), VecNth(rt, rt.R(cpi), 2 * i, Val.Nil)) && ValEq(rt, rt.R(@base + 1), VecNth(rt, rt.R(cpi), (2 * i) + 1, Val.Nil));
                rt.PopTo(@base);
                if (!same) {
                    return false;
                }
            }
        }
        return true;
    }
    /// Write the elements rooted at `at` .. `at + n`.
    internal static int PutRun(Rt rt, int esi, int at, int n) {
        for (int i = 0; i < n; i++) {
            int st = PutValue(rt, esi, at + i);
            if (st != RsOk) {
                return st;
            }
        }
        return RsOk;
    }
    /// Push every element of the collection at `vi`, answering how many: a
    /// seq walked, a vector indexed, a set in its own order.
    internal static int PushElements(Rt rt, int vi) {
        if (IsVectorLike(rt, rt.R(vi))) {
            int n = VecCount(rt, rt.R(vi));
            for (int i = 0; i < n; i++) {
                rt.Push(VecNth(rt, rt.R(vi), i, Val.Nil));
            }
            return n;
        }
        if (IsSet(rt, rt.R(vi))) {
            long xs = SetElementVector(rt, rt.R(vi));
            int xsi = rt.Push(xs);
            int sn = VecCount(rt, rt.R(xsi));
            for (int j = 0; j < sn; j++) {
                rt.Push(VecNth(rt, rt.R(xsi), j, Val.Nil));
            }
            // The element vector's root sits under the elements; move them
            // down over it.
            for (int k = 0; k < sn; k++) {
                rt.SetR(xsi + k, rt.R(xsi + (k + 1)));
            }
            rt.PopTo(xsi + sn);
            return sn;
        }
        long s0 = Seq(rt, rt.R(vi));
        int si = rt.Push(s0);
        int cnt;
        cnt = 0;
        for (;;) {
            if (Val.IsNil(rt.R(si))) {
                break;
            }
            long x = First(rt, rt.R(si));
            rt.Push(x);
            cnt += 1;
            long nx = Next(rt, rt.R(si));
            rt.SetR(si, nx);
        }
        for (int q = 0; q < cnt; q++) {
            rt.SetR(si + q, rt.R(si + (q + 1)));
        }
        rt.PopTo(si + cnt);
        return cnt;
    }
    /// Record an encoder error and answer `RS_ERR`.
    internal static int Efail(Rt rt, int esi, int sk) {
        long m = rt.SinkString(sk);
        rt.SinkClose(sk);
        Eput(rt, esi, FeErr, m);
        return RsErr;
    }
    /// A number written as text, `FT_NUM`: what `num->str` says, or the three
    /// that have no digits.
    internal static void PutNumText(Rt rt, int esi, long v) {
        long text;
        text = Val.Nil;
        if (Val.IsDouble(v)) {
            double d = Num.F64(rt, v);
            if (double.IsNaN(d)) {
                text = Str.Of(rt, "##NaN");
            } else if (double.IsInfinity(d)) {
                if (d > 0.0) {
                    text = Str.Of(rt, "##Inf");
                } else {
                    text = Str.Of(rt, "##-Inf");
                }
            }
        }
        if (Val.IsNil(text)) {
            text = NumToStr(rt, v);
        }
        long ix = Intern(rt, esi, FeStrs, FeStrxs, text);
        rt.SinkPut(Ebody(rt, esi), FtNum);
        PutVarint(rt, Ebody(rt, esi), ix);
    }
    /// `v`, rooted at `vi`, WITHOUT its metadata.
    internal static int PutBare(Rt rt, int esi, int vi) {
        int b = Ebody(rt, esi);
        long v = rt.R(vi);
        if (Val.IsNil(v)) {
            rt.SinkPut(b, FtNil);
            return RsOk;
        }
        if (v == Val.True) {
            rt.SinkPut(b, FtTrue);
            return RsOk;
        }
        if (v == Val.False) {
            rt.SinkPut(b, FtFalse);
            return RsOk;
        }
        if (IsInt(rt, v)) {
            long n = IntegerValue(rt, v);
            if ((n > -1) && (n < VarintLimit)) {
                rt.SinkPut(b, FtInt);
                PutVarint(rt, b, n);
                return RsOk;
            }
            if ((n > (0 - VarintLimit)) && (n < 0)) {
                rt.SinkPut(b, FtNeg);
                PutVarint(rt, b, 0 - n);
                return RsOk;
            }
            PutNumText(rt, esi, rt.R(vi));
            return RsOk;
        }
        if (Val.IsDouble(v)) {
            PutNumText(rt, esi, v);
            return RsOk;
        }
        if (IsString(rt, v)) {
            long si = Intern(rt, esi, FeStrs, FeStrxs, v);
            rt.SinkPut(Ebody(rt, esi), FtStr);
            PutVarint(rt, Ebody(rt, esi), si);
            return RsOk;
        }
        if (IsSymbol(rt, v) || IsKeyword(rt, v)) {
            // INTERNED WITHOUT METADATA: equality ignores it, so the symbol
            // itself is the key, and the table writes only its names.
        }
        if (IsSymbol(rt, v) || IsKeyword(rt, v)) {
            long ni = Intern(rt, esi, FeNames, FeNamexs, v);
            rt.SinkPut(Ebody(rt, esi), FtName);
            PutVarint(rt, Ebody(rt, esi), ni);
            return RsOk;
        }
        if (IsSeq(rt, v) || (IsVectorLike(rt, v) || IsSet(rt, v))) {
            int @base = rt.Mark();
            bool isList = IsSeq(rt, rt.R(vi));
            bool isVec = IsVectorLike(rt, rt.R(vi));
            int n = PushElements(rt, vi);
            if (isList) {
                rt.SinkPut(Ebody(rt, esi), FtList);
            } else if (isVec) {
                rt.SinkPut(Ebody(rt, esi), FtVec);
            } else {
                rt.SinkPut(Ebody(rt, esi), FtSet);
            }
            PutVarint(rt, Ebody(rt, esi), (long) n);
            int st = PutRun(rt, esi, @base, n);
            rt.PopTo(@base);
            return st;
        }
        if (IsMap(rt, v)) {
            int mbase = rt.Mark();
            long ev = MapEntryVector(rt, rt.R(vi));
            int evi = rt.Push(ev);
            int mn = VecCount(rt, rt.R(evi));
            rt.SinkPut(Ebody(rt, esi), FtMap);
            PutVarint(rt, Ebody(rt, esi), (long) mn);
            for (int i = 0; i < mn; i++) {
                long en = VecNth(rt, rt.R(evi), i, Val.Nil);
                int ki = rt.Push(rt.Slot(en, 0));
                int vvi = rt.Push(rt.Slot(VecNth(rt, rt.R(evi), i, Val.Nil), 1));
                int kst = PutValue(rt, esi, ki);
                if (kst != RsOk) {
                    rt.PopTo(mbase);
                    return kst;
                }
                int vst = PutValue(rt, esi, vvi);
                if (vst != RsOk) {
                    rt.PopTo(mbase);
                    return vst;
                }
                rt.PopTo(ki);
            }
            rt.PopTo(mbase);
            return RsOk;
        }
        if (IsTagged(rt, v)) {
            int tbase = rt.Mark();
            int tgi = rt.Push(rt.Slot(v, 0));
            int fmi = rt.Push(rt.Slot(rt.R(vi), 1));
            rt.SinkPut(Ebody(rt, esi), FtTagged);
            int tst = PutValue(rt, esi, tgi);
            if (tst != RsOk) {
                rt.PopTo(tbase);
                return tst;
            }
            int fst = PutValue(rt, esi, fmi);
            rt.PopTo(tbase);
            return fst;
        }
        int ek = rt.SinkOpen();
        MsgLit(rt, ek, "flint.forms cannot write this value");
        return Efail(rt, esi, ek);
    }
    /// A position: the line as a delta from the last one written, the column.
    internal static void PutPos(Rt rt, int esi, long line, long col) {
        long last = Val.AsFixnum(Eget(rt, esi, FeLine));
        PutVarint(rt, Ebody(rt, esi), Zigzag(line - last));
        Eput(rt, esi, FeLine, Val.Fixnum(line));
        PutVarint(rt, Ebody(rt, esi), col);
    }
    /// `v`, rooted at `vi`, with its metadata.
    public static int PutValue(Rt rt, int esi, int vi) {
        long v = rt.R(vi);
        if (!(IsSymbol(rt, v) || (IsVectorLike(rt, v) || (IsMap(rt, v) || (IsSet(rt, v) || IsSeq(rt, v)))))) {
            return PutBare(rt, esi, vi);
        }
        int @base = rt.Mark();
        long m = MetaOf(rt, rt.R(vi));
        int mi = rt.Push(m);
        if (Val.IsNil(rt.R(mi))) {
            rt.PopTo(@base);
            return PutBare(rt, esi, vi);
        }
        if (!PosParts(rt, esi, mi)) {
            rt.SinkPut(Ebody(rt, esi), FtMeta);
            int mst = PutValue(rt, esi, mi);
            if (mst != RsOk) {
                rt.PopTo(@base);
                return mst;
            }
            int bst = PutBare(rt, esi, vi);
            rt.PopTo(@base);
            return bst;
        }
        // `cp extra` are at `mi + 1` and `mi + 2`.
        int cpi = mi + 1;
        int exi = mi + 2;
        long line = MetaInt(rt, esi, mi, FeKline);
        long col = MetaInt(rt, esi, mi, FeKcol);
        bool hasCp = !Val.IsNil(rt.R(cpi));
        int nextra = VecCount(rt, rt.R(exi));
        if (IsSymbol(rt, rt.R(vi)) && (!hasCp && (nextra == 0))) {
            long ni = Intern(rt, esi, FeNames, FeNamexs, rt.R(vi));
            rt.SinkPut(Ebody(rt, esi), FtPosSym);
            PutPos(rt, esi, line, col);
            PutVarint(rt, Ebody(rt, esi), ni);
            rt.PopTo(@base);
            return RsOk;
        }
        // THE CHILDREN, when there are positions for them: a map has
        // none to derive from.
        bool derived;
        derived = false;
        int xsi = rt.Mark();
        if (hasCp && !IsMap(rt, rt.R(vi))) {
            int eb = rt.Mark();
            int en = PushElements(rt, vi);
            long xs = VecFromRoots(rt, eb, en);
            rt.PopTo(eb);
            rt.Push(xs);
            derived = Derivable(rt, esi, cpi, xsi);
        } else {
            rt.Push(Val.Nil);
        }
        rt.SinkPut(Ebody(rt, esi), FtPos);
        PutPos(rt, esi, line, col);
        long flags;
        flags = 0;
        if (hasCp) {
            if (derived) {
                flags = (long) FfCpDerived;
            } else {
                flags = (long) FfCpFull;
            }
        }
        if (nextra > 0) {
            flags += (long) FfExtra;
        }
        PutVarint(rt, Ebody(rt, esi), flags);
        if (nextra > 0) {
            PutVarint(rt, Ebody(rt, esi), (long) (nextra / 2));
            int xb = rt.Mark();
            for (int i = 0; i < nextra; i++) {
                rt.Push(VecNth(rt, rt.R(exi), i, Val.Nil));
            }
            int xst = PutRun(rt, esi, xb, nextra);
            rt.PopTo(xb);
            if (xst != RsOk) {
                rt.PopTo(@base);
                return xst;
            }
        }
        int bst2 = PutBare(rt, esi, vi);
        if (bst2 != RsOk) {
            rt.PopTo(@base);
            return bst2;
        }
        // THE CHILD POSITIONS AFTER THE CHILDREN, so the derived ones
        // can be read off what was just decoded.
        if (hasCp) {
            if (derived) {
                int n = VecCount(rt, rt.R(xsi));
                for (int k = 0; k < n; k++) {
                    int ob = rt.Mark();
                    if (OwnPos(rt, esi, VecNth(rt, rt.R(xsi), k, Val.Nil))) {
                        rt.PopTo(ob);
                    } else {
                        long cl = IntegerValue(rt, VecNth(rt, rt.R(cpi), 2 * k, Val.Nil));
                        long cc = IntegerValue(rt, VecNth(rt, rt.R(cpi), (2 * k) + 1, Val.Nil));
                        PutVarint(rt, Ebody(rt, esi), Zigzag(cl - line));
                        PutVarint(rt, Ebody(rt, esi), cc);
                    }
                }
            } else {
                int cn = VecCount(rt, rt.R(cpi));
                PutVarint(rt, Ebody(rt, esi), (long) (cn / 2));
                int q;
                q = 0;
                while (q < cn) {
                    long fl = IntegerValue(rt, VecNth(rt, rt.R(cpi), q, Val.Nil));
                    long fc = IntegerValue(rt, VecNth(rt, rt.R(cpi), q + 1, Val.Nil));
                    PutVarint(rt, Ebody(rt, esi), Zigzag(fl - line));
                    PutVarint(rt, Ebody(rt, esi), fc);
                    q += 2;
                }
            }
        }
        rt.PopTo(@base);
        return RsOk;
    }
    /// A string's UTF-8: its byte count, then the bytes.
    internal static void PutString(Rt rt, int sk, long s) {
        PutVarint(rt, sk, (long) SBytes(rt, s));
        SAppend(rt, s, sk);
    }
    /// `flint.forms/encode` of the header rooted at `hi` and the forms vector
    /// at `fi`, with the file named `file` (rooted at `filei`). Pushes the
    /// bytes, or an error message string with `RS_ERR`.
    public static int FormsEncode(Rt rt, int hi, int fi, int filei) {
        int @base = rt.Mark();
        long node = NewNode(rt, FeLen, Val.Nil);
        int esi = rt.Push(node);
        int body = rt.SinkOpen();
        Eput(rt, esi, FeBody, Val.Fixnum(body & 0xFFFFFFFFL));
        Eput(rt, esi, FeFile, rt.R(filei));
        Eput(rt, esi, FeLine, Val.Fixnum(1 & 0xFFFFFFFFL));
        long t1 = ToTransient(rt, global::Flint.Rt.Maps.Empty(rt));
        Eput(rt, esi, FeStrs, t1);
        Eput(rt, esi, FeStrxs, Vec.Empty(rt));
        long t2 = ToTransient(rt, global::Flint.Rt.Maps.Empty(rt));
        Eput(rt, esi, FeNames, t2);
        Eput(rt, esi, FeNamexs, Vec.Empty(rt));
        long kl = LitKeyword1(rt, "line");
        Eput(rt, esi, FeKline, kl);
        long kc = LitKeyword1(rt, "column");
        Eput(rt, esi, FeKcol, kc);
        long kf = LitKeyword1(rt, "file");
        Eput(rt, esi, FeKfile, kf);
        long kp = LitKeyword1(rt, "child-pos");
        Eput(rt, esi, FeKcp, kp);
        // `cp-first?`: does the merge leave `:child-pos` before `:file`?
        // Asked of the runtime, as the guest asks it -- the order is the
        // trie's, and both halves of the format have to agree about it.
        int qb = rt.Mark();
        long e0 = global::Flint.Rt.Maps.Empty(rt);
        int q0 = rt.Push(e0);
        long m1 = MapAssoc(rt, rt.R(q0), Eget(rt, esi, FeKline), Val.Fixnum(1 & 0xFFFFFFFFL));
        rt.SetR(q0, m1);
        long m2 = MapAssoc(rt, rt.R(q0), Eget(rt, esi, FeKcol), Val.Fixnum(1 & 0xFFFFFFFFL));
        rt.SetR(q0, m2);
        long fs = Str.Of(rt, "f");
        long m3 = MapAssoc(rt, rt.R(q0), Eget(rt, esi, FeKfile), fs);
        rt.SetR(q0, m3);
        int q1 = rt.Push(Val.Nil);
        long e1 = global::Flint.Rt.Maps.Empty(rt);
        int cpm = rt.Push(e1);
        rt.Push(Val.Fixnum(1 & 0xFFFFFFFFL));
        rt.Push(Val.Fixnum(1 & 0xFFFFFFFFL));
        long cpv = VecFromRoots(rt, cpm + 1, 2);
        rt.PopTo(cpm + 1);
        long m4 = MapAssoc(rt, rt.R(cpm), Eget(rt, esi, FeKcp), cpv);
        rt.SetR(q1, m4);
        rt.PopTo(cpm);
        rt.Push(Val.Nil);
        Merge3(rt, q0, q1, q1 + 1);
        long ev = MapEntryVector(rt, rt.R(q1 + 2));
        int evi = rt.Push(ev);
        // The keys, in order, are exactly line column child-pos file?
        bool cpf;
        cpf = VecCount(rt, rt.R(evi)) == 4;
        if (cpf) {
            cpf = (ValEq(rt, rt.Slot(VecNth(rt, rt.R(evi), 0, Val.Nil), 0), Eget(rt, esi, FeKline)) && ValEq(rt, rt.Slot(VecNth(rt, rt.R(evi), 1, Val.Nil), 0), Eget(rt, esi, FeKcol))) && (ValEq(rt, rt.Slot(VecNth(rt, rt.R(evi), 2, Val.Nil), 0), Eget(rt, esi, FeKcp)) && ValEq(rt, rt.Slot(VecNth(rt, rt.R(evi), 3, Val.Nil), 0), Eget(rt, esi, FeKfile)));
        }
        if (cpf) {
            Eput(rt, esi, FeCpfirst, Val.True);
        } else {
            Eput(rt, esi, FeCpfirst, Val.False);
        }
        rt.PopTo(qb);
        int st;
        st = PutValue(rt, esi, hi);
        if (st == RsOk) {
            PutVarint(rt, body, (long) VecCount(rt, rt.R(fi)));
            int n = VecCount(rt, rt.R(fi));
            for (int i = 0; i < n; i++) {
                if (st == RsOk) {
                    int xi = rt.Push(VecNth(rt, rt.R(fi), i, Val.Nil));
                    st = PutValue(rt, esi, xi);
                    rt.PopTo(xi);
                }
            }
        }
        if (st != RsOk) {
            long err = Eget(rt, esi, FeErr);
            rt.SinkClose(body);
            rt.PopTo(@base);
            rt.Push(err);
            return RsErr;
        }
        // THE NAME TABLE refers into the string table, so it is resolved
        // to indices before the string table is written -- and may add to
        // it: namespace first, then name.
        int names = rt.SinkOpen();
        long nxs = Eget(rt, esi, FeNamexs);
        int nxi = rt.Push(nxs);
        int nn = VecCount(rt, rt.R(nxi));
        PutVarint(rt, names, (long) nn);
        for (int j = 0; j < nn; j++) {
            long nmv = VecNth(rt, rt.R(nxi), j, Val.Nil);
            int nmi = rt.Push(nmv);
            long nsv = NsOf(rt, rt.R(nmi));
            bool kw = IsKeyword(rt, rt.R(nmi));
            if (Val.IsNil(nsv)) {
                long nm1 = NameOf(rt, rt.R(nmi));
                long i1 = Intern(rt, esi, FeStrs, FeStrxs, nm1);
                if (kw) {
                    rt.SinkPut(names, FnKw);
                } else {
                    rt.SinkPut(names, FnSym);
                }
                PutVarint(rt, names, i1);
            } else {
                int nsi = rt.Push(nsv);
                long i2 = Intern(rt, esi, FeStrs, FeStrxs, rt.R(nsi));
                long nm2 = NameOf(rt, rt.R(nmi));
                long i3 = Intern(rt, esi, FeStrs, FeStrxs, nm2);
                if (kw) {
                    rt.SinkPut(names, FnKwNs);
                } else {
                    rt.SinkPut(names, FnSymNs);
                }
                PutVarint(rt, names, i2);
                PutVarint(rt, names, i3);
            }
            rt.PopTo(nmi);
        }
        int head = rt.SinkOpen();
        long sxs = Eget(rt, esi, FeStrxs);
        int sxi = rt.Push(sxs);
        int sn = VecCount(rt, rt.R(sxi));
        rt.SinkPut(head, 70);
        rt.SinkPut(head, 76);
        rt.SinkPut(head, 70);
        rt.SinkPut(head, 49);
        PutVarint(rt, head, (long) sn);
        for (int k = 0; k < sn; k++) {
            PutString(rt, head, VecNth(rt, rt.R(sxi), k, Val.Nil));
        }
        long hb = rt.SinkBytes(head);
        int hbi = rt.Push(hb);
        long nb = rt.SinkBytes(names);
        int nbi = rt.Push(nb);
        long bb = rt.SinkBytes(body);
        int bbi = rt.Push(bb);
        long hn = BConcat(rt, rt.R(hbi), rt.R(nbi));
        long all = BConcat(rt, hn, rt.R(bbi));
        rt.SinkClose(body);
        rt.PopTo(@base);
        rt.Push(all);
        return RsOk;
    }
    /// THE READER'S ENTRY: the string `src`, read as `file`, as `flint.forms`
    /// bytes -- or, when it does not read, `[message line column plain]`, the
    /// message whole ("read error: .. (file:l:c)" for the reader's own,
    /// bare for an error the guest raised from underneath it, `plain` true).
    /// 
    /// `features` nil is a DEFERRED read, `:features :any` in its options;
    /// otherwise the set the conditionals are chosen by. `tags` is the
    /// workspace's tag map or nil, `portable` the dialect, `gensym0` the first
    /// auto-gensym's number. The header's options are
    /// `{:file :features :tags :dialect}` -- `flint.project/read-options`, which
    /// is what the compiler checks them against on arrival.
    public static long ReadForms(Rt rt, long src, long file, long features, long tags, bool portable, long gensym0) {
        int @base = rt.Mark();
        int filei = rt.Push(file);
        int feati = rt.Push(features);
        int tagsi = rt.Push(tags);
        long st0 = RdNew(rt, src, rt.R(filei), rt.R(feati), rt.R(tagsi), portable, gensym0);
        int sti = rt.Push(st0);
        long cv = Vec.Empty(rt);
        int condsi = rt.Push(cv);
        int forms = rt.Mark();
        int n;
        n = 0;
        int status;
        status = RsOk;
        for (;;) {
            long n0 = RdInt(rt, sti, RdsConds);
            int rst = ReadTop(rt, sti);
            if (rst == RsEof) {
                break;
            }
            if (rst == RsErr) {
                status = RsErr;
                break;
            }
            if (RdFlag(rt, sti, RdsDefer) && (n0 != RdInt(rt, sti, RdsConds))) {
                long c2 = VecConj(rt, rt.R(condsi), Val.Fixnum(n & 0xFFFFFFFFL));
                rt.SetR(condsi, c2);
            }
            n += 1;
        }
        RdClose(rt, sti);
        if (status == RsErr) {
            int sk = rt.SinkOpen();
            bool plain = RdFlag(rt, sti, RdsErrplain);
            if (!plain) {
                MsgLit(rt, sk, "read error: ");
            }
            MsgVal(rt, sk, RdGet(rt, sti, RdsErrmsg));
            if (!plain) {
                MsgLit(rt, sk, " (");
                MsgVal(rt, sk, rt.R(filei));
                MsgLit(rt, sk, ":");
                MsgInt(rt, sk, RdInt(rt, sti, RdsErrline));
                MsgLit(rt, sk, ":");
                MsgInt(rt, sk, RdInt(rt, sti, RdsErrcol));
                MsgLit(rt, sk, ")");
            }
            long msg = rt.SinkString(sk);
            rt.SinkClose(sk);
            rt.PopTo(forms);
            rt.Push(msg);
            rt.Push(RdGet(rt, sti, RdsErrline));
            rt.Push(RdGet(rt, sti, RdsErrcol));
            if (plain) {
                rt.Push(Val.True);
            } else {
                rt.Push(Val.False);
            }
            long ev = VecFromRoots(rt, forms, 4);
            rt.PopTo(@base);
            return ev;
        }
        long fv = VecFromRoots(rt, forms, n);
        rt.PopTo(forms);
        int fvi = rt.Push(fv);
        int optsb = rt.Mark();
        long e = global::Flint.Rt.Maps.Empty(rt);
        int oi = rt.Push(e);
        // `{:file .. :features .. :tags .. :dialect ..}`, a map literal.
        long k1 = LitKeyword1(rt, "file");
        long o1 = MapAssoc(rt, rt.R(oi), k1, rt.R(filei));
        rt.SetR(oi, o1);
        long k2 = LitKeyword1(rt, "features");
        if (Val.IsNil(rt.R(feati))) {
            int k2i = rt.Push(k2);
            long anyk = LitKeyword1(rt, "any");
            long o2 = MapAssoc(rt, rt.R(oi), rt.R(k2i), anyk);
            rt.SetR(oi, o2);
            rt.PopTo(k2i);
        } else {
            long o2b = MapAssoc(rt, rt.R(oi), k2, rt.R(feati));
            rt.SetR(oi, o2b);
        }
        long k3 = LitKeyword1(rt, "tags");
        long tv;
        tv = rt.R(tagsi);
        if (!Val.IsNil(tv)) {
            if (MapCount(rt, tv) == 0) {
                tv = Val.Nil;
            }
        }
        long o3 = MapAssoc(rt, rt.R(oi), k3, tv);
        rt.SetR(oi, o3);
        long k4 = LitKeyword1(rt, "dialect");
        int k4i = rt.Push(k4);
        long dv;
        if (portable) {
            dv = LitKeyword1(rt, "portable");
        } else {
            dv = LitKeyword1(rt, "flint");
        }
        long o4 = MapAssoc(rt, rt.R(oi), rt.R(k4i), dv);
        rt.SetR(oi, o4);
        rt.PopTo(k4i);
        // `{:opts .. :conds ..}`, a map literal.
        long he = global::Flint.Rt.Maps.Empty(rt);
        int hi = rt.Push(he);
        long ko = LitKeyword1(rt, "opts");
        long h1 = MapAssoc(rt, rt.R(hi), ko, rt.R(oi));
        rt.SetR(hi, h1);
        long kc = LitKeyword1(rt, "conds");
        long h2 = MapAssoc(rt, rt.R(hi), kc, rt.R(condsi));
        rt.SetR(hi, h2);
        int est = FormsEncode(rt, hi, fvi, filei);
        long @out = rt.R(hi + 1);
        if (est == RsErr) {
            rt.PopTo(optsb);
            rt.Push(@out);
            rt.Push(Val.Fixnum(0 & 0xFFFFFFFFL));
            rt.Push(Val.Fixnum(0 & 0xFFFFFFFFL));
            rt.Push(Val.True);
            long ev2 = VecFromRoots(rt, optsb, 4);
            rt.PopTo(@base);
            return ev2;
        }
        rt.PopTo(@base);
        return @out;
    }
}
