// Generated by kin from the source named below. Do not edit.
// source: flint.rt.meta

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Meta {
    /// Can `v` carry metadata at all?
    /// 
    /// A PREDICATE AND A TOTAL ACCESSOR rather than an optional slot index, the
    /// same shape `is-int` and `i64-of` take. Rust answered `Option<u32>` and
    /// there is no slot number free to mean `nowhere` -- slot 0 is a real slot
    /// for an empty list.
    public static bool HasMeta(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if (t == Obj.TySym) {
            return true;
        }
        if (t == Obj.TyVec) {
            return true;
        }
        if (t == Obj.TyArraymap) {
            return true;
        }
        if (t == Obj.TyHashmap) {
            return true;
        }
        if (t == Obj.TySet) {
            return true;
        }
        if (t == Obj.TyCons) {
            return true;
        }
        if (t == Obj.TyEmptyList) {
            return true;
        }
        if (t == Obj.TyLazyseq) {
            return true;
        }
        if (t == Obj.TyAtom) {
            return true;
        }
        if (t == Obj.TyClosure) {
            return true;
        }
        if (t == Obj.TyTagged) {
            return true;
        }
        return false;
    }
    /// WHICH slot holds `v`'s metadata. Ask `has-meta` first.
    public static int MetaSlot(Rt rt, long v) {
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if (t == Obj.TySym) {
            return 2;
        }
        if (t == Obj.TyVec) {
            return V_META;
        }
        if (t == Obj.TyArraymap) {
            return AM_META;
        }
        if (t == Obj.TyHashmap) {
            return HM_META;
        }
        if (t == Obj.TySet) {
            return global::Flint.Rt.Sets.S_META;
        }
        if (t == Obj.TyCons) {
            return C_META;
        }
        if (t == Obj.TyEmptyList) {
            return 0;
        }
        if (t == Obj.TyLazyseq) {
            return 2;
        }
        if (t == Obj.TyAtom) {
            return 1;
        }
        // THE LAST SLOT for a closure -- see the header.
        if (t == Obj.TyClosure) {
            return Olen(rt, v) - 1;
        }
        // A TAGGED FORM keeps the tag at 0 and the form at 1, so metadata
        // goes after them. A raw 2, like `TY_SYM` and `TY_LAZYSEQ` above:
        // this function is where the slot numbers live.
        if (t == Obj.TyTagged) {
            return 2;
        }
        return 0;
    }
    /// The metadata, or nil when the value cannot carry any.
    public static long MetaOf(Rt rt, long v) {
        if (!HasMeta(rt, v)) {
            return Val.Nil;
        }
        // HOISTED: `slot` borrows and `meta-slot` takes `&mut self`, so
        // nesting them is an immutable and a mutable borrow at once.
        int at = MetaSlot(rt, v);
        return rt.Slot(v, at);
    }
    /// A COPY of `v` with `m` as its metadata, or `v` unchanged when it cannot
    /// carry any.
    /// 
    /// A COPY, because metadata is part of the value: two vectors that differ
    /// only in their metadata are still `=`, but they are not the same object,
    /// and changing one must not change the other.
    public static long WithMeta(Rt rt, long v, long m) {
        if (!HasMeta(rt, v)) {
            return v;
        }
        int idx = MetaSlot(rt, v);
        int @base = rt.Mark();
        int vi = rt.Push(v);
        int mi = rt.Push(m);
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        int n = Olen(rt, v);
        long @out = Conc.NewObj(rt, t, n);
        if (Val.IsNil(@out)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        // COPIED FROM THE ROOT, not from the host local: the allocation
        // may have moved `v` (0031).
        for (int i = 0; i < n; i++) {
            rt.SetSlot(Val.AsHeap(@out), i, rt.Slot(rt.R(vi), i));
        }
        rt.SetSlot(Val.AsHeap(@out), idx, rt.R(mi));
        rt.PopTo(@base);
        return @out;
    }
}
