// Generated by kin from the source named below. Do not edit.
// source: flint.rt.objsize

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Objhdr;

public static class Objsize {
    /// Which of the three shapes `ty` has.
    /// 
    /// SLOTS UNLESS NAMED OTHERWISE, and the default is the safe one: a type
    /// the allocator has not heard of is laid out as values, so the collector
    /// traces it. Defaulting to RAW would hide a new type's references from
    /// the collector, and the failure would be a freed live object rather than
    /// a wasted word.
    /// 
    /// A STRING IS ITS OWN SHAPE because its bytes do not begin where every
    /// other object's body does -- `STR_DATA` and not `HDR`.
    /// 
    /// THE RAW FIVE ARE THE ALLOCATOR'S OWN, three of which no guest ever
    /// sees: `TY_FREE` is a hole in the old space and `TY_FWD` an object that
    /// has moved. Both are walked by the sweeper, so both must size correctly
    /// or the walk steps into the middle of the next object.
    public static int LayoutOf(int ty) {
        if (ty == Obj.TyStr) {
            return Obj.LStr;
        }
        if ((ty == Obj.TyBigint) || ((ty == Obj.TyRaw) || ((ty == Obj.TyBytes) || ((ty == Obj.TyFree) || (ty == Obj.TyFwd))))) {
            return Obj.LRaw;
        }
        return Obj.LVals;
    }
    /// How many BYTES an object of `ty` with `len` occupies.
    /// 
    /// `len` MEANS DIFFERENT THINGS PER LAYOUT, which is the whole reason this
    /// is one function and not three call sites. For slots it is a COUNT and
    /// each is eight bytes wide; for the other two it is already a byte count.
    /// Reading it as bytes for a vector would size a ten-element vector at
    /// ten bytes and hand back an object the collector walks off the end of.
    /// 
    /// ONLY THE BYTE LAYOUTS ROUND. A slot count multiplied by eight is
    /// already a multiple of eight, so rounding it is a no-op that would only
    /// hide a mistake in the multiply; the two byte layouts round because a
    /// caller may ask for any length at all.
    /// 
    /// THE ANSWER IS BYTES AND THE CHARGE IS `>> 3`. The caller divides; this
    /// does not, because the sweeper walks in bytes and would step wrong on a
    /// size already divided.
    public static long SizeFor(int ty, int len) {
        int lay = LayoutOf(ty);
        // WIDENED BEFORE THE ARITHMETIC. A length is 32-bit and an
        // address is 64; Java and C# widen silently and Rust does not,
        // so the conversion is said here rather than left to whichever
        // target happens to tolerate it. Native's copy says `len as
        // Addr` in the same three places.
        if (lay == Obj.LVals) {
            return Obj.Hdr + (len * 8);
        }
        if (lay == Obj.LStr) {
            return Obj.Align8(Obj.StrData + len);
        }
        return Obj.Align8(Obj.Hdr + len);
    }
    /// How many bytes this object occupies, header included.
    /// 
    /// IN THIS FILE AND NOT `objhdr.kin`, which is where it was written
    /// first and where it did not compile: the generated module globs both
    /// the hand-written `Obj` and its own siblings, and `size-for` exists in
    /// BOTH -- once here and once as the delegator `Obj` keeps for its four
    /// callers. Two globs offering one name make it ambiguous rather than
    /// resolving it. Beside `size-for` the call is to a LOCAL definition,
    /// which shadows a glob on all three targets, and the two belong
    /// together anyway: they must agree for every type, since one measures
    /// a live object and the other reserves room for a new one.
    /// 
    /// TWO SPECIAL CASES AND THEN `size-for`, which is the point. This used to
    /// carry its own copy of the layout match, and a type added to `layout-of`
    /// but not to that copy was sized as `HDR + len * 8` -- a 513-byte
    /// `TY_BYTES` measured as 4112. The collector then walked from-space with
    /// the wrong stride and blamed an object that was perfectly fine. Deriving
    /// the size from one table removes the second one.
    /// 
    /// A FREE BLOCK'S LENGTH IS ITS SIZE IN BYTES, and it is the one length
    /// that can genuinely set the high bit -- which is why it is widened with
    /// `addr-of-u32` rather than `to-addr`. All three runtimes already did this
    /// by three different routes: `len as Addr`, `Integer.toUnsignedLong(len)`
    /// and `(uint) len`.
    public static long ObjSizeOf(Space sp, long addr) {
        int ty = ObjTy(sp, addr);
        int len = ObjLen(sp, addr);
        if (ty == Obj.TyFree) {
            return (long)(uint) len;
        }
        if (ty == Obj.TyFwd) {
            return Obj.Hdr;
        }
        return SizeFor(ty, len);
    }
}
