// Generated by kin from the source named below. Do not edit.
// source: flint.rt.opaque

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Opaque {
    /// A tagged form: a reader tag and the form it wrapped.
    public static long NewTagged(Rt rt, long tag, long form) {
        int @base = rt.Mark();
        int ti = rt.Push(tag);
        int fi = rt.Push(form);
        long v = Conc.NewObj(rt, Obj.TyTagged, 2);
        // `new-obj` AND NOT `alloc`: it answers NIL when the heap refused.
        // BOTH PORTS CHECKED AND RUST DID NOT -- Rust's `new_opaque`
        // checked and its `new_tagged` did not, so the odd one out was a
        // single function in a single runtime. A half-allocated tagged
        // form is worse than a refusal.
        if (Val.IsNil(v)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        // THE TAG AND THE FORM ARE RE-READ FROM THE ROOTS. The allocation
        // may have moved them, and 0031 says a value in a host local does
        // not survive one.
        rt.SetSlot(Val.AsHeap(v), 0, rt.R(ti));
        rt.SetSlot(Val.AsHeap(v), 1, rt.R(fi));
        rt.PopTo(@base);
        return v;
    }
    public static bool IsTagged(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        return Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyTagged;
    }
    /// An opaque value: a label, an identity, and the host's own id.
    /// 
    /// THE IDENTITY IS STORED, NOT DERIVED FROM THE ADDRESS. The nursery is a
    /// COPYING collector, so an address-derived hash would change under
    /// collection -- and a value in a map would stop being findable by the key
    /// that put it there. That is the whole reason there is a slot for it.
    public static long NewOpaque(Rt rt, long label, long hostId) {
        int @base = rt.Mark();
        int li = rt.Push(label);
        long v = Conc.NewObj(rt, Obj.TyOpaque, 3);
        if (Val.IsNil(v)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        long id = rt.TakeOpaqueId();
        rt.SetSlot(Val.AsHeap(v), 0, rt.R(li));
        rt.SetSlot(Val.AsHeap(v), 1, Val.Fixnum(id & 0xFFFFFFFFL));
        rt.SetSlot(Val.AsHeap(v), 2, Val.Fixnum(hostId & 0xFFFFFFFFL));
        rt.PopTo(@base);
        return v;
    }
    public static bool IsOpaque(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        return Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyOpaque;
    }
    /// The host's id, or 0 for a GUEST-MINTED value.
    /// 
    /// Not reachable from guest code -- there is no builtin that answers it. A
    /// host uses it to recognise its own.
    public static long OpaqueHostId(Rt rt, long v) {
        if (!IsOpaque(rt, v)) {
            return 0;
        }
        long s = rt.Slot(v, 2);
        if (!Val.IsFixnum(s)) {
            return 0;
        }
        return Val.AsFixnum(s);
    }
    /// The label, or nil.
    public static long OpaqueLabel(Rt rt, long v) {
        if (!IsOpaque(rt, v)) {
            return Val.Nil;
        }
        return rt.Slot(v, 0);
    }
}
