// Generated by kin from the source named below. Do not edit.
// source: flint.rt.portinstall

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Portmake;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;

public static class Portinstall {
    /// PUT A HOST PORT IN THIS SANDBOX, or hand back the one already here.
    /// 
    /// IDEMPOTENT BY ID. A host that installs the same id twice gets the SAME
    /// object and the host hears nothing the second time -- one `EV_RETAIN` per
    /// handle, or the host's count of holders stops meaning anything.
    /// 
    /// THE LABEL IS ROOTED BEFORE THE SCHEDULER IS BUILT. See the note at the
    /// top of this file: every runtime had these two the other way round, and
    /// it is a live rooting bug rather than a tidiness point. `ensure-sched` is
    /// a word precisely so this order can be stated ONCE.
    /// 
    /// A NEGATIVE ID IS REFUSED. Ids come from the host and -1 is the absent
    /// marker used throughout; minting a port for it would make `port-by-id`
    /// answer for a handle nobody holds.
    /// 
    /// ANNOUNCED ONLY WHEN ASKED. The system port is installed without an
    /// `EV_RETAIN` because the host did not ask for it -- it IS the host's end
    /// of the door, and telling it to hold something it already owns would
    /// leave a retain no release ever matches.
    public static long InstallBridgeAt(Rt rt, long hostId, long label, bool announce) {
        if (hostId < 0) {
            return Val.Nil;
        }
        int @base = rt.Mark();
        int li = rt.Push(label);
        // ROOTED FIRST, THEN THE SCHEDULER -- the whole point of this file.
        Conc.EnsureSched(rt);
        long existing = Conc.PortById(rt, hostId);
        if (!Val.IsNil(existing) && (Val.AsFixnum(rt.Slot(existing, Conc.PT_KIND)) == Conc.K_BRIDGE)) {
            rt.PopTo(@base);
            return existing;
        }
        long p = NewPortAt(rt, Conc.DEFAULT_BRIDGE_CAP, rt.R(li), Conc.K_BRIDGE, Conc.P_OPEN, hostId);
        if (Val.IsNil(p)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        int pi = rt.Push(p);
        int si = rt.Push(Conc.Sched(rt));
        // RECORDED AS HELD, which is what `reap-all` walks to notice
        // that the script has let the handle go.
        int bi = rt.Push(rt.Slot(rt.R(si), Conc.SC_BRIDGES));
        long nb = VecConj(rt, rt.R(bi), Val.Fixnum(hostId));
        rt.SetSlot(Val.AsHeap(rt.R(si)), Conc.SC_BRIDGES, nb);
        if (announce) {
            Conc.PushEvent(rt, Conc.EV_RETAIN, hostId, 0, Val.Nil);
        }
        long @out = rt.R(pi);
        rt.PopTo(@base);
        return @out;
    }
    /// INSTALL THE SYSTEM PORT: the one the control plane parks on.
    /// 
    /// NOT ANNOUNCED. It is the host's own end of the door rather than a handle
    /// the host asked for, so a retain here would never be matched.
    /// 
    /// RECORDED IN `SC_SYSTEM` so `drive` can find it without a search -- it is
    /// consulted on every iteration.
    public static long InstallSystemAt(Rt rt, long hostId, long label) {
        long p = InstallBridgeAt(rt, hostId, label, false);
        if (Val.IsNil(p)) {
            return Val.Nil;
        }
        int @base = rt.Mark();
        int pi = rt.Push(p);
        int si = rt.Push(Conc.Sched(rt));
        rt.SetSlot(Val.AsHeap(rt.R(si)), Conc.SC_SYSTEM, rt.R(pi));
        long @out = rt.R(pi);
        rt.PopTo(@base);
        return @out;
    }
}
