// Generated by kin from the source named below. Do not edit.
// source: flint.rt.readsq

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Codepoints;
using static global::_3sln.Flint.Kgen.Rt.Collvec;
using static global::_3sln.Flint.Kgen.Rt.Dblstr;
using static global::_3sln.Flint.Kgen.Rt.Mapcore;
using static global::_3sln.Flint.Kgen.Rt.Mapread;
using static global::_3sln.Flint.Kgen.Rt.Mapwrite;
using static global::_3sln.Flint.Kgen.Rt.Names;
using static global::_3sln.Flint.Kgen.Rt.Numkind;
using static global::_3sln.Flint.Kgen.Rt.Readconst;
using static global::_3sln.Flint.Kgen.Rt.Readcore;
using static global::_3sln.Flint.Kgen.Rt.Ropecmp;
using static global::_3sln.Flint.Kgen.Rt.Ropeflat;
using static global::_3sln.Flint.Kgen.Rt.Ropemeas;
using static global::_3sln.Flint.Kgen.Rt.Seqcore;
using static global::_3sln.Flint.Kgen.Rt.Seqwalk;
using static global::_3sln.Flint.Kgen.Rt.Setcore;
using static global::_3sln.Flint.Kgen.Rt.Vecread;

public static class Readsq {
    /// Replace the `n` values rooted at `base` with ONE: the list of them.
    public static void CollapseList(Rt rt, int @base, int n) {
        long l = ListFromRoots(rt, @base, n);
        rt.PopTo(@base);
        rt.Push(l);
    }
    /// Insertion-sort the `n` strings rooted at `base` in UTF-16 order --
    /// STABLE, as the guest's `sort` is.
    public static void SortRoots(Rt rt, int @base, int n) {
        int i;
        i = 1;
        while (i < n) {
            int j;
            j = i;
            for (;;) {
                if (j == 0) {
                    break;
                }
                long a = rt.R(@base + (j - 1));
                long b = rt.R(@base + j);
                int c = StrCmp(rt, a, b);
                if (c <= 0) {
                    break;
                }
                long lo = rt.R(@base + (j - 1));
                long hi = rt.R(@base + j);
                rt.SetR(@base + (j - 1), hi);
                rt.SetR(@base + j, lo);
                j -= 1;
            }
            i += 1;
        }
    }
    /// Append a name's namespace (empty for none), a slash and its name.
    internal static void CkeyName(Rt rt, int sk, long v) {
        int @base = rt.Mark();
        int vi = rt.Push(v);
        long nsv = NsOf(rt, rt.R(vi));
        if (!Val.IsNil(nsv)) {
            SAppend(rt, nsv, sk);
        }
        rt.SinkPut(sk, 47);
        long nm = NameOf(rt, rt.R(vi));
        SAppend(rt, nm, sk);
        rt.PopTo(@base);
    }
    /// The elements of the vector `xs`, each keyed and followed by the
    /// separator; SORTED when `sorted`, which is a set's.
    internal static void CkeyElements(Rt rt, int sk, long xs, bool sorted) {
        int @base = rt.Mark();
        int xi = rt.Push(xs);
        int n = VecCount(rt, rt.R(xi));
        int at = @base + 1;
        for (int i = 0; i < n; i++) {
            int ek = rt.SinkOpen();
            CkeyPut(rt, ek, VecNth(rt, rt.R(xi), i, Val.Nil));
            rt.SinkPut(ek, 31);
            long one = rt.SinkString(ek);
            rt.SinkClose(ek);
            rt.Push(one);
        }
        if (sorted) {
            SortRoots(rt, at, n);
        }
        for (int k = 0; k < n; k++) {
            SAppend(rt, rt.R(at + k), sk);
        }
        rt.PopTo(@base);
    }
    /// A map's entries, each as `key SEP value SEP`, sorted.
    internal static void CkeyMap(Rt rt, int sk, long m) {
        int @base = rt.Mark();
        long ev = MapEntryVector(rt, m);
        int evi = rt.Push(ev);
        int n = VecCount(rt, rt.R(evi));
        int at = @base + 1;
        for (int i = 0; i < n; i++) {
            long e = VecNth(rt, rt.R(evi), i, Val.Nil);
            int ei = rt.Push(e);
            int ek = rt.SinkOpen();
            CkeyPut(rt, ek, rt.Slot(rt.R(ei), 0));
            rt.SinkPut(ek, 31);
            CkeyPut(rt, ek, rt.Slot(rt.R(ei), 1));
            rt.SinkPut(ek, 31);
            long one = rt.SinkString(ek);
            rt.SinkClose(ek);
            rt.SetR(ei, one);
        }
        SortRoots(rt, at, n);
        for (int k = 0; k < n; k++) {
            SAppend(rt, rt.R(at + k), sk);
        }
        rt.PopTo(@base);
    }
    /// Append `flint.canon/ckey` of `v`.
    public static void CkeyPut(Rt rt, int sk, long v) {
        if (Val.IsNil(v)) {
            rt.SinkPut(sk, 48);
            return;
        }
        if (v == Val.True) {
            rt.SinkPut(sk, 49);
            rt.SinkPut(sk, 116);
            return;
        }
        if (v == Val.False) {
            rt.SinkPut(sk, 49);
            rt.SinkPut(sk, 102);
            return;
        }
        if (IsInt(rt, v)) {
            long t = NumToStr(rt, v);
            rt.SinkPut(sk, 50);
            SAppend(rt, t, sk);
            return;
        }
        if (Val.IsDouble(v)) {
            long bits = System.BitConverter.DoubleToInt64Bits(Num.F64(rt, v));
            rt.SinkPut(sk, 51);
            if (bits < 0) {
                rt.SinkPut(sk, 45);
                // The most negative bit pattern has no positive
                // counterpart, so it is spelled rather than negated.
                if (bits == long.MinValue) {
                    MsgLit(rt, sk, "9223372036854775808");
                } else {
                    MsgInt(rt, sk, 0 - bits);
                }
            } else {
                MsgInt(rt, sk, bits);
            }
            return;
        }
        if (IsString(rt, v)) {
            rt.SinkPut(sk, 52);
            SAppend(rt, v, sk);
            return;
        }
        if (IsKeyword(rt, v)) {
            rt.SinkPut(sk, 53);
            CkeyName(rt, sk, v);
            return;
        }
        if (IsSymbol(rt, v)) {
            rt.SinkPut(sk, 54);
            CkeyName(rt, sk, v);
            return;
        }
        if (IsVectorLike(rt, v)) {
            rt.SinkPut(sk, 55);
            CkeyElements(rt, sk, v, false);
            return;
        }
        if (IsSet(rt, v)) {
            long xs = SetElementVector(rt, v);
            rt.SinkPut(sk, 56);
            CkeyElements(rt, sk, xs, true);
            return;
        }
        if (IsMap(rt, v)) {
            rt.SinkPut(sk, 57);
            CkeyMap(rt, sk, v);
            return;
        }
        if (IsSeq(rt, v)) {
            int @base = rt.Mark();
            long s0 = Seq(rt, v);
            int si = rt.Push(s0);
            rt.SinkPut(sk, 97);
            for (;;) {
                if (Val.IsNil(rt.R(si))) {
                    break;
                }
                long x = First(rt, rt.R(si));
                CkeyPut(rt, sk, x);
                rt.SinkPut(sk, 31);
                long nx = Next(rt, rt.R(si));
                rt.SetR(si, nx);
            }
            rt.PopTo(@base);
            return;
        }
        // Only a tagged literal reaches here, and syntax quote refuses the
        // one kind the reader makes (`deferred-guard`); its printing is not
        // reproduced.
        rt.SinkPut(sk, 122);
    }
    /// Is `f` the list `(head x ..)` for the symbol `ns`/`nm`?
    internal static bool Headed(Rt rt, long f, string ns, string nm) {
        if (!IsSeq(rt, f)) {
            return false;
        }
        long h = First(rt, f);
        return IsSym2(rt, h, ns, nm);
    }
    /// The second element of the seq `f`, or nil.
    internal static long SecondOf(Rt rt, long f) {
        long nx = Next(rt, f);
        if (Val.IsNil(nx)) {
            return Val.Nil;
        }
        return First(rt, nx);
    }
    /// Is `sym` one of the special forms syntax quote leaves unqualified,
    /// exactly as Clojure does?
    internal static bool IsSpecial(Rt rt, long sym) {
        if (IsSym1(rt, sym, "if")) {
            return true;
        }
        if (IsSym1(rt, sym, "do")) {
            return true;
        }
        if (IsSym1(rt, sym, "let*")) {
            return true;
        }
        if (IsSym1(rt, sym, "loop*")) {
            return true;
        }
        if (IsSym1(rt, sym, "recur")) {
            return true;
        }
        if (IsSym1(rt, sym, "fn*")) {
            return true;
        }
        if (IsSym1(rt, sym, "quote")) {
            return true;
        }
        if (IsSym1(rt, sym, "var")) {
            return true;
        }
        if (IsSym1(rt, sym, "throw")) {
            return true;
        }
        if (IsSym1(rt, sym, "try")) {
            return true;
        }
        if (IsSym1(rt, sym, "catch")) {
            return true;
        }
        if (IsSym1(rt, sym, "finally")) {
            return true;
        }
        if (IsSym1(rt, sym, "def")) {
            return true;
        }
        if (IsSym1(rt, sym, "new")) {
            return true;
        }
        if (IsSym1(rt, sym, "set!")) {
            return true;
        }
        if (IsSym1(rt, sym, ".")) {
            return true;
        }
        if (IsSym1(rt, sym, "&")) {
            return true;
        }
        if (IsSym1(rt, sym, "monitor-enter")) {
            return true;
        }
        if (IsSym1(rt, sym, "monitor-exit")) {
            return true;
        }
        if (IsSym1(rt, sym, "deftype*")) {
            return true;
        }
        if (IsSym1(rt, sym, "reify*")) {
            return true;
        }
        if (IsSym1(rt, sym, "case*")) {
            return true;
        }
        if (IsSym1(rt, sym, "letfn*")) {
            return true;
        }
        if (IsSym1(rt, sym, "ns")) {
            return true;
        }
        return false;
    }
    /// Push `(head x)` for the symbol `ns`/`nm` -- nil for no namespace -- and
    /// the value rooted at `xi`.
    internal static void PushPair(Rt rt, long head, int xi) {
        int @base = rt.Mark();
        rt.Push(head);
        rt.Push(rt.R(xi));
        CollapseList(rt, @base, 2);
    }
    /// A symbol inside syntax quote, pushed: `(quote sym)` for a `.method` or a
    /// special form, and otherwise `(flint.reader/syntax-quoted sym)` for the
    /// analyzer.
    internal static int SqSymbol(Rt rt, int sti, int fi) {
        long nm = NameOf(rt, rt.R(fi));
        int c = CodePoints(rt, nm);
        bool dotted = (rt.CpsLen(c) > 0) && (rt.CpsAt(c, 0) == 46);
        rt.CpsClose(c);
        if ((Val.IsNil(NsOf(rt, rt.R(fi))) && dotted) || IsSpecial(rt, rt.R(fi))) {
            long q = LitSymbol1(rt, "quote");
            PushPair(rt, q, fi);
            return RsOk;
        }
        long sq = LitSymbol(rt, "flint.reader", "syntax-quoted");
        PushPair(rt, sq, fi);
        return RsOk;
    }
    /// An auto-gensym `x#`, pushed as `(quote x__N)`: one name per syntax-quote
    /// form, the same name for every `x#` in it.
    internal static int SqGensym(Rt rt, int sti, int fi) {
        long g = RdGet(rt, sti, RdsGensyms);
        if (Val.IsNil(g)) {
            return RdFailLit(rt, sti, "an auto-gensym inside a syntax quote nested in another cannot be read");
        }
        long hit = MapGet(rt, g, rt.R(fi), Val.NotFound);
        if (hit != Val.NotFound) {
            int hbase = rt.Mark();
            int hi = rt.Push(hit);
            long hq = LitSymbol1(rt, "quote");
            PushPair(rt, hq, hi);
            long hdone = rt.R(hbase + 1);
            rt.PopTo(hbase);
            rt.Push(hdone);
            return RsOk;
        }
        int @base = rt.Mark();
        long nm = NameOf(rt, rt.R(fi));
        int c = CodePoints(rt, nm);
        int n = rt.CpsLen(c);
        int sk = rt.SinkOpen();
        for (int i = 0; i < n - 1; i++) {
            SinkPutCp(rt, sk, rt.CpsAt(c, i));
        }
        rt.CpsClose(c);
        rt.SinkPut(sk, 95);
        rt.SinkPut(sk, 95);
        long k = RdInt(rt, sti, RdsGensymN);
        MsgInt(rt, sk, k);
        RdSetInt(rt, sti, RdsGensymN, k + 1);
        long text = rt.SinkString(sk);
        rt.SinkClose(sk);
        long s = global::Flint.Rt.Str.SymbolOf(rt, Val.Nil, text);
        int si = rt.Push(s);
        long g2 = MapAssoc(rt, RdGet(rt, sti, RdsGensyms), rt.R(fi), rt.R(si));
        RdPut(rt, sti, RdsGensyms, g2);
        long q = LitSymbol1(rt, "quote");
        PushPair(rt, q, si);
        long done = rt.R(@base + 1);
        rt.PopTo(@base);
        rt.Push(done);
        return RsOk;
    }
    /// `sq-expand-seq` over the values rooted at `at`..`at + n`: each item
    /// pushed in turn, `(clojure.core/list x)` for an unquote, the form itself
    /// for an unquote-splicing, and `(clojure.core/list <sq-form>)` otherwise.
    /// Then the whole run is replaced by `(clojure.core/concat ..)` with them.
    internal static int SqExpand(Rt rt, int sti, int at, int n) {
        int @out = rt.Mark();
        long cc = LitSymbol(rt, "clojure.core", "concat");
        rt.Push(cc);
        for (int i = 0; i < n; i++) {
            int ii = at + i;
            if (Headed(rt, rt.R(ii), "clojure.core", "unquote")) {
                long l = LitSymbol(rt, "clojure.core", "list");
                int li = rt.Push(l);
                long x = SecondOf(rt, rt.R(ii));
                rt.Push(x);
                CollapseList(rt, li, 2);
            } else if (Headed(rt, rt.R(ii), "clojure.core", "unquote-splicing")) {
                long xs = SecondOf(rt, rt.R(ii));
                rt.Push(xs);
            } else {
                long l2 = LitSymbol(rt, "clojure.core", "list");
                int l2i = rt.Push(l2);
                int st = SqForm(rt, sti, ii);
                if (st != RsOk) {
                    rt.PopTo(@out);
                    return st;
                }
                CollapseList(rt, l2i, 2);
            }
        }
        CollapseList(rt, @out, n + 1);
        return RsOk;
    }
    /// Push the seq rooted at `fi`'s elements, answering how many.
    internal static int PushSeq(Rt rt, int fi) {
        int n;
        n = 0;
        long s0 = Seq(rt, rt.R(fi));
        int si = rt.Push(s0);
        for (;;) {
            if (Val.IsNil(rt.R(si))) {
                break;
            }
            long x = First(rt, rt.R(si));
            rt.Push(x);
            n += 1;
            // The seq's slot is BELOW the elements just pushed, so it is
            // re-read through its root.
            long nx = Next(rt, rt.R(si));
            rt.SetR(si, nx);
        }
        return n;
    }
    /// Push the elements of the vector `v` (rooted at `vi`), answering how many.
    internal static int PushVec(Rt rt, int vi) {
        int n = VecCount(rt, rt.R(vi));
        for (int i = 0; i < n; i++) {
            long x = VecNth(rt, rt.R(vi), i, Val.Nil);
            rt.Push(x);
        }
        return n;
    }
    /// Wrap what `sq-expand` left on the stack at `at` in `(head <concat>)`
    /// and move the result down to `base`.
    internal static void WrapAt(Rt rt, int @base, int at, long head) {
        int hi = rt.Push(head);
        long body = rt.R(at);
        // `(head body)`: the head was pushed AFTER the body, so the two
        // are pushed again in order.
        rt.Push(rt.R(hi));
        rt.Push(body);
        CollapseList(rt, hi + 1, 2);
        long done = rt.R(hi + 1);
        rt.PopTo(@base);
        rt.Push(done);
    }
    /// Syntax quote of the form rooted at `fi`, pushed.
    public static int SqForm(Rt rt, int sti, int fi) {
        int @base = rt.Mark();
        if (Headed(rt, rt.R(fi), "clojure.core", "unquote")) {
            long x = SecondOf(rt, rt.R(fi));
            rt.Push(x);
            return RsOk;
        }
        if (IsSymbol(rt, rt.R(fi))) {
            long nm = NameOf(rt, rt.R(fi));
            int c = CodePoints(rt, nm);
            int n = rt.CpsLen(c);
            bool hashed = (n > 0) && (rt.CpsAt(c, n - 1) == 35);
            rt.CpsClose(c);
            if (hashed) {
                return SqGensym(rt, sti, fi);
            }
            return SqSymbol(rt, sti, fi);
        }
        if (Headed(rt, rt.R(fi), "flint.reader", "syntax-quoted")) {
            long q = LitSymbol1(rt, "quote");
            int qi = rt.Push(q);
            long x = SecondOf(rt, rt.R(fi));
            rt.Push(x);
            CollapseList(rt, qi, 2);
            int st = SqForm(rt, sti, qi);
            if (st != RsOk) {
                rt.PopTo(@base);
                return st;
            }
            long done = rt.R(qi + 1);
            rt.PopTo(@base);
            rt.Push(done);
            return RsOk;
        }
        if (IsSeq(rt, rt.R(fi))) {
            int n = PushSeq(rt, fi);
            if (n == 0) {
                long l = LitSymbol(rt, "clojure.core", "list");
                rt.PopTo(@base);
                rt.Push(l);
                CollapseList(rt, @base, 1);
                return RsOk;
            }
            int at = @base + 1;
            int st = SqExpand(rt, sti, at, n);
            if (st != RsOk) {
                rt.PopTo(@base);
                return st;
            }
            long h = LitSymbol(rt, "clojure.core", "seq");
            WrapAt(rt, @base, at + n, h);
            return RsOk;
        }
        if (IsVectorLike(rt, rt.R(fi))) {
            int vn = PushVec(rt, fi);
            int vat = @base;
            int vst = SqExpand(rt, sti, vat, vn);
            if (vst != RsOk) {
                rt.PopTo(@base);
                return vst;
            }
            long vh = LitSymbol(rt, "clojure.core", "vec");
            WrapAt(rt, @base, vat + vn, vh);
            return RsOk;
        }
        if (IsSet(rt, rt.R(fi))) {
            long xs = SetElementVector(rt, rt.R(fi));
            int xsi = rt.Push(xs);
            int sn = PushVec(rt, xsi);
            int sat = @base + 1;
            int sst = SqExpand(rt, sti, sat, sn);
            if (sst != RsOk) {
                rt.PopTo(@base);
                return sst;
            }
            long sh = LitSymbol(rt, "clojure.core", "set");
            WrapAt(rt, @base, sat + sn, sh);
            return RsOk;
        }
        // A MAP, SORTED BY THE CANONICAL KEY: each entry's key string is
        // sorted with the entry's index beside it, and the entries are
        // then read back in that order and flattened.
        if (IsMap(rt, rt.R(fi))) {
            long ev = MapEntryVector(rt, rt.R(fi));
            int evi = rt.Push(ev);
            int mn = VecCount(rt, rt.R(evi));
            int keys = rt.Mark();
            for (int i = 0; i < mn; i++) {
                long e = VecNth(rt, rt.R(evi), i, Val.Nil);
                int ei = rt.Push(e);
                int ek = rt.SinkOpen();
                CkeyPut(rt, ek, rt.Slot(rt.R(ei), 0));
                rt.SinkPut(ek, 31);
                CkeyPut(rt, ek, rt.Slot(rt.R(ei), 1));
                long ks = rt.SinkString(ek);
                rt.SinkClose(ek);
                rt.SetR(ei, ks);
            }
            // Sort the key strings and carry each entry's index beside it:
            // the entries vector is read back by the index afterwards.
            int idx = rt.Mark();
            for (int j = 0; j < mn; j++) {
                rt.Push(Val.Fixnum(j & 0xFFFFFFFFL));
            }
            // Insertion sort of `keys` with `idx` moved alongside.
            int a;
            a = 1;
            while (a < mn) {
                int b;
                b = a;
                for (;;) {
                    if (b == 0) {
                        break;
                    }
                    int p = keys + (b - 1);
                    int q = keys + b;
                    int cmpv = StrCmp(rt, rt.R(p), rt.R(q));
                    if (cmpv <= 0) {
                        break;
                    }
                    long kp = rt.R(p);
                    long kq = rt.R(q);
                    long ip = rt.R(idx + (b - 1));
                    long iq = rt.R(idx + b);
                    rt.SetR(p, kq);
                    rt.SetR(q, kp);
                    rt.SetR(idx + (b - 1), iq);
                    rt.SetR(idx + b, ip);
                    b -= 1;
                }
                a += 1;
            }
            int flat = rt.Mark();
            for (int k = 0; k < mn; k++) {
                int which = (int) Val.AsFixnum(rt.R(idx + k));
                long e2 = VecNth(rt, rt.R(evi), which, Val.Nil);
                int e2i = rt.Push(e2);
                long kk = rt.Slot(rt.R(e2i), 0);
                rt.SetR(e2i, kk);
                long vv = rt.Slot(VecNth(rt, rt.R(evi), which, Val.Nil), 1);
                rt.Push(vv);
            }
            int mst = SqExpand(rt, sti, flat, 2 * mn);
            if (mst != RsOk) {
                rt.PopTo(@base);
                return mst;
            }
            // `(clojure.core/apply clojure.core/hash-map <concat>)`.
            long body = rt.R(flat + (2 * mn));
            int bi = rt.Push(body);
            int three = rt.Mark();
            long ap = LitSymbol(rt, "clojure.core", "apply");
            rt.Push(ap);
            long hm = LitSymbol(rt, "clojure.core", "hash-map");
            rt.Push(hm);
            rt.Push(rt.R(bi));
            CollapseList(rt, three, 3);
            long done = rt.R(three);
            rt.PopTo(@base);
            rt.Push(done);
            return RsOk;
        }
        rt.Push(rt.R(fi));
        return RsOk;
    }
}
