// Generated by kin from the source named below. Do not edit.
// source: flint.rt.readform

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Codepoints;
using static global::_3sln.Flint.Kgen.Rt.Collvec;
using static global::_3sln.Flint.Kgen.Rt.Mapcore;
using static global::_3sln.Flint.Kgen.Rt.Mapmake;
using static global::_3sln.Flint.Kgen.Rt.Mapread;
using static global::_3sln.Flint.Kgen.Rt.Mapwrite;
using static global::_3sln.Flint.Kgen.Rt.Meta;
using static global::_3sln.Flint.Kgen.Rt.Names;
using static global::_3sln.Flint.Kgen.Rt.Opaque;
using static global::_3sln.Flint.Kgen.Rt.Readconst;
using static global::_3sln.Flint.Kgen.Rt.Readcore;
using static global::_3sln.Flint.Kgen.Rt.Readnum;
using static global::_3sln.Flint.Kgen.Rt.Readsq;
using static global::_3sln.Flint.Kgen.Rt.Readtext;
using static global::_3sln.Flint.Kgen.Rt.Ropecmp;
using static global::_3sln.Flint.Kgen.Rt.Ropemeas;
using static global::_3sln.Flint.Kgen.Rt.Seqcore;
using static global::_3sln.Flint.Kgen.Rt.Seqwalk;
using static global::_3sln.Flint.Kgen.Rt.Setcore;
using static global::_3sln.Flint.Kgen.Rt.Transients;
using static global::_3sln.Flint.Kgen.Rt.Valeq;
using static global::_3sln.Flint.Kgen.Rt.Vecassoc;
using static global::_3sln.Flint.Kgen.Rt.Vecread;
using static global::_3sln.Flint.Kgen.Rt.Vecroots;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;

public static class Readform {
    /// Is `v` something metadata can sit on -- a symbol or a collection?
    public static bool MetaAble(Rt rt, long v) {
        return IsSymbol(rt, v) || (IsVectorLike(rt, v) || (IsMap(rt, v) || (IsSet(rt, v) || IsSeq(rt, v))));
    }
    /// Replace the value rooted at `vi` with `(list head v)`.
    internal static void WrapRoot(Rt rt, int vi, long head) {
        int hi = rt.Push(head);
        rt.Push(rt.R(hi));
        rt.Push(rt.R(vi));
        long l = ListFromRoots(rt, hi + 1, 2);
        rt.PopTo(hi);
        rt.SetR(vi, l);
    }
    /// `(merge a b c)` as the guest's `merge` does it: the nils dropped, the
    /// first made TRANSIENT -- which promotes it to a CHAMP -- and every later
    /// map's entries `assoc!`ed in the order that map visits them. The three
    /// are rooted at `ai`, `bi`, `ci`; the answer is pushed.
    public static void Merge3(Rt rt, int ai, int bi, int ci) {
        int @base = rt.Mark();
        int firsti;
        firsti = ai;
        int skip;
        skip = 0;
        if (Val.IsNil(rt.R(ai))) {
            if (Val.IsNil(rt.R(bi))) {
                firsti = ci;
                skip = 2;
            } else {
                firsti = bi;
                skip = 1;
            }
        }
        if (Val.IsNil(rt.R(firsti))) {
            rt.Push(Val.Nil);
            return;
        }
        long t0 = ToTransient(rt, rt.R(firsti));
        int ti = rt.Push(t0);
        for (int w = 0; w < 3; w++) {
            if (w > skip) {
                int mi;
                mi = ai;
                if (w == 1) {
                    mi = bi;
                }
                if (w == 2) {
                    mi = ci;
                }
                if (!Val.IsNil(rt.R(mi))) {
                    long ev = MapEntryVector(rt, rt.R(mi));
                    int evi = rt.Push(ev);
                    int n = VecCount(rt, rt.R(evi));
                    for (int i = 0; i < n; i++) {
                        long e = VecNth(rt, rt.R(evi), i, Val.Nil);
                        int ei = rt.Push(e);
                        long t2 = TransientAssoc(rt, rt.R(ti), rt.Slot(rt.R(ei), 0), rt.Slot(rt.R(ei), 1));
                        rt.SetR(ti, t2);
                        rt.PopTo(ei);
                    }
                    rt.PopTo(evi);
                }
            }
        }
        long @out = ToPersistent(rt, rt.R(ti));
        rt.PopTo(@base);
        rt.Push(@out);
    }
    /// Push `{:line l :column c :file f}` built as a map LITERAL is: assoc
    /// after assoc onto the empty map, which stays an array map in that order.
    public static void PushPosLiteral(Rt rt, int sti, long line, long col) {
        int @base = rt.Mark();
        long e = global::Flint.Rt.Maps.Empty(rt);
        int mi = rt.Push(e);
        long kl = LitKeyword1(rt, "line");
        long m1 = MapAssoc(rt, rt.R(mi), kl, Val.Fixnum(line));
        rt.SetR(mi, m1);
        long kc = LitKeyword1(rt, "column");
        long m2 = MapAssoc(rt, rt.R(mi), kc, Val.Fixnum(col));
        rt.SetR(mi, m2);
        long kf = LitKeyword1(rt, "file");
        long m3 = MapAssoc(rt, rt.R(mi), kf, RdGet(rt, sti, RdsFile));
        rt.SetR(mi, m3);
        long @out = rt.R(mi);
        rt.PopTo(@base);
        rt.Push(@out);
    }
    /// `flint.reader/position-meta`: the metadata a form at `line`/`col` gets,
    /// with the children's positions `cp` (rooted at `cpi`, nil or a vector) and
    /// the form's existing metadata (rooted at `xi`). Pushed.
    public static void PushPositionMeta(Rt rt, int sti, long line, long col, int cpi, int xi) {
        int @base = rt.Mark();
        PushPosLiteral(rt, sti, line, col);
        // `(when (seq children) {:child-pos children})`.
        bool hasCp;
        hasCp = false;
        if (!Val.IsNil(rt.R(cpi))) {
            if (VecCount(rt, rt.R(cpi)) > 0) {
                hasCp = true;
            }
        }
        if (hasCp) {
            long e = global::Flint.Rt.Maps.Empty(rt);
            int ci = rt.Push(e);
            long k = LitKeyword1(rt, "child-pos");
            long m = MapAssoc(rt, rt.R(ci), k, rt.R(cpi));
            rt.SetR(ci, m);
        } else {
            rt.Push(Val.Nil);
        }
        Merge3(rt, @base, @base + 1, xi);
        long @out = rt.R(@base + 2);
        rt.PopTo(@base);
        rt.Push(@out);
    }
    /// `stamp`: the value rooted at `vi`, if it can carry metadata, gets its
    /// position over whatever it already has -- A POSITION ALREADY THERE WINS,
    /// because the existing map is merged last. `cp` is rooted at `cpi`.
    public static void StampRoot(Rt rt, int sti, int vi, long line, long col, int cpi) {
        if (!MetaAble(rt, rt.R(vi))) {
            return;
        }
        int @base = rt.Mark();
        long ex = MetaOf(rt, rt.R(vi));
        int xi = rt.Push(ex);
        PushPositionMeta(rt, sti, line, col, cpi, xi);
        long @out = WithMeta(rt, rt.R(vi), rt.R(@base + 1));
        rt.PopTo(@base);
        rt.SetR(vi, @out);
    }
    /// Stamp the value rooted at `vi` with the child positions in the stash
    /// when `with-cp`, or none.
    internal static void StampStash(Rt rt, int sti, int vi, long line, long col, bool withCp) {
        int @base = rt.Mark();
        if (withCp) {
            rt.Push(RdGet(rt, sti, RdsChildpos));
        } else {
            rt.Push(Val.Nil);
        }
        StampRoot(rt, sti, vi, line, col, @base);
        rt.PopTo(@base);
    }
    /// Is `x` a reader conditional a deferred read left as data?
    public static bool IsConditional(Rt rt, long x) {
        if (!IsTagged(rt, x)) {
            return false;
        }
        return IsSym2(rt, rt.Slot(x, 0), "flint.reader", "#?");
    }
    /// Push the conditional node `#flint.reader/#? [kind line col cp items]`,
    /// counting it. `cpi` and `itemsi` are rooted; `kind` is the keyword's name.
    internal static void PushConditional(Rt rt, int sti, string kind, long line, long col, int cpi, int itemsi) {
        long nc = RdInt(rt, sti, RdsConds) + 1;
        RdSetInt(rt, sti, RdsConds, nc);
        int @base = rt.Mark();
        long k = LitKeyword1(rt, kind);
        rt.Push(k);
        rt.Push(Val.Fixnum(line));
        rt.Push(Val.Fixnum(col));
        rt.Push(rt.R(cpi));
        rt.Push(rt.R(itemsi));
        long form = VecFromRoots(rt, @base, 5);
        int fi = rt.Push(form);
        long tag = LitSymbol(rt, "flint.reader", "#?");
        long node = NewTagged(rt, tag, rt.R(fi));
        rt.PopTo(@base);
        rt.Push(node);
    }
    /// Refuse a conditional read inside a context that consumes its contents
    /// as it reads, when the features are not known. `n0` is the count when
    /// the context began.
    internal static int DeferredGuard(Rt rt, int sti, long n0, string what) {
        if (RdFlag(rt, sti, RdsDefer) && (n0 != RdInt(rt, sti, RdsConds))) {
            int sk = rt.SinkOpen();
            MsgLit(rt, sk, "a reader conditional inside ");
            MsgLit(rt, sk, what);
            MsgLit(rt, sk, " cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
            return RdFailSink(rt, sti, sk);
        }
        return RsOk;
    }
    /// The elements up to `closer`, at the opening character.
    /// 
    /// On `RS_OK` this has pushed ONE MORE value than there are elements: a
    /// placeholder, then the elements, so they are `(base + 1, n)` for the
    /// caller's `base` -- and it has written the elements' positions, as a flat
    /// `[line col ..]`, to the stash. A splice's elements each get the SPLICE's
    /// position: they were all written at `#?@`.
    public static int ReadDelimited(Rt rt, int sti, int closer) {
        RdNext(rt, sti);
        int @base = rt.Mark();
        long e = Vec.Empty(rt);
        int pi = rt.Push(e);
        for (;;) {
            RdSkipWs(rt, sti);
            int c = RdPeek(rt, sti);
            long cl = RdInt(rt, sti, RdsLine);
            long cc = RdInt(rt, sti, RdsCol);
            if (c == NoCp) {
                int sk = rt.SinkOpen();
                MsgLit(rt, sk, "unterminated, expecting ");
                SinkPutCp(rt, sk, closer);
                rt.PopTo(@base);
                return RdFailSink(rt, sti, sk);
            }
            if (c == closer) {
                RdNext(rt, sti);
                RdPut(rt, sti, RdsChildpos, rt.R(pi));
                return RsOk;
            }
            int at = rt.Mark();
            int st = ReadOne(rt, sti);
            if (st == RsErr) {
                rt.PopTo(@base);
                return RsErr;
            }
            if (st == RsOk) {
                long p1 = VecConj(rt, rt.R(pi), Val.Fixnum(cl));
                int p1i = rt.Push(p1);
                long p2 = VecConj(rt, rt.R(p1i), Val.Fixnum(cc));
                rt.SetR(pi, p2);
                rt.PopTo(p1i);
            }
            // A SPLICE: the spliced collection is on top, walked into
            // roots above it, then moved down over it.
            if (st == RsSplice) {
                long s0 = Seq(rt, rt.R(at));
                int si = rt.Push(s0);
                int xs = rt.Mark();
                int n;
                n = 0;
                for (;;) {
                    if (Val.IsNil(rt.R(si))) {
                        break;
                    }
                    long x = First(rt, rt.R(si));
                    rt.Push(x);
                    n += 1;
                    long nx = Next(rt, rt.R(si));
                    rt.SetR(si, nx);
                }
                for (int k = 0; k < n; k++) {
                    rt.SetR(at + k, rt.R(xs + k));
                    long q1 = VecConj(rt, rt.R(pi), Val.Fixnum(cl));
                    int q1i = rt.Push(q1);
                    long q2 = VecConj(rt, rt.R(q1i), Val.Fixnum(cc));
                    rt.SetR(pi, q2);
                    rt.PopTo(q1i);
                }
                rt.PopTo(at + n);
            }
        }
    }
    /// How many elements `read-delimited` left above `base`.
    internal static int DelimitedCount(Rt rt, int @base) {
        return (int) ((rt.Mark() - @base) - 1);
    }
    /// `^meta form`, at the caret.
    internal static int ReadMeta(Rt rt, int sti) {
        RdNext(rt, sti);
        RdSkipWs(rt, sti);
        int @base = rt.Mark();
        int st = ReadOne(rt, sti);
        if (st == RsErr) {
            return RsErr;
        }
        if (st != RsOk) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "metadata must be a symbol, keyword, string or map");
        }
        if (IsConditional(rt, rt.R(@base))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "metadata that is itself a reader conditional cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
        }
        // THE METADATA AS A MAP: `{m true}` for a keyword, `{:tag m}` for
        // a symbol or string, a map as it is.
        if (IsKeyword(rt, rt.R(@base))) {
            long e = global::Flint.Rt.Maps.Empty(rt);
            long m = MapAssoc(rt, e, rt.R(@base), Val.True);
            rt.SetR(@base, m);
        } else if (IsSymbol(rt, rt.R(@base)) || IsString(rt, rt.R(@base))) {
            long e2 = global::Flint.Rt.Maps.Empty(rt);
            int e2i = rt.Push(e2);
            long kt = LitKeyword1(rt, "tag");
            long m2 = MapAssoc(rt, rt.R(e2i), kt, rt.R(@base));
            rt.PopTo(e2i);
            rt.SetR(@base, m2);
        } else if (!IsMap(rt, rt.R(@base))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "metadata must be a symbol, keyword, string or map");
        }
        RdSkipWs(rt, sti);
        int ti = rt.Mark();
        int tst = ReadOne(rt, sti);
        if (tst == RsErr) {
            rt.PopTo(@base);
            return RsErr;
        }
        if ((tst == RsEof) || (tst == RsNone)) {
            rt.PopTo(@base);
            return tst;
        }
        if (IsConditional(rt, rt.R(ti))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "metadata on a reader conditional cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
        }
        if ((tst == RsOk) && MetaAble(rt, rt.R(ti))) {
            long ex = MetaOf(rt, rt.R(ti));
            int xi = rt.Push(ex);
            int ni = rt.Push(Val.Nil);
            Merge3(rt, xi, ni, @base);
            long @out = WithMeta(rt, rt.R(ti), rt.R(ni + 1));
            rt.PopTo(@base);
            rt.Push(@out);
            return RsOk;
        }
        long same = rt.R(ti);
        rt.PopTo(@base);
        rt.Push(same);
        return tst;
    }
    /// The symbol `p<k>__flint#`.
    internal static long ArgSymbol(Rt rt, long k) {
        int sk = rt.SinkOpen();
        rt.SinkPut(sk, 112);
        MsgInt(rt, sk, k);
        MsgLit(rt, sk, "__flint#");
        long text = rt.SinkString(sk);
        rt.SinkClose(sk);
        return global::Flint.Rt.Str.SymbolOf(rt, Val.Nil, text);
    }
    /// `#()`'s walk of the value rooted at `fi`, pushed. `ri` roots a
    /// two-slot vector `[maxn rest?]` the walk updates. A collection is REBUILT
    /// and loses its metadata, as the guest's walk rebuilt it; a symbol that is
    /// not an argument keeps its own.
    internal static void WalkArg(Rt rt, int fi, int ri) {
        int @base = rt.Mark();
        if (IsSymbol(rt, rt.R(fi))) {
            long nm = NameOf(rt, rt.R(fi));
            int nmi = rt.Push(nm);
            long pct = Str.Of(rt, "%");
            if (ValEq(rt, rt.R(nmi), pct)) {
                long mx = Val.AsFixnum(VecNth(rt, rt.R(ri), 0, Val.Nil));
                if (mx < 1) {
                    long r1 = VecAssoc(rt, rt.R(ri), 0, Val.Fixnum(1));
                    rt.SetR(ri, r1);
                }
                long p1 = ArgSymbol(rt, 1);
                rt.PopTo(@base);
                rt.Push(p1);
                return;
            }
            long amp = Str.Of(rt, "%&");
            if (ValEq(rt, rt.R(nmi), amp)) {
                long r2 = VecAssoc(rt, rt.R(ri), 1, Val.True);
                int r2i = rt.Push(r2);
                rt.SetR(ri, rt.R(r2i));
                long ps = LitSymbol1(rt, "prest__flint#");
                rt.PopTo(@base);
                rt.Push(ps);
                return;
            }
            // `%N`: a percent and then digits, at least one.
            int c = CodePoints(rt, rt.R(nmi));
            int n = rt.CpsLen(c);
            bool digits;
            digits = (n > 1) && (rt.CpsAt(c, 0) == 37);
            long k;
            k = 0;
            for (int i = 1; i < n; i++) {
                int d = rt.CpsAt(c, i);
                if (!IsDigit(d)) {
                    digits = false;
                }
                if (digits) {
                    k = (k * 10) + ((long) (d - 48));
                }
            }
            rt.CpsClose(c);
            if (digits) {
                long mx2 = Val.AsFixnum(VecNth(rt, rt.R(ri), 0, Val.Nil));
                if (mx2 < k) {
                    long r3 = VecAssoc(rt, rt.R(ri), 0, Val.Fixnum(k));
                    rt.SetR(ri, r3);
                }
                long pk = ArgSymbol(rt, k);
                rt.PopTo(@base);
                rt.Push(pk);
                return;
            }
            rt.PopTo(@base);
            rt.Push(rt.R(fi));
            return;
        }
        if (IsSeq(rt, rt.R(fi)) || IsVectorLike(rt, rt.R(fi))) {
            bool asList = IsSeq(rt, rt.R(fi));
            long s0 = Seq(rt, rt.R(fi));
            int si = rt.Push(s0);
            int xs = rt.Mark();
            int cnt;
            cnt = 0;
            for (;;) {
                if (Val.IsNil(rt.R(si))) {
                    break;
                }
                long x = First(rt, rt.R(si));
                int xi = rt.Push(x);
                WalkArg(rt, xi, ri);
                // The walked value sits above the original: move it down.
                rt.SetR(xi, rt.R(xi + 1));
                rt.PopTo(xi + 1);
                cnt += 1;
                long nx = Next(rt, rt.R(si));
                rt.SetR(si, nx);
            }
            long built;
            if (asList) {
                built = ListFromRoots(rt, xs, cnt);
            } else {
                built = VecFromRoots(rt, xs, cnt);
            }
            rt.PopTo(@base);
            rt.Push(built);
            return;
        }
        if (IsSet(rt, rt.R(fi))) {
            long ev = SetElementVector(rt, rt.R(fi));
            int evi = rt.Push(ev);
            long es = global::Flint.Rt.Sets.Empty(rt);
            long t0 = ToTransient(rt, es);
            int ti = rt.Push(t0);
            int sn = VecCount(rt, rt.R(evi));
            for (int j = 0; j < sn; j++) {
                long y = VecNth(rt, rt.R(evi), j, Val.Nil);
                int yi = rt.Push(y);
                WalkArg(rt, yi, ri);
                long t2 = TransientConj(rt, rt.R(ti), rt.R(yi + 1));
                rt.SetR(ti, t2);
                rt.PopTo(yi);
            }
            long sv = ToPersistent(rt, rt.R(ti));
            rt.PopTo(@base);
            rt.Push(sv);
            return;
        }
        if (IsMap(rt, rt.R(fi))) {
            long mv = MapEntryVector(rt, rt.R(fi));
            int mvi = rt.Push(mv);
            int mn = VecCount(rt, rt.R(mvi));
            int kvs = rt.Mark();
            for (int q = 0; q < mn; q++) {
                long en = VecNth(rt, rt.R(mvi), q, Val.Nil);
                int eni = rt.Push(en);
                long kk = rt.Slot(rt.R(eni), 0);
                int kki = rt.Push(kk);
                WalkArg(rt, kki, ri);
                long vv = rt.Slot(rt.R(eni), 1);
                int vvi = rt.Push(vv);
                WalkArg(rt, vvi, ri);
                // Leave exactly the walked key and value at `eni`.
                rt.SetR(eni, rt.R(kki + 1));
                rt.SetR(kki, rt.R(vvi + 1));
                rt.PopTo(kki + 1);
            }
            long flat = VecFromRoots(rt, kvs, 2 * mn);
            long om = OrderedMap(rt, flat);
            rt.PopTo(@base);
            rt.Push(om);
            return;
        }
        rt.Push(rt.R(fi));
    }
    /// `#(...)`, at the `(` after the `#`: `(fn* [p1__flint# ..] body)`, its
    /// arity the highest `%n` used and `& prest__flint#` for `%&`.
    internal static int ReadArgFn(Rt rt, int sti) {
        long n0 = RdInt(rt, sti, RdsConds);
        int @base = rt.Mark();
        int st = ReadDelimited(rt, sti, 41);
        if (st != RsOk) {
            return st;
        }
        int g = DeferredGuard(rt, sti, n0, "#()");
        if (g != RsOk) {
            rt.PopTo(@base);
            return g;
        }
        int n = DelimitedCount(rt, @base);
        long body0 = ListFromRoots(rt, @base + 1, n);
        rt.PopTo(@base);
        int bi = rt.Push(body0);
        rt.Push(Val.Fixnum(0 & 0xFFFFFFFFL));
        rt.Push(Val.False);
        long state = VecFromRoots(rt, bi + 1, 2);
        rt.PopTo(bi + 1);
        int ri = rt.Push(state);
        WalkArg(rt, bi, ri);
        int walked = ri + 1;
        long maxn = Val.AsFixnum(VecNth(rt, rt.R(ri), 0, Val.Nil));
        bool rest = VecNth(rt, rt.R(ri), 1, Val.Nil) == Val.True;
        int ps = rt.Mark();
        long k;
        k = 1;
        while (k <= maxn) {
            long pk = ArgSymbol(rt, k);
            rt.Push(pk);
            k += 1;
        }
        if (rest) {
            long amp = LitSymbol1(rt, "&");
            rt.Push(amp);
            long pr = LitSymbol1(rt, "prest__flint#");
            rt.Push(pr);
        }
        long @params = VecFromRoots(rt, ps, (int) (rt.Mark() - ps));
        rt.PopTo(ps);
        int pai = rt.Push(@params);
        int three = rt.Mark();
        long fnsym = LitSymbol1(rt, "fn*");
        rt.Push(fnsym);
        rt.Push(rt.R(pai));
        rt.Push(rt.R(walked));
        CollapseList(rt, three, 3);
        long @out = rt.R(three);
        rt.PopTo(@base);
        rt.Push(@out);
        return RsOk;
    }
    /// `#?(..)` and `#?@(..)`, at the `?`. A deferred read keeps it as a node;
    /// an eager one chooses: the first clause whose key is a feature or
    /// `:default`. Unmatched is `RS_EOF` -- the form vanishes -- or `RS_NONE`
    /// for a splice; a matched splice is `RS_SPLICE` with its collection pushed.
    internal static int ReadCond(Rt rt, int sti, bool splicing, long line, long col) {
        RdNext(rt, sti);
        if (splicing) {
            RdNext(rt, sti);
        }
        RdSkipWs(rt, sti);
        if (RdPeek(rt, sti) != 40) {
            return RdFailLit(rt, sti, "reader conditional wants a list");
        }
        int @base = rt.Mark();
        int st = ReadDelimited(rt, sti, 41);
        if (st != RsOk) {
            return st;
        }
        int n = DelimitedCount(rt, @base);
        if (RdFlag(rt, sti, RdsDefer)) {
            long items = VecFromRoots(rt, @base + 1, n);
            rt.PopTo(@base);
            int ii = rt.Push(items);
            long cp = RdGet(rt, sti, RdsChildpos);
            int cpi = rt.Push(cp);
            if (splicing) {
                PushConditional(rt, sti, "splice", line, col, cpi, ii);
            } else {
                PushConditional(rt, sti, "one", line, col, cpi, ii);
            }
            long node = rt.R(cpi + 1);
            rt.PopTo(@base);
            rt.Push(node);
            return RsOk;
        }
        // CHOOSE. A nil key ends the clauses, as the guest's
        // destructuring loop ends on one.
        long dk = LitKeyword1(rt, "default");
        int dki = rt.Push(dk);
        int i;
        i = 0;
        while (i < n) {
            int ki = @base + (i + 1);
            if (Val.IsNil(rt.R(ki))) {
                break;
            }
            if (SetContains(rt, RdGet(rt, sti, RdsFeatures), rt.R(ki)) || ValEq(rt, rt.R(ki), rt.R(dki))) {
                long chosen;
                chosen = Val.Nil;
                if ((i + 1) < n) {
                    chosen = rt.R(ki + 1);
                }
                rt.PopTo(@base);
                rt.Push(chosen);
                if (splicing) {
                    return RsSplice;
                }
                return RsOk;
            }
            i += 2;
        }
        rt.PopTo(@base);
        if (splicing) {
            return RsNone;
        }
        return RsEof;
    }
    /// Does resolving a conditional among the map literal's forms (rooted at
    /// `at`, `n` of them) change how many forms there are, or which are keys?
    internal static bool SizeConditional(Rt rt, int at, int n) {
        for (int i = 0; i < n; i++) {
            long x = rt.R(at + i);
            if (IsConditional(rt, x)) {
                if (((i % 2) == 0) || ((n % 2) != 0)) {
                    return true;
                }
                long kind = VecNth(rt, rt.Slot(rt.R(at + i), 1), 0, Val.Nil);
                int kbase = rt.Mark();
                int kindi = rt.Push(kind);
                long sp = LitKeyword1(rt, "splice");
                bool hit = ValEq(rt, rt.R(kindi), sp);
                rt.PopTo(kbase);
                if (hit) {
                    return true;
                }
            }
        }
        return false;
    }
    /// The namespace `::a/kw` names, pushed: `a`'s alias from the file's `ns`
    /// form, or `a` itself as a string. Refused when the `ns` form held a
    /// reader conditional and the read is deferred, because then which aliases
    /// it declares is not known. `a` is the code points `from`..`to`.
    internal static int AliasNs(Rt rt, int sti, int from, int to) {
        int @base = rt.Mark();
        long a = RdString(rt, sti, from, to);
        int ai = rt.Push(a);
        long @as = global::Flint.Rt.Str.SymbolOf(rt, Val.Nil, rt.R(ai));
        long hit = MapGet(rt, RdGet(rt, sti, RdsAliases), @as, Val.NotFound);
        if ((hit != Val.NotFound) && !Val.IsNil(hit)) {
            rt.PopTo(@base);
            rt.Push(hit);
            return RsOk;
        }
        if (RdFlag(rt, sti, RdsApartial)) {
            int sk = rt.SinkOpen();
            MsgLit(rt, sk, "::");
            MsgVal(rt, sk, rt.R(ai));
            MsgLit(rt, sk, "/ in a file whose ns form holds a reader conditional cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
            rt.PopTo(@base);
            return RdFailSink(rt, sti, sk);
        }
        return RsOk;
    }
    /// Push `(str x)` of the value on top -- a symbol's full name, or the
    /// string itself -- replacing it.
    internal static void TopAsString(Rt rt, int at) {
        int sk = rt.SinkOpen();
        MsgVal(rt, sk, rt.R(at));
        long s = rt.SinkString(sk);
        rt.SinkClose(sk);
        rt.SetR(at, s);
    }
    /// Push the current namespace's name as a string, or "user".
    internal static void PushCurrentNs(Rt rt, int sti) {
        long nsv = RdGet(rt, sti, RdsNs);
        if (Val.IsNil(nsv)) {
            long u = Str.Of(rt, "user");
            rt.Push(u);
            return;
        }
        int at = rt.Push(nsv);
        TopAsString(rt, at);
    }
    /// `#:ns{..}`, `#::{..}`, `#::alias{..}`, at the colon: the map with every
    /// unqualified keyword or symbol key given the namespace -- a NEW map,
    /// assoc'd in the map's order.
    internal static int ReadNsMap(Rt rt, int sti) {
        int from = RdToken(rt, sti);
        int to = RdPos(rt, sti);
        int @base = rt.Mark();
        // THE NAMESPACE, as a string; empty when there is none.
        if (((to - from) >= 2) && ((RdAt(rt, sti, from) == 58) && (RdAt(rt, sti, from + 1) == 58))) {
            if ((to - from) == 2) {
                PushCurrentNs(rt, sti);
            } else {
                int ast = AliasNs(rt, sti, from + 2, to);
                if (ast != RsOk) {
                    return ast;
                }
                TopAsString(rt, @base);
            }
        } else if (((to - from) >= 1) && (RdAt(rt, sti, from) == 58)) {
            long s1 = RdString(rt, sti, from + 1, to);
            rt.Push(s1);
        } else {
            long s2 = Str.Of(rt, "");
            rt.Push(s2);
        }
        RdSkipWs(rt, sti);
        int mi = rt.Mark();
        int st = ReadOne(rt, sti);
        if (st == RsErr) {
            rt.PopTo(@base);
            return RsErr;
        }
        if (st != RsOk) {
            rt.Push(Val.Nil);
        }
        if (IsConditional(rt, rt.R(mi))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "#: over a map whose keys hold a reader conditional cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
        }
        long empty = Str.Of(rt, "");
        if (ValEq(rt, rt.R(@base), empty)) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "#: wants a namespace");
        }
        if (!IsMap(rt, rt.R(mi))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "#: wants a map");
        }
        long ev = MapEntryVector(rt, rt.R(mi));
        int evi = rt.Push(ev);
        long e0 = global::Flint.Rt.Maps.Empty(rt);
        int acci = rt.Push(e0);
        int n = VecCount(rt, rt.R(evi));
        for (int i = 0; i < n; i++) {
            long en = VecNth(rt, rt.R(evi), i, Val.Nil);
            int eni = rt.Push(en);
            long k = rt.Slot(rt.R(eni), 0);
            int kki = rt.Push(k);
            if ((IsKeyword(rt, rt.R(kki)) || IsSymbol(rt, rt.R(kki))) && Val.IsNil(NsOf(rt, rt.R(kki)))) {
                long nm = NameOf(rt, rt.R(kki));
                if (IsKeyword(rt, rt.R(kki))) {
                    long qk = global::Flint.Rt.Str.KeywordOf(rt, rt.R(@base), nm);
                    rt.SetR(kki, qk);
                } else {
                    long qs = global::Flint.Rt.Str.SymbolOf(rt, rt.R(@base), nm);
                    rt.SetR(kki, qs);
                }
            }
            long m2 = MapAssoc(rt, rt.R(acci), rt.R(kki), rt.Slot(rt.R(eni), 1));
            rt.SetR(acci, m2);
            rt.PopTo(eni);
        }
        long @out = rt.R(acci);
        rt.PopTo(@base);
        rt.Push(@out);
        return RsOk;
    }
    /// `no reader for the tag #x; this project can read #a, #b. ..` -- the
    /// names this project binds, sorted.
    internal static int TagError(Rt rt, int sti, int tagi) {
        int @base = rt.Mark();
        long tm = RdGet(rt, sti, RdsTags);
        long ev = MapEntryVector(rt, tm);
        int evi = rt.Push(ev);
        int n = VecCount(rt, rt.R(evi));
        int names = rt.Mark();
        for (int i = 0; i < n; i++) {
            int nk = rt.SinkOpen();
            MsgVal(rt, nk, rt.Slot(VecNth(rt, rt.R(evi), i, Val.Nil), 0));
            long one = rt.SinkString(nk);
            rt.SinkClose(nk);
            rt.Push(one);
        }
        SortRoots(rt, names, n);
        int sk = rt.SinkOpen();
        MsgLit(rt, sk, "no reader for the tag #");
        MsgVal(rt, sk, rt.R(tagi));
        if (n > 0) {
            MsgLit(rt, sk, "; this project can read ");
            for (int j = 0; j < n; j++) {
                if (j > 0) {
                    MsgLit(rt, sk, ", ");
                }
                rt.SinkPut(sk, 35);
                MsgVal(rt, sk, rt.R(names + j));
            }
        } else {
            MsgLit(rt, sk, "; this project has no reader tags");
        }
        MsgLit(rt, sk, ". A tag is bound per PROJECT, not per namespace: add it under :flint/tag-readers in deps.edn, mapping the tag NAME to the VAR that reads it -- {");
        MsgVal(rt, sk, rt.R(tagi));
        MsgLit(rt, sk, " my.ns/read-it}. Using another project's tag is opt-in, which is why yours are not in scope here by default (DECISIONS.md#reader-tags). To make a tagged literal as a VALUE instead, call (tagged-literal '");
        MsgVal(rt, sk, rt.R(tagi));
        MsgLit(rt, sk, " form); to read one from data, use clojure.edn/read-string with :readers or :default.");
        rt.PopTo(@base);
        return RdFailSink(rt, sti, sk);
    }
    /// A flint-only tag in a PORTABLE file.
    internal static int PortabilityError(Rt rt, int sti, int tagi) {
        int sk = rt.SinkOpen();
        rt.SinkPut(sk, 35);
        MsgVal(rt, sk, rt.R(tagi));
        MsgLit(rt, sk, " is a flint-only reader tag, and ");
        MsgVal(rt, sk, RdGet(rt, sti, RdsFile));
        MsgLit(rt, sk, " is a PORTABLE file. Nothing outside flint can read it: a tag is bound by flint's workspace (:flint/tag-readers) or by flint's reader itself, and another platform's reader knows neither (DECISIONS.md#dialects-and-preludes). Rename the file to .fln -- a .fln and a .cljc are the same namespace, and flint prefers its own -- or write the value without the tag.");
        return RdFailSink(rt, sti, sk);
    }
    /// `#tag form`, the tag not yet read: REWRITTEN to `(the-var form)` with
    /// what was written on its metadata -- the reader evaluates nothing
    /// (`DECISIONS.md#reader-tags`). The position is where the reader stands
    /// AFTER the form, as the guest's took it.
    internal static int ReadTagged(Rt rt, int sti) {
        int @base = rt.Mark();
        int tst = ReadOne(rt, sti);
        if (tst == RsErr) {
            return RsErr;
        }
        if (tst != RsOk) {
            rt.PopTo(@base);
            rt.Push(Val.Nil);
        }
        RdSkipWs(rt, sti);
        long n0 = RdInt(rt, sti, RdsConds);
        int vi = rt.Mark();
        int vst = ReadOne(rt, sti);
        if (vst == RsErr) {
            rt.PopTo(@base);
            return RsErr;
        }
        if (vst != RsOk) {
            rt.PopTo(vi);
            rt.Push(Val.Nil);
        }
        int g = DeferredGuard(rt, sti, n0, "a reader tag's argument");
        if (g != RsOk) {
            rt.PopTo(@base);
            return g;
        }
        if (!IsSymbol(rt, rt.R(@base))) {
            rt.PopTo(@base);
            return RdFailLit(rt, sti, "reader tag must be a symbol");
        }
        long target0 = MapGet(rt, RdGet(rt, sti, RdsTags), rt.R(@base), Val.Nil);
        if (Val.IsNil(target0)) {
            int te = TagError(rt, sti, @base);
            rt.PopTo(@base);
            return te;
        }
        long target = WithMeta(rt, target0, Val.Nil);
        int tgi = rt.Push(target);
        if (RdFlag(rt, sti, RdsPortable)) {
            int pe = PortabilityError(rt, sti, @base);
            rt.PopTo(@base);
            return pe;
        }
        // THE METADATA, a map literal in this order.
        long e = global::Flint.Rt.Maps.Empty(rt);
        int mi = rt.Push(e);
        long tl = NewTagged(rt, rt.R(@base), rt.R(vi));
        int tli = rt.Push(tl);
        long k1 = LitKeyword(rt, "flint", "read-form");
        long m1 = MapAssoc(rt, rt.R(mi), k1, rt.R(tli));
        rt.SetR(mi, m1);
        long k2 = LitKeyword(rt, "flint", "read-tag");
        long m2 = MapAssoc(rt, rt.R(mi), k2, rt.R(@base));
        rt.SetR(mi, m2);
        long k3 = LitKeyword(rt, "flint", "read-var");
        long m3 = MapAssoc(rt, rt.R(mi), k3, rt.R(tgi));
        rt.SetR(mi, m3);
        long k4 = LitKeyword1(rt, "line");
        long m4 = MapAssoc(rt, rt.R(mi), k4, RdGet(rt, sti, RdsLine));
        rt.SetR(mi, m4);
        long k5 = LitKeyword1(rt, "column");
        long m5 = MapAssoc(rt, rt.R(mi), k5, RdGet(rt, sti, RdsCol));
        rt.SetR(mi, m5);
        long k6 = LitKeyword1(rt, "file");
        long m6 = MapAssoc(rt, rt.R(mi), k6, RdGet(rt, sti, RdsFile));
        rt.SetR(mi, m6);
        int two = rt.Mark();
        rt.Push(rt.R(tgi));
        rt.Push(rt.R(vi));
        CollapseList(rt, two, 2);
        long @out = WithMeta(rt, rt.R(two), rt.R(mi));
        rt.PopTo(@base);
        rt.Push(@out);
        return RsOk;
    }
    /// Everything after `#`: sets, `#()`, regexes, `#'`, `#_`, `#?`, `##`,
    /// `#:`, and tags.
    internal static int ReadDispatch(Rt rt, int sti, long line, long col) {
        RdNext(rt, sti);
        int c = RdPeek(rt, sti);
        if (c == 123) {
            int @base = rt.Mark();
            int st = ReadDelimited(rt, sti, 125);
            if (st != RsOk) {
                return st;
            }
            int n = DelimitedCount(rt, @base);
            bool any;
            any = false;
            if (RdFlag(rt, sti, RdsDefer)) {
                for (int i = 0; i < n; i++) {
                    if (IsConditional(rt, rt.R(@base + (i + 1)))) {
                        any = true;
                    }
                }
            }
            if (any) {
                long items = VecFromRoots(rt, @base + 1, n);
                rt.PopTo(@base);
                int ii = rt.Push(items);
                int cpi = rt.Push(Val.Nil);
                PushConditional(rt, sti, "set", line, col, cpi, ii);
                long node = rt.R(cpi + 1);
                rt.PopTo(@base);
                rt.Push(node);
                return RsOk;
            }
            // `(set xs)`: `into #{}`, through a transient.
            long es = global::Flint.Rt.Sets.Empty(rt);
            long t0 = ToTransient(rt, es);
            int ti = rt.Push(t0);
            for (int j = 0; j < n; j++) {
                long t1 = TransientConj(rt, rt.R(ti), rt.R(@base + (j + 1)));
                rt.SetR(ti, t1);
            }
            long sv = ToPersistent(rt, rt.R(ti));
            rt.PopTo(@base);
            rt.Push(sv);
            return RsOk;
        }
        if (c == 40) {
            return ReadArgFn(rt, sti);
        }
        if (c == 34) {
            return ReadRegexLit(rt, sti);
        }
        if (c == 39) {
            RdNext(rt, sti);
            int vb = rt.Mark();
            int vst = ReadOne(rt, sti);
            if (vst == RsErr) {
                return RsErr;
            }
            if (vst != RsOk) {
                rt.Push(Val.Nil);
            }
            long vs = LitSymbol1(rt, "var");
            WrapRoot(rt, vb, vs);
            return RsOk;
        }
        if (c == 95) {
            RdNext(rt, sti);
            int db = rt.Mark();
            int dst = ReadOne(rt, sti);
            rt.PopTo(db);
            if (dst == RsErr) {
                return RsErr;
            }
            return RsEof;
        }
        if (c == 63) {
            return ReadCond(rt, sti, RdPeek2(rt, sti) == 64, line, col);
        }
        if (c == 35) {
            RdNext(rt, sti);
            int from = RdToken(rt, sti);
            int to = RdPos(rt, sti);
            long inf = Str.Of(rt, "Inf");
            if (RdRangeIs(rt, sti, from, to, inf)) {
                rt.Push(Val.OfDouble(double.PositiveInfinity));
                return RsOk;
            }
            long ninf = Str.Of(rt, "-Inf");
            if (RdRangeIs(rt, sti, from, to, ninf)) {
                rt.Push(Val.OfDouble(-1.0 * double.PositiveInfinity));
                return RsOk;
            }
            long nan = Str.Of(rt, "NaN");
            if (RdRangeIs(rt, sti, from, to, nan)) {
                rt.Push(Val.OfDouble(System.BitConverter.Int64BitsToDouble(Val.CanonicalNan)));
                return RsOk;
            }
            int sk = rt.SinkOpen();
            MsgLit(rt, sk, "unknown ## literal: ");
            int i;
            i = from;
            while (i < to) {
                MsgCp(rt, sk, RdAt(rt, sti, i));
                i += 1;
            }
            return RdFailSink(rt, sti, sk);
        }
        if (c == 58) {
            return ReadNsMap(rt, sti);
        }
        if ((c == NoCp) || IsWs(c)) {
            return RdFailLit(rt, sti, "unexpected #");
        }
        return ReadTagged(rt, sti);
    }
    /// The index of the first `/` in `from`..`to`, or `to`.
    internal static int SlashAt(Rt rt, int sti, int from, int to) {
        int i;
        i = from;
        while (i < to) {
            if (RdAt(rt, sti, i) == 47) {
                return i;
            }
            i += 1;
        }
        return to;
    }
    /// A token that is not a delimiter: nil, true, false, `/`, a number, a
    /// keyword or a symbol.
    internal static int ReadSymbolic(Rt rt, int sti) {
        int from = RdToken(rt, sti);
        int to = RdPos(rt, sti);
        if (from == to) {
            return RdFailLit(rt, sti, "empty token");
        }
        long tn = Str.Of(rt, "nil");
        if (RdRangeIs(rt, sti, from, to, tn)) {
            rt.Push(Val.Nil);
            return RsOk;
        }
        long tt = Str.Of(rt, "true");
        if (RdRangeIs(rt, sti, from, to, tt)) {
            rt.Push(Val.True);
            return RsOk;
        }
        long tf = Str.Of(rt, "false");
        if (RdRangeIs(rt, sti, from, to, tf)) {
            rt.Push(Val.False);
            return RsOk;
        }
        if (((to - from) == 1) && (RdAt(rt, sti, from) == 47)) {
            long sl = LitSymbol1(rt, "/");
            rt.Push(sl);
            return RsOk;
        }
        int nst = ParseNumber(rt, sti, from, to);
        if (nst != RsNone) {
            return nst;
        }
        // `::kw` against this file's `ns`, `::a/kw` against its alias `a`.
        if (RdAt(rt, sti, from) == 58) {
            if (((to - from) > 1) && (RdAt(rt, sti, from + 1) == 58)) {
                int t2 = from + 2;
                int sl = SlashAt(rt, sti, t2, to);
                if (sl < to) {
                    int @base = rt.Mark();
                    int ast = AliasNs(rt, sti, t2, sl);
                    if (ast != RsOk) {
                        return ast;
                    }
                    TopAsString(rt, @base);
                    long nm = RdString(rt, sti, sl + 1, to);
                    long kw = global::Flint.Rt.Str.KeywordOf(rt, rt.R(@base), nm);
                    rt.PopTo(@base);
                    rt.Push(kw);
                    return RsOk;
                }
                int base2 = rt.Mark();
                PushCurrentNs(rt, sti);
                long nm2 = RdString(rt, sti, t2, to);
                long kw2 = global::Flint.Rt.Str.KeywordOf(rt, rt.R(base2), nm2);
                rt.PopTo(base2);
                rt.Push(kw2);
                return RsOk;
            }
            int t1 = from + 1;
            int sl1 = SlashAt(rt, sti, t1, to);
            if ((sl1 == to) || (sl1 == t1)) {
                long whole = RdString(rt, sti, t1, to);
                long kw3 = global::Flint.Rt.Str.KeywordOf(rt, Val.Nil, whole);
                rt.Push(kw3);
                return RsOk;
            }
            int base3 = rt.Mark();
            long kns = RdString(rt, sti, t1, sl1);
            int knsi = rt.Push(kns);
            long knm = RdString(rt, sti, sl1 + 1, to);
            long kw4 = global::Flint.Rt.Str.KeywordOf(rt, rt.R(knsi), knm);
            rt.PopTo(base3);
            rt.Push(kw4);
            return RsOk;
        }
        int sl2 = SlashAt(rt, sti, from, to);
        if ((sl2 == to) || ((sl2 == from) || (sl2 == (to - 1)))) {
            long sn = RdString(rt, sti, from, to);
            long sym = global::Flint.Rt.Str.SymbolOf(rt, Val.Nil, sn);
            rt.Push(sym);
            return RsOk;
        }
        int base4 = rt.Mark();
        long sns = RdString(rt, sti, from, sl2);
        int snsi = rt.Push(sns);
        long snm = RdString(rt, sti, sl2 + 1, to);
        long sym2 = global::Flint.Rt.Str.SymbolOf(rt, rt.R(snsi), snm);
        rt.PopTo(base4);
        rt.Push(sym2);
        return RsOk;
    }
    /// Read `(head <form>)` for a reader macro whose character was just taken.
    internal static int ReadWrapped(Rt rt, int sti, long head) {
        int @base = rt.Mark();
        int hi = rt.Push(head);
        int vi = rt.Mark();
        int st = ReadOne(rt, sti);
        if (st == RsErr) {
            rt.PopTo(@base);
            return RsErr;
        }
        if (st != RsOk) {
            rt.PopTo(vi);
            rt.Push(Val.Nil);
        }
        WrapRoot(rt, vi, rt.R(hi));
        rt.SetR(@base, rt.R(vi));
        rt.PopTo(@base + 1);
        return RsOk;
    }
    /// One form at the cursor, pushed -- or `RS_EOF` at the end of the text.
    /// Every meta-able result is stamped with where it began, and a SEQUENCE
    /// with the stash's child positions.
    public static int ReadOne(Rt rt, int sti) {
        RdSkipWs(rt, sti);
        long line = RdInt(rt, sti, RdsLine);
        long col = RdInt(rt, sti, RdsCol);
        int c = RdPeek(rt, sti);
        int @base = rt.Mark();
        if (c == NoCp) {
            return RsEof;
        }
        int st;
        st = RsOk;
        int closer;
        closer = 93;
        if (c == 40) {
            closer = 41;
        }
        if ((c == 40) || (c == 91)) {
            st = ReadDelimited(rt, sti, closer);
            if (st != RsOk) {
                return st;
            }
            int n = DelimitedCount(rt, @base);
            long coll;
            if (c == 40) {
                coll = ListFromRoots(rt, @base + 1, n);
            } else {
                coll = VecFromRoots(rt, @base + 1, n);
            }
            rt.PopTo(@base);
            rt.Push(coll);
            StampStash(rt, sti, @base, line, col, true);
        } else if (c == 123) {
            st = ReadDelimited(rt, sti, 125);
            if (st != RsOk) {
                return st;
            }
            int mn = DelimitedCount(rt, @base);
            if (RdFlag(rt, sti, RdsDefer) && SizeConditional(rt, @base + 1, mn)) {
                long kvs = VecFromRoots(rt, @base + 1, mn);
                rt.PopTo(@base);
                int kvi = rt.Push(kvs);
                int ncp = rt.Push(Val.Nil);
                PushConditional(rt, sti, "map", line, col, ncp, kvi);
                long node = rt.R(ncp + 1);
                rt.PopTo(@base);
                rt.Push(node);
            } else {
                if ((mn % 2) != 0) {
                    rt.PopTo(@base);
                    return RdFailLit(rt, sti, "map literal needs an even number of forms");
                }
                long flat = VecFromRoots(rt, @base + 1, mn);
                long om = OrderedMap(rt, flat);
                rt.PopTo(@base);
                rt.Push(om);
            }
        } else if (c == 41) {
            return RdFailLit(rt, sti, "unexpected )");
        } else if (c == 93) {
            return RdFailLit(rt, sti, "unexpected ]");
        } else if (c == 125) {
            return RdFailLit(rt, sti, "unexpected }");
        } else if (c == 34) {
            st = ReadStringLit(rt, sti);
        } else if (c == 92) {
            st = ReadCharLit(rt, sti);
        } else if (c == 39) {
            RdNext(rt, sti);
            long q = LitSymbol1(rt, "quote");
            st = ReadWrapped(rt, sti, q);
        } else if (c == 64) {
            RdNext(rt, sti);
            long dr = LitSymbol(rt, "clojure.core", "deref");
            st = ReadWrapped(rt, sti, dr);
        } else if (c == 94) {
            st = ReadMeta(rt, sti);
        } else if (c == 96) {
            st = ReadSyntaxQuote(rt, sti);
        } else if (c == 126) {
            RdNext(rt, sti);
            if (RdPeek(rt, sti) == 64) {
                RdNext(rt, sti);
                long us = LitSymbol(rt, "clojure.core", "unquote-splicing");
                st = ReadWrapped(rt, sti, us);
            } else {
                long uq = LitSymbol(rt, "clojure.core", "unquote");
                st = ReadWrapped(rt, sti, uq);
            }
        } else if (c == 35) {
            st = ReadDispatch(rt, sti, line, col);
        } else {
            st = ReadSymbolic(rt, sti);
        }
        if (st != RsOk) {
            return st;
        }
        // EVERY meta-able form, and the stash's positions on a sequence.
        StampStash(rt, sti, @base, line, col, IsSeq(rt, rt.R(@base)));
        return RsOk;
    }
    /// `` `form ``, at the backquote: the form read with a fresh gensym table,
    /// then expanded.
    internal static int ReadSyntaxQuote(Rt rt, int sti) {
        RdNext(rt, sti);
        long gm = global::Flint.Rt.Maps.Empty(rt);
        RdPut(rt, sti, RdsGensyms, gm);
        long n0 = RdInt(rt, sti, RdsConds);
        int @base = rt.Mark();
        int st = ReadOne(rt, sti);
        if (st == RsErr) {
            return RsErr;
        }
        if (st != RsOk) {
            rt.Push(Val.Nil);
        }
        int g = DeferredGuard(rt, sti, n0, "syntax quote");
        if (g != RsOk) {
            rt.PopTo(@base);
            return g;
        }
        int sst = SqForm(rt, sti, @base);
        RdPut(rt, sti, RdsGensyms, Val.Nil);
        if (sst != RsOk) {
            rt.PopTo(@base);
            return sst;
        }
        rt.SetR(@base, rt.R(@base + 1));
        rt.PopTo(@base + 1);
        return RsOk;
    }
    /// `{alias target}` for every `:as` in the `ns` form rooted at `fi`'s
    /// require clauses, as the map the reader resolves `::a/kw` against.
    internal static void NsAliases(Rt rt, int sti, int fi) {
        int @base = rt.Mark();
        long e = global::Flint.Rt.Maps.Empty(rt);
        int acci = rt.Push(e);
        long kreq = LitKeyword1(rt, "require");
        int kreqi = rt.Push(kreq);
        long kuse = LitKeyword1(rt, "use");
        int kusei = rt.Push(kuse);
        long kas = LitKeyword1(rt, "as");
        int kasi = rt.Push(kas);
        long s0 = Seq(rt, rt.R(fi));
        int ci = rt.Push(s0);
        // `(drop 2 form)`.
        long d1 = Next(rt, rt.R(ci));
        rt.SetR(ci, d1);
        long d2 = Next(rt, rt.R(ci));
        rt.SetR(ci, d2);
        for (;;) {
            if (Val.IsNil(rt.R(ci))) {
                break;
            }
            long clause = First(rt, rt.R(ci));
            int cli = rt.Push(clause);
            if (IsSeq(rt, rt.R(cli))) {
                long head = First(rt, rt.R(cli));
                if (ValEq(rt, head, rt.R(kreqi)) || ValEq(rt, head, rt.R(kusei))) {
                    long sp0 = Next(rt, rt.R(cli));
                    int spi = rt.Push(sp0);
                    for (;;) {
                        if (Val.IsNil(rt.R(spi))) {
                            break;
                        }
                        long spec = First(rt, rt.R(spi));
                        int speci = rt.Push(spec);
                        // `(apply hash-map (rest spec))` and its `:as`: the
                        // LAST `:as` wins, and an odd count leaves the final
                        // key's value nil.
                        if (IsVectorLike(rt, rt.R(speci))) {
                            int sn = VecCount(rt, rt.R(speci));
                            long alias;
                            alias = Val.Nil;
                            int j;
                            j = 1;
                            while (j < sn) {
                                if (ValEq(rt, VecNth(rt, rt.R(speci), j, Val.Nil), rt.R(kasi))) {
                                    alias = VecNth(rt, rt.R(speci), j + 1, Val.Nil);
                                }
                                j += 2;
                            }
                            if (!Val.IsNil(alias) && (alias != Val.False)) {
                                int ali = rt.Push(alias);
                                long m2 = MapAssoc(rt, rt.R(acci), rt.R(ali), VecNth(rt, rt.R(speci), 0, Val.Nil));
                                rt.SetR(acci, m2);
                            }
                        }
                        rt.PopTo(speci);
                        long sn2 = Next(rt, rt.R(spi));
                        rt.SetR(spi, sn2);
                    }
                }
            }
            rt.PopTo(cli);
            long cn = Next(rt, rt.R(ci));
            rt.SetR(ci, cn);
        }
        RdPut(rt, sti, RdsAliases, rt.R(acci));
        rt.PopTo(@base);
    }
    /// One top-level form, pushed, or `RS_EOF`. A top-level `(ns ..)` sets the
    /// namespace and aliases `::kw` and `#::{}` resolve against for the rest
    /// of the read -- the FILE's own context, not the compiler's.
    public static int ReadTop(Rt rt, int sti) {
        for (;;) {
            long n0 = RdInt(rt, sti, RdsConds);
            int @base = rt.Mark();
            int st = ReadOne(rt, sti);
            if (st == RsErr) {
                return RsErr;
            }
            if (st == RsEof) {
                if (RdPeek(rt, sti) == NoCp) {
                    return RsEof;
                }
                continue;
            }
            if (st == RsSplice) {
                rt.PopTo(@base);
                return RdFailLit(rt, sti, "#?@ outside a collection");
            }
            // An unmatched `#?@` at the top: the guest's reader handed its
            // marker on as a form, which nothing can encode. Nothing is read
            // here instead.
            if (st == RsNone) {
                continue;
            }
            int vi = @base;
            if (IsSeq(rt, rt.R(vi))) {
                long h = First(rt, rt.R(vi));
                if (IsSym1(rt, h, "ns")) {
                    long nx = Next(rt, rt.R(vi));
                    long nm = First(rt, nx);
                    if (IsSymbol(rt, nm)) {
                        RdPut(rt, sti, RdsNs, nm);
                        NsAliases(rt, sti, vi);
                        if (n0 != RdInt(rt, sti, RdsConds)) {
                            RdPut(rt, sti, RdsApartial, Val.True);
                        } else {
                            RdPut(rt, sti, RdsApartial, Val.False);
                        }
                    }
                }
            }
            if (IsConditional(rt, rt.R(vi))) {
                long items = VecNth(rt, rt.Slot(rt.R(vi), 1), 4, Val.Nil);
                int ii = rt.Push(items);
                int n = VecCount(rt, rt.R(ii));
                for (int i = 0; i < n; i++) {
                    long x = VecNth(rt, rt.R(ii), i, Val.Nil);
                    if (IsSeq(rt, x)) {
                        long xh = First(rt, x);
                        if (IsSym1(rt, xh, "ns")) {
                            rt.PopTo(@base);
                            return RdFailLit(rt, sti, "an ns form inside a reader conditional cannot be read before its features are known (DECISIONS.md#stdlib-preread)");
                        }
                    }
                }
                rt.PopTo(ii);
            }
            return RsOk;
        }
    }
}
