// Generated by kin from the source named below. Do not edit.
// source: flint.rt.reapports

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Sched;
using static global::_3sln.Flint.Kgen.Rt.Vecread;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;

public static class Reapports {
    /// Has any id in this list lost its port? A scan allocates nothing, which is
    /// the point: the rebuild below is the expensive part and is almost never
    /// owed.
    public static bool AnyCollected(Rt rt, long ids) {
        int n = VecCount(rt, ids);
        bool gone;
        gone = false;
        for (int k = 0; k < n; k++) {
            if (Val.IsNil(Conc.PortById(rt, Val.AsFixnum(VecNth(rt, ids, k, Val.Nil))))) {
                gone = true;
            }
        }
        return gone;
    }
    /// A bridge end the collector took: the host hears the same pair it would
    /// have heard from an explicit close -- this sandbox is finished with the
    /// port, and it has let go of its reference. One `EV_RELEASE` per
    /// `EV_RETAIN`, which is what makes the host's count a count of holders
    /// rather than of arrivals.
    public static void ReapBridges(Rt rt, int si) {
        int bi = rt.Push(rt.Slot(rt.R(si), Conc.SC_BRIDGES));
        if (!AnyCollected(rt, rt.R(bi))) {
            return;
        }
        int bn = VecCount(rt, rt.R(bi));
        int hi = rt.Push(Vec.Empty(rt));
        for (int k = 0; k < bn; k++) {
            long id = Val.AsFixnum(VecNth(rt, rt.R(bi), k, Val.Nil));
            if (Val.IsNil(Conc.PortById(rt, id))) {
                Conc.PushEvent(rt, Conc.EV_CLOSED, id, 0, Val.Nil);
                Conc.PushEvent(rt, Conc.EV_RELEASE, id, 0, Val.Nil);
                continue;
            }
            // HOISTED, because Rust will not take two mutable borrows of
            // `rt` in one expression -- the conj has to land in a local
            // before `set-r` is handed it.
            long nh = VecConj(rt, rt.R(hi), Val.Fixnum(id));
            rt.SetR(hi, nh);
        }
        rt.SetSlot(Val.AsHeap(rt.R(si)), Conc.SC_BRIDGES, rt.R(hi));
    }
    /// A channel end the collector took ORPHANS its peer, which is not the same
    /// as a tidy close and must not read like one. Anyone parked on the peer is
    /// failed rather than left waiting for something that can never arrive.
    public static void ReapChannels(Rt rt, int si) {
        int ii = rt.Push(rt.Slot(rt.R(si), Conc.SC_PORTS));
        if (!AnyCollected(rt, rt.R(ii))) {
            return;
        }
        int n = VecCount(rt, rt.R(ii));
        int li = rt.Push(Vec.Empty(rt));
        for (int k = 0; k < n; k++) {
            long id = Val.AsFixnum(VecNth(rt, rt.R(ii), k, Val.Nil));
            if (!Val.IsNil(Conc.PortById(rt, id))) {
                long nl = VecConj(rt, rt.R(li), Val.Fixnum(id));
                rt.SetR(li, nl);
                continue;
            }
            // This end has been collected. Tell whoever is affected --
            // and the object is gone, so the pairing is looked up by id.
            long pid = Conc.PeerIdOfDead(rt, id);
            long peer = Conc.PortById(rt, pid);
            if (Val.IsNil(peer)) {
                continue;
            }
            int pi = rt.Push(peer);
            long pst = Val.AsFixnum(rt.Slot(rt.R(pi), Conc.PT_STATE));
            if ((pst != Conc.P_CLOSED) && (pst != Conc.P_ORPHANED)) {
                rt.SetSlot(Val.AsHeap(rt.R(pi)), Conc.PT_STATE, Val.Fixnum(Conc.P_ORPHANED));
            }
            Conc.FailWaitersOn(rt, rt.R(pi), "the other end of this port is unreachable, so this can never complete");
            Conc.WakeOn(rt, rt.R(pi));
            rt.PopTo(pi);
        }
        rt.SetSlot(Val.AsHeap(rt.R(si)), Conc.SC_PORTS, rt.R(li));
    }
    /// Both lists, under one mark. A collection is a RELEASE for a bridge and an
    /// ORPHANING for a channel, and neither is noticed anywhere else.
    public static void ReapAll(Rt rt) {
        long s = Conc.Sched(rt);
        if (Val.IsNil(s)) {
            return;
        }
        int @base = rt.Mark();
        int si = rt.Push(s);
        ReapBridges(rt, si);
        ReapChannels(rt, si);
        rt.PopTo(@base);
    }
    /// EVERYTHING THAT FOLLOWS FROM ONE END CLOSING, however it closed.
    /// 
    /// Two things happen, and only the first depends on what kind of port it is.
    /// 
    /// A BRIDGE MUST TELL THE HOST, and a close IS a release -- the prompt one.
    /// Dropping the last reference and waiting for the collector gets here too,
    /// through `reap-all`, but that is the backstop rather than the mechanism:
    /// it is not prompt, and a host holding a socket until then is a real cost.
    /// The id LEAVES `SC_BRIDGES` between the two events, so the sweep does not
    /// send a second release for a port already let go. A channel says nothing
    /// to anybody -- both its ends are in this heap.
    /// 
    /// THE PEER BECOMES HALF-CLOSED, NOT CLOSED, and that is the subtle half.
    /// It may still drain what is already in its buffer and only then read
    /// end-of-stream; the channel is not finished until both ends are. Closing
    /// it here would throw away messages that were legitimately sent.
    /// 
    /// AND ONLY AN OPEN PEER IS MOVED. A peer already closed or orphaned has
    /// had something more specific happen to it, and `P_HALF` would overwrite
    /// it -- the same reading `reap-all` takes when it refuses to orphan a peer
    /// that was tidily closed. It is not woken either: the `wake-on` is inside
    /// the same test, because there is nothing new for it to learn.
    /// 
    /// NAMED `close-effects` and not `close-side-effects`: the latter is the
    /// word each runtime exposes, and a kin function of that name would shadow
    /// it under whole-project generation. Same split as `reap-ports` over
    /// `reap-all`.
    public static long CloseEffects(Rt rt, long p) {
        int @base = rt.Mark();
        int pi = rt.Push(p);
        if (Conc.CrossesAHeap(Val.AsFixnum(rt.Slot(rt.R(pi), Conc.PT_KIND)))) {
            long id = Val.AsFixnum(rt.Slot(rt.R(pi), Conc.PT_ID));
            Conc.PushEvent(rt, Conc.EV_CLOSED, id, 0, Val.Nil);
            Conc.ForgetBridge(rt, id);
            Conc.PushEvent(rt, Conc.EV_RELEASE, id, 0, Val.Nil);
        }
        Conc.WakeOn(rt, rt.R(pi));
        long peer = Conc.PeerOf(rt, rt.R(pi));
        if (!Val.IsNil(peer) && (Val.AsFixnum(rt.Slot(peer, Conc.PT_STATE)) == Conc.P_OPEN)) {
            rt.SetSlot(Val.AsHeap(peer), Conc.PT_STATE, Val.Fixnum(Conc.P_HALF));
            Conc.WakeOn(rt, peer);
        }
        rt.PopTo(@base);
        return Val.Nil;
    }
    /// CLOSE EVERY BRIDGE THIS SANDBOX HOLDS, which is what ending it means.
    /// 
    /// NAMED `close-bridges` AND NOT `close-all-bridges`, which is the word each
    /// runtime still exposes: a kin function shadows a vocabulary word of the
    /// same name under whole-project generation, and `sched-drive` needs the
    /// WORD so the scheduler drivers can stub it. Same split as `reap-ports`
    /// (the word) over `reap-all` (this file).
    /// 
    /// A bridge crosses a heap, so the other side is somebody else's and has to
    /// be TOLD; a channel lives entirely in here and simply stops mattering.
    /// That is the whole of the `crosses-a-heap` test -- the list is walked
    /// whole and only the bridges are acted on.
    /// 
    /// ALREADY-CLOSED ENDS ARE SKIPPED, and not as an optimisation: the side
    /// effects push an `EV_CLOSED`/`EV_RELEASE` pair, and a second pair for a
    /// port already let go would make the host's count of holders wrong. One
    /// release per retain is the property, and the state test is what keeps it.
    /// 
    /// ROOTED PER ITERATION. `close-side-effects` pushes events and wakes
    /// threads, both of which allocate, so the port cannot be held in a local
    /// across it -- and the id list cannot either, which is why `ii` is a root
    /// and not a value.
    /// 
    /// THE DEFAULT IS `NIL`, and the three copies did not agree on it: native
    /// passed `NIL` to `vec-nth` and both ports passed `NOT_FOUND`. Nothing
    /// could reach it -- `k` is bounded by the count -- so it was a difference
    /// that could not show, which is exactly the kind that survives. Generating
    /// it settles the question by removing it.
    public static long CloseBridges(Rt rt) {
        long s = Conc.Sched(rt);
        if (Val.IsNil(s)) {
            return Val.Nil;
        }
        int @base = rt.Mark();
        int si = rt.Push(s);
        int ii = rt.Push(rt.Slot(rt.R(si), Conc.SC_PORTS));
        int n = VecCount(rt, rt.R(ii));
        for (int k = 0; k < n; k++) {
            long p = Conc.PortById(rt, Val.AsFixnum(VecNth(rt, rt.R(ii), k, Val.Nil)));
            if (Val.IsNil(p)) {
                continue;
            }
            int pi = rt.Push(p);
            if (Conc.CrossesAHeap(Val.AsFixnum(rt.Slot(rt.R(pi), Conc.PT_KIND))) && (Val.AsFixnum(rt.Slot(rt.R(pi), Conc.PT_STATE)) != Conc.P_CLOSED)) {
                rt.SetSlot(Val.AsHeap(rt.R(pi)), Conc.PT_STATE, Val.Fixnum(Conc.P_CLOSED));
                Conc.CloseSideEffects(rt, rt.R(pi));
            }
            rt.PopTo(pi);
        }
        rt.PopTo(@base);
        return Val.Nil;
    }
}
