// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropemeas

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Ropecat;

public static class Ropemeas {
    /// How many BYTES the string holds. O(1) on all three tiers.
    public static int SBytes(Rt rt, long v) {
        if (Val.IsInlineStr(v)) {
            return rt.LeafLen(v);
        }
        if (IsRope(rt, v)) {
            return (int) Val.AsFixnum(rt.Slot(v, global::Flint.Rt.Str.RP_BYTES));
        }
        return rt.LeafLen(v);
    }
    /// Is every byte below 0x80? All three tiers, O(1).
    /// 
    /// A ROPE READS BIT 0 of `RP_CPS`, where the count sits above it. A flat
    /// string reads the header bit the allocator set. Only an inline string is
    /// scanned, and it is at most seven bytes.
    public static bool SAscii(Rt rt, long v) {
        if (Val.IsInlineStr(v)) {
            int n = rt.LeafLen(v);
            for (int i = 0; i < n; i++) {
                if (rt.LeafByte(v, i) >= 128) {
                    return false;
                }
            }
            return true;
        }
        if (IsRope(rt, v)) {
            return (((int) Val.AsFixnum(rt.Slot(v, global::Flint.Rt.Str.RP_CPS))) & 1) != 0;
        }
        return Obj.StrIsAscii(rt.gc.sp, Val.AsHeap(v));
    }
    /// How many CODE POINTS the string holds.
    /// 
    /// O(1) for a rope and for an ASCII leaf; a scan bounded by the leaf
    /// otherwise. COUNTING NON-CONTINUATION BYTES rather than decoding: a
    /// continuation byte is exactly `10xxxxxx`, so every other byte starts a
    /// code point and nothing has to be assembled to be counted.
    public static int SCount(Rt rt, long v) {
        if (IsRope(rt, v)) {
            return (int)((uint) ((int) Val.AsFixnum(rt.Slot(v, global::Flint.Rt.Str.RP_CPS))) >> 1);
        }
        int n = rt.LeafLen(v);
        if (SAscii(rt, v)) {
            return n;
        }
        int c;
        c = 0;
        for (int i = 0; i < n; i++) {
            if ((rt.LeafByte(v, i) & 192) != 128) {
                c += 1;
            }
        }
        return c;
    }
}
