// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropecat

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Ropenode;

public static class Ropecat {
    /// Is `v` the NODE tier -- a tree rather than a leaf or an inline string?
    public static bool IsRope(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        return Obj.Ty(rt.gc.sp, Val.AsHeap(v)) == Obj.TyRope;
    }
    /// How many children this node has.
    public static int RopeKids(Rt rt, long v) {
        return Olen(rt, v) - global::Flint.Rt.Str.RP_KIDS;
    }
    /// How many levels of node stand above the leaves, 0 for a leaf itself.
    /// 
    /// Reads CHILD ZERO and recurses, which is exact because a node's children
    /// are all the same height -- the invariant `rope-lift` exists to keep.
    public static int RopeHeight(Rt rt, long v) {
        if (!IsRope(rt, v)) {
            return 0;
        }
        return 1 + RopeHeight(rt, rt.Slot(v, global::Flint.Rt.Str.RP_KIDS));
    }
    /// Append `b` into the rightmost subtree of `a` that has room.
    /// 
    /// NIL when the right spine is full at every level, which is the ONLY time
    /// the caller adds one -- so depth grows O(log n) times over n appends
    /// rather than O(n/FANOUT) times.
    /// 
    /// DEEPEST FIRST: room further down costs no depth at all, and only when
    /// nothing below has room does this node take `b` as a sibling.
    public static long RopeAppend(Rt rt, long a, long b) {
        if (!IsRope(rt, a)) {
            return Val.Nil;
        }
        int n = RopeKids(rt, a);
        int @base = rt.Mark();
        int ai = rt.Push(a);
        int bi = rt.Push(b);
        long last = rt.Slot(rt.R(ai), global::Flint.Rt.Str.RP_KIDS + (n - 1));
        int li = rt.Push(last);
        long deeper;
        deeper = Val.Nil;
        if (IsRope(rt, rt.R(li))) {
            deeper = RopeAppend(rt, rt.R(li), rt.R(bi));
        }
        if (!Val.IsNil(deeper)) {
            int ni = rt.Push(deeper);
            int kbase = rt.Mark();
            for (int i = 0; i < n - 1; i++) {
                rt.Push(rt.Slot(rt.R(ai), global::Flint.Rt.Str.RP_KIDS + i));
            }
            rt.Push(rt.R(ni));
            long @out = RopeNode(rt, kbase, n);
            rt.PopTo(@base);
            return @out;
        }
        if (n < global::Flint.Rt.Str.FANOUT) {
            // The spine is full below, but this node has room: `b` joins
            // as a sibling, LIFTED to the height its siblings stand at, or
            // the tree goes ragged and the depth grows linearly again.
            int h = RopeHeight(rt, rt.R(li));
            long lifted = RopeLift(rt, rt.R(bi), h);
            if (Val.IsNil(lifted)) {
                rt.PopTo(@base);
                return Val.Nil;
            }
            int ni = rt.Push(lifted);
            int kbase = rt.Mark();
            for (int i = 0; i < n; i++) {
                rt.Push(rt.Slot(rt.R(ai), global::Flint.Rt.Str.RP_KIDS + i));
            }
            rt.Push(rt.R(ni));
            long @out = RopeNode(rt, kbase, n + 1);
            rt.PopTo(@base);
            return @out;
        }
        rt.PopTo(@base);
        return Val.Nil;
    }
    /// `a` followed by `b`, as a string.
    public static long SConcat(Rt rt, long a, long b) {
        if (Str.SBytes(rt, a) == 0) {
            return b;
        }
        if (Str.SBytes(rt, b) == 0) {
            return a;
        }
        // Small enough that a tree would cost more in metadata than the copy
        // saves. This is the tier that must NOT be skipped.
        if ((Str.SBytes(rt, a) + Str.SBytes(rt, b)) <= global::Flint.Rt.Str.FLAT_MAX) {
            return Str.CopyConcat(rt, a, b);
        }
        long appended = RopeAppend(rt, a, b);
        if (!Val.IsNil(appended)) {
            return appended;
        }
        // A NEW LEVEL, and `b` is lifted to stand as tall as the old root so
        // the leaves stay at one depth on this side too.
        int @base = rt.Mark();
        int ai = rt.Push(a);
        int bi = rt.Push(b);
        int h = RopeHeight(rt, rt.R(ai));
        long lifted = RopeLift(rt, rt.R(bi), h);
        int li = rt.Push(lifted);
        int kbase = rt.Mark();
        rt.Push(rt.R(ai));
        rt.Push(rt.R(li));
        long @out = RopeNode(rt, kbase, 2);
        rt.PopTo(@base);
        return @out;
    }
}
