// Generated by kin from the source named below. Do not edit.
// source: flint.rt.seqcore

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Seqcore {
    /// Is this a SEQ? Six heap tags and nothing else.
    /// 
    /// Narrower than `sequential?`, which also takes a vector and a map entry,
    /// and narrower than what `seq` accepts, which takes those plus maps, sets
    /// and strings. Three different questions that are easy to conflate: the
    /// JVM's kind table once spelled `sequential?` as `is-vec or is-seq` --
    /// that predicate minus map entries -- so `(sequential? (first (seq m)))`
    /// was false while the method two below it said true.
    public static bool IsSeq(Rt rt, long v) {
        if (!Val.IsHeap(v)) {
            return false;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        return (t == Obj.TyCons) || (t == Obj.TyEmptyList) || (t == Obj.TyLazyseq) || (t == Obj.TyVecseq) || (t == Obj.TyStrseq) || (t == Obj.TyRange);
    }
    /// The count of `v` if it is known WITHOUT walking, else nil.
    /// 
    /// A VALUE and not an absent one: the answer goes straight into a slot that
    /// holds a fixnum or nil, so Rust's `Option<u32>` was being unwrapped into
    /// exactly that, one line later.
    /// 
    /// It answers `v`'s OWN count. Both ports folded the `+ 1` in here, which
    /// reads fine while `cons` is the only caller and is wrong for `seq-count`,
    /// which wants `v`'s own count -- so the `+ 1` moved to `cons`, and this is
    /// named for what it answers.
    /// How many values a range has, or NIL when it will not say.
    /// 
    /// FIXNUMS ONLY, and that is the whole subtlety. `range-empty` next door
    /// compares its endpoints in f64, which is right for a comparison and
    /// wrong for a count: two f64s near 1e18 are 128 apart, so the subtraction
    /// below would answer a size that is off by more than one. A fixnum is
    /// bounded at 2^47, so the difference cannot overflow an i64 either.
    /// 
    /// An UNBOUNDED range declines, and so does one whose size will not fit an
    /// int -- `count` answers an I32, and a wrong small number is worse than a
    /// walk that never finishes, which is what Clojure's `(count (range))`
    /// does too.
    internal static long RangeCount(Rt rt, long v) {
        long e = rt.Slot(v, 1);
        if (Val.IsNil(e)) {
            return Val.Nil;
        }
        long s0 = rt.Slot(v, 0);
        long st = rt.Slot(v, 2);
        if (!(Val.IsFixnum(s0) && (Val.IsFixnum(e) && Val.IsFixnum(st)))) {
            return Val.Nil;
        }
        long a = Val.AsFixnum(s0);
        long b = Val.AsFixnum(e);
        long k = Val.AsFixnum(st);
        // A zero step never advances, and `range-empty` calls that
        // empty rather than infinite.
        if (k == 0) {
            return Val.Fixnum(0 & 0xFFFFFFFFL);
        }
        long n;
        n = 0;
        if (k > 0) {
            if (a < b) {
                n = ((b + (k - 1)) - a) / k;
            }
        } else if (a > b) {
            n = ((a + ((0 - k) - 1)) - b) / (0 - k);
        }
        if (n > 2147483647) {
            return Val.Nil;
        }
        return Val.Fixnum(n & 0xFFFFFFFFL);
    }
    public static long CountHint(Rt rt, long v) {
        if (Val.IsNil(v)) {
            return Val.Fixnum(0 & 0xFFFFFFFFL);
        }
        if (!Val.IsHeap(v)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if (t == Obj.TyEmptyList) {
            return Val.Fixnum(0 & 0xFFFFFFFFL);
        }
        if (t == Obj.TyCons) {
            return rt.Slot(v, C_COUNT);
        }
        if (t == Obj.TyVec) {
            return Val.Fixnum(Vec.Count(rt, v) & 0xFFFFFFFFL);
        }
        // A RANGE KNOWS ITS SIZE. Clojure's Range is Counted; this walked
        // instead, so `(count (range 2000000))` cost 11.92s against a
        // 1.40s baseline for every other accessor -- two million steps to
        // answer what start, end and step already say.
        if (t == Obj.TyRange) {
            return RangeCount(rt, v);
        }
        return Val.Nil;
    }
    /// `(cons head tail)`: a cell, counted when the tail's count is known.
    /// 
    /// Named `cons` and not `cons-cell`: it is what every runtime already calls
    /// it, and a generated name that differs from the one 40 call sites use is
    /// a rename dressed up as a port.
    public static long Cons(Rt rt, long head, long tail) {
        int @base = rt.Mark();
        int h = rt.Push(head);
        int t = rt.Push(tail);
        long a = rt.Alloc(Obj.TyCons, 4);
        if (a == 0) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        long hint = CountHint(rt, rt.R(t));
        rt.SetSlot(a, C_FIRST, rt.R(h));
        rt.SetSlot(a, C_REST, rt.R(t));
        rt.SetSlot(a, C_META, Val.Nil);
        // The count of the CELL, which is the tail's plus one. Nil when
        // the tail's is unknown, and then `count` walks.
        if (Val.IsFixnum(hint)) {
            rt.SetSlot(a, C_COUNT, Val.Fixnum((Val.AsFixnum(hint) + 1) & 0xFFFFFFFFL));
        } else {
            rt.SetSlot(a, C_COUNT, Val.Nil);
        }
        rt.PopTo(@base);
        return Val.Heap(a);
    }
    /// A list from `n` values rooted at `base`, last-first.
    /// 
    /// What a variadic arity folds its surplus arguments into -- and it must be
    /// a SEQ, not a vector: `clojure.core/list` is `[& xs] xs`, so a vector here
    /// makes `(list 1 2)` print as `[1 2]`, the right elements in the wrong
    /// shape.
    /// 
    /// THE LOOP COUNTS UP AND THE INDEX COUNTS DOWN. Rust wrote this as
    /// `for i in (0..n).rev()` and both ports as `for (i = n - 1; i >= 0; i--)`;
    /// kin's `for` is half-open and ASCENDING only. Converging the source is
    /// cheaper than a descending loop form -- one form, three targets, and the
    /// conses happen in the same order they did before.
    /// 
    /// `n` is tagged `I32` and not `RootIx`. It is a COUNT, and `RootIx` means
    /// an index into the shadow stack; borrowing it here would compile on all
    /// three and tell a reader something false, which is the reason `Ty` and
    /// `Cat` are two tags. The cast back to an index is `as-idx`, which is what
    /// Rust needs and what the ports spell as nothing at all.
    public static long ListFromRoots(Rt rt, int @base, int n) {
        int mk = rt.Mark();
        long empty = global::Flint.Rt.Seqs.EmptyList(rt);
        int ai = rt.Push(empty);
        // HOISTED: `empty-list` and `push` both take `&mut self` in Rust,
        // so nesting them is two mutable borrows at once.
        for (int i = 0; i < n; i++) {
            long x = rt.R(@base + ((n - 1) - i));
            long c = Cons(rt, x, rt.R(ai));
            rt.SetR(ai, c);
        }
        long @out = rt.R(ai);
        rt.PopTo(mk);
        return @out;
    }
}
