// Generated by kin from the source named below. Do not edit.
// source: flint.rt.seqwalk

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Seqs;
using static global::_3sln.Flint.Kgen.Rt.Vecread;

public static class Seqwalk {
    /// The first element of `v`, or nil when there is none.
    public static long First(Rt rt, long v) {
        long s = global::Flint.Rt.Seqs.Seq(rt, v);
        if (Val.IsNil(s)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(s));
        if (t == Obj.TyCons) {
            return rt.Slot(s, C_FIRST);
        }
        if (t == Obj.TyVecseq) {
            long coll = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            // A MAP ENTRY rides the same vecseq, read directly. A
            // TABLE rides it too and answers a ROW REF, which is the
            // one thing about a table seq that differs
            // (`doc/decisions/0026`).
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyMapentry) {
                return rt.Slot(coll, i);
            }
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyTable) {
                return Table.tableRef(rt, coll, i);
            }
            return Vec.Nth(rt, coll, i, Val.Nil);
        }
        if (t == Obj.TyStrseq) {
            return Str.Nth(rt, rt.Slot(s, 0), (int) Val.AsFixnum(rt.Slot(s, 1)), Val.Nil);
        }
        if (t == Obj.TyRange) {
            return rt.Slot(s, 0);
        }
        return Val.Nil;
    }
    /// The seq after the first element, or nil when it is exhausted.
    public static long Next(Rt rt, long v) {
        long s = global::Flint.Rt.Seqs.Seq(rt, v);
        if (Val.IsNil(s)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(s));
        if (t == Obj.TyCons) {
            return global::Flint.Rt.Seqs.Seq(rt, rt.Slot(s, C_REST));
        }
        if (t == Obj.TyVecseq) {
            long coll = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            int n;
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyMapentry) {
                n = 2;
            } else if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyTable) {
                n = Table.tableCount(rt, coll);
            } else {
                n = Vec.Count(rt, coll);
            }
            if ((i + 1) >= n) {
                return Val.Nil;
            }
            return Vecseq(rt, coll, i + 1);
        }
        if (t == Obj.TyStrseq) {
            long st = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            if ((i + 1) >= Str.CharLen(rt, st)) {
                return Val.Nil;
            }
            return Strseq(rt, st, i + 1);
        }
        if (t == Obj.TyRange) {
            // A FRESH range, not a mutated cursor: a range IS a value,
            // so walking one must not disturb anything else holding it.
            // HOISTED. `seq-of` and `range` both take `&mut self` in
            // Rust, so nesting them is two mutable borrows at once. The
            // other two targets read the hoisted form fine.
            long nstart = Num.Add(rt, rt.Slot(s, 0), rt.Slot(s, 2));
            long r = Range(rt, nstart, rt.Slot(s, 1), rt.Slot(s, 2));
            return global::Flint.Rt.Seqs.Seq(rt, r);
        }
        return Val.Nil;
    }
}
