// Generated by kin from the source named below. Do not edit.
// source: flint.rt.seqwalk

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Collvec;
using static global::_3sln.Flint.Kgen.Rt.Nouns;
using static global::_3sln.Flint.Kgen.Rt.Ropemeas;
using static global::_3sln.Flint.Kgen.Rt.Seqcore;
using static global::_3sln.Flint.Kgen.Rt.Seqs;
using static global::_3sln.Flint.Kgen.Rt.Tablemeta;
using static global::_3sln.Flint.Kgen.Rt.Tableref;
using static global::_3sln.Flint.Kgen.Rt.Vecread;

public static class Seqwalk {
    /// The first element of `v`, or nil when there is none.
    public static long First(Rt rt, long v) {
        long s = global::_3sln.Flint.Kgen.Rt.Seqwalk.Seq(rt, v);
        if (Val.IsNil(s)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(s));
        if (t == Obj.TyCons) {
            return rt.Slot(s, C_FIRST);
        }
        if (t == Obj.TyVecseq) {
            long coll = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            // A MAP ENTRY rides the same vecseq, read directly. A
            // TABLE rides it too and answers a ROW REF, which is the
            // one thing about a table seq that differs
            // (`doc/decisions/0026`).
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyMapentry) {
                return rt.Slot(coll, i);
            }
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyTable) {
                return Table.tableRef(rt, coll, i);
            }
            return Vec.Nth(rt, coll, i, Val.Nil);
        }
        if (t == Obj.TyStrseq) {
            return Str.Nth(rt, rt.Slot(s, 0), (int) Val.AsFixnum(rt.Slot(s, 1)), Val.Nil);
        }
        if (t == Obj.TyRange) {
            return rt.Slot(s, 0);
        }
        return Val.Nil;
    }
    /// The seq after the first element, or nil when it is exhausted.
    public static long Next(Rt rt, long v) {
        long s = global::_3sln.Flint.Kgen.Rt.Seqwalk.Seq(rt, v);
        if (Val.IsNil(s)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(s));
        if (t == Obj.TyCons) {
            return global::_3sln.Flint.Kgen.Rt.Seqwalk.Seq(rt, rt.Slot(s, C_REST));
        }
        if (t == Obj.TyVecseq) {
            long coll = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            int n;
            if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyMapentry) {
                n = 2;
            } else if (Obj.Ty(rt.gc.sp, Val.AsHeap(coll)) == Obj.TyTable) {
                n = Table.tableCount(rt, coll);
            } else {
                n = Vec.Count(rt, coll);
            }
            if ((i + 1) >= n) {
                return Val.Nil;
            }
            return Vecseq(rt, coll, i + 1);
        }
        if (t == Obj.TyStrseq) {
            long st = rt.Slot(s, 0);
            int i = (int) Val.AsFixnum(rt.Slot(s, 1));
            if ((i + 1) >= Str.SCount(rt, st)) {
                return Val.Nil;
            }
            return Strseq(rt, st, i + 1);
        }
        if (t == Obj.TyRange) {
            // A FRESH range, not a mutated cursor: a range IS a value,
            // so walking one must not disturb anything else holding it.
            // HOISTED. `seq-of` and `range` both take `&mut self` in
            // Rust, so nesting them is two mutable borrows at once. The
            // other two targets read the hoisted form fine.
            long nstart = Num.Add(rt, rt.Slot(s, 0), rt.Slot(s, 2));
            long r = Range(rt, nstart, rt.Slot(s, 1), rt.Slot(s, 2));
            return global::_3sln.Flint.Kgen.Rt.Seqwalk.Seq(rt, r);
        }
        return Val.Nil;
    }
    /// `rest`: the seq after the first element, and NEVER nil.
    /// 
    /// Clojure's rule, and the difference from `next` is the whole of it: an
    /// exhausted `rest` is the empty list, so `(rest (rest [1]))` is `()` and
    /// keeps being seqable, where `next` answers nil and stops.
    public static long Rest(Rt rt, long v) {
        long n = Next(rt, v);
        if (Val.IsNil(n)) {
            return global::Flint.Rt.Seqs.EmptyList(rt);
        }
        return n;
    }
    /// Force a lazy seq to whatever it actually is, and CACHE that in it.
    /// 
    /// A thunk already run leaves `LS_THUNK` nil and the answer in `LS_SEQ`, so
    /// forcing twice runs nothing twice -- which is what makes a lazy seq a
    /// value rather than a generator.
    /// 
    /// The loop is for CHAINED lazy seqs: a thunk may answer another lazy seq,
    /// and that one another, and only the end of the chain is concrete.
    /// 
    /// The cursor lives in the ROOT throughout. Rust used to hold it in a host
    /// local with a `set_r` alongside -- correct, because the local was always
    /// overwritten by the result of the call that could have moved it, but
    /// correct by an argument the reader has to rebuild each time. Both ports
    /// already did it this way.
    public static long Force(Rt rt, long ls) {
        long thunk = rt.Slot(ls, LS_THUNK);
        if (Val.IsNil(thunk)) {
            return rt.Slot(ls, LS_SEQ);
        }
        int @base = rt.Mark();
        int li = rt.Push(ls);
        long firstForced = rt.Call(thunk, System.Array.Empty<long>());
        int vi = rt.Push(firstForced);
        // HOISTED, both calls: `push`, `set-r` and `invoke-thunk` all
        // take `&mut self` in Rust, so nesting an invoke inside either
        // is two mutable borrows at once.
        while (Val.IsHeap(rt.R(vi)) && (Obj.Ty(rt.gc.sp, Val.AsHeap(rt.R(vi))) == Obj.TyLazyseq)) {
            long t2 = rt.Slot(rt.R(vi), LS_THUNK);
            if (Val.IsNil(t2)) {
                rt.SetR(vi, rt.Slot(rt.R(vi), LS_SEQ));
                break;
            }
            long forced = rt.Call(t2, System.Array.Empty<long>());
            rt.SetR(vi, forced);
        }
        long cur = rt.R(vi);
        long l = rt.R(li);
        rt.PopTo(@base);
        rt.SetSlot(Val.AsHeap(l), LS_THUNK, Val.Nil);
        rt.SetSlot(Val.AsHeap(l), LS_SEQ, cur);
        return cur;
    }
    /// How many elements `v` has -- asking first, walking only if it must.
    /// 
    /// THE ASK IS THE POINT, and it is what both ports were missing. A vector,
    /// a map, a counted cons chain all know their size without being walked,
    /// and `count-hint` answers it; only when the answer is nil does this walk.
    /// Rust had the fast path and the JVM and CLR did not, so `(count v)` was
    /// O(1) on native and O(n) on both ports -- the same function, a different
    /// complexity class, which is not a difference a conform diff can see
    /// because both answers are right.
    /// 
    /// The cursor lives in the ROOT, not a host local: `next` forces a lazy
    /// seq, forcing allocates, and `doc/decisions/0031` is that a value in a
    /// host local does not survive an allocation.
    public static int SeqCount(Rt rt, long v) {
        long hint = CountHint(rt, v);
        if (Val.IsFixnum(hint)) {
            return (int) Val.AsFixnum(hint);
        }
        int @base = rt.Mark();
        long s = global::_3sln.Flint.Kgen.Rt.Seqwalk.Seq(rt, v);
        int ci = rt.Push(s);
        // HOISTED: `seq-of` and `push` both take `&mut self` in Rust.
        int n;
        n = 0;
        while (!Val.IsNil(rt.R(ci))) {
            n += 1;
            long nx = Next(rt, rt.R(ci));
            rt.SetR(ci, nx);
        }
        rt.PopTo(@base);
        return n;
    }
    /// The seq of `v`, or NIL when there is nothing to walk.
    /// 
    /// NO `case`, for the reason `nouns.kin` gives: hole 3 is open, and these
    /// arms are mutually exclusive so an early `return` leaves nothing to fall
    /// through to.
    /// 
    /// ITERATING A TABLE HANDS BACK REFS, one per row, materialising nothing --
    /// which is the point of the ref type and not a detail of it (`0026`). It
    /// rides on `TY_VECSEQ` because a table is indexed and counted exactly as a
    /// vector is; only `first` differs, and it differs by calling `table-ref`.
    /// 
    /// A REF MATERIALISES HERE AND ONLY HERE. `seq`, `=` and `hash` all want the
    /// whole row and each is O(columns) anyway; the paths that must stay cheap --
    /// `get` and `(:name row)` -- never come through.
    public static long Seq(Rt rt, long v) {
        if (Val.IsNil(v)) {
            return Val.Nil;
        }
        if (IsString(rt, v)) {
            // CODE POINTS, matching the index the strseq holds.
            if (Str.SCount(rt, v) == 0) {
                return Val.Nil;
            }
            return Strseq(rt, v, 0);
        }
        if (!Val.IsHeap(v)) {
            return Val.Nil;
        }
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if (t == Obj.TyEmptyList) {
            return Val.Nil;
        }
        if ((t == Obj.TyCons) || ((t == Obj.TyVecseq) || (t == Obj.TyStrseq))) {
            return v;
        }
        if (t == Obj.TyRange) {
            if (RangeEmpty(rt, v)) {
                return Val.Nil;
            }
            return v;
        }
        if (t == Obj.TyLazyseq) {
            long s = Force(rt, v);
            if (Val.IsNil(s)) {
                return Val.Nil;
            }
            return Seq(rt, s);
        }
        if (t == Obj.TyVec) {
            if (Vec.Count(rt, v) == 0) {
                return Val.Nil;
            }
            return Vecseq(rt, v, 0);
        }
        if (t == Obj.TyMapentry) {
            return Vecseq(rt, v, 0);
        }
        if (t == Obj.TyTable) {
            if (Table.tableCount(rt, v) == 0) {
                return Val.Nil;
            }
            return Vecseq(rt, v, 0);
        }
        if (t == Obj.TyTableref) {
            long m = global::Flint.Rt.Table.refToMap(rt, v);
            return Seq(rt, m);
        }
        if ((t == Obj.TyArraymap) || (t == Obj.TyHashmap)) {
            long ents = Maps.EntryVector(rt, v);
            if (Val.IsNil(ents)) {
                return Val.Nil;
            }
            if (Vec.Count(rt, ents) == 0) {
                return Val.Nil;
            }
            return Vecseq(rt, ents, 0);
        }
        if (t == Obj.TySet) {
            long ents = Sets.ElementVector(rt, v);
            if (Val.IsNil(ents)) {
                return Val.Nil;
            }
            if (Vec.Count(rt, ents) == 0) {
                return Val.Nil;
            }
            return Vecseq(rt, ents, 0);
        }
        // REFUSED, NOT NIL. This answered NIL and both ports threw, so
        // `(seq (atom 1))` was nil here and an exception there -- a reachable
        // divergence, and the ports are the ones matching Clojure, which
        // refuses anything it cannot make an ISeq from.
        string what = Describe(rt, v);
        return rt.ThrowStr("IllegalArgumentException", "seq over " + what + " needs more of the data structures");
    }
}
