// Generated by kin from the source named below. Do not edit.
// source: flint.rt.tablekind

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;

public static class Tablekind {
    /// The kind of a value, as the keyword protocol dispatch uses.
    /// 
    /// A CLOSED SET. `0005` says a value a guest can hold needs a kind of its
    /// own or it cannot be dispatched on at all -- so `:other` is not a kind,
    /// it is the ABSENCE of one, and four types answered it until the printer
    /// moved onto a protocol and the hole showed. An `extend-protocol :other`
    /// written for one of them would have caught all of them, and every future
    /// type besides.
    public static long KindOf(Rt rt, long v) {
        if (Val.IsNil(v)) {
            return Str.Keyword(rt, null, "nil");
        }
        if (Val.IsBool(v)) {
            return Str.Keyword(rt, null, "boolean");
        }
        if (Val.IsDouble(v)) {
            return Str.Keyword(rt, null, "number");
        }
        if (Val.IsFixnum(v)) {
            return Str.Keyword(rt, null, "number");
        }
        if (Val.IsInlineStr(v)) {
            return Str.Keyword(rt, null, "string");
        }
        if (Val.IsInlineKw(v)) {
            return Str.Keyword(rt, null, "keyword");
        }
        if (!Val.IsHeap(v)) {
            return Str.Keyword(rt, null, "other");
        }
        // NO `case`, and for the reason `nouns.kin` gives: hole 3 is still
        // open, and the chain costs nothing here. These arms are mutually
        // exclusive, so an early `return` leaves nothing to fall through
        // to -- and a `case` whose arms are `return` statements renders as
        // a Rust `match` whose arms are statements, which is not Rust.
        int t = Obj.Ty(rt.gc.sp, Val.AsHeap(v));
        if ((t == Obj.TyStr) || (t == Obj.TyRope)) {
            return Str.Keyword(rt, null, "string");
        }
        if (t == Obj.TyKw) {
            return Str.Keyword(rt, null, "keyword");
        }
        if (t == Obj.TySym) {
            return Str.Keyword(rt, null, "symbol");
        }
        if (t == Obj.TyBigint) {
            return Str.Keyword(rt, null, "number");
        }
        if ((t == Obj.TyVec) || (t == Obj.TyMapentry)) {
            return Str.Keyword(rt, null, "vector");
        }
        if ((t == Obj.TyArraymap) || (t == Obj.TyHashmap) || (t == Obj.TyTableref)) {
            return Str.Keyword(rt, null, "map");
        }
        if (t == Obj.TySet) {
            return Str.Keyword(rt, null, "set");
        }
        if ((t == Obj.TyCons) || (t == Obj.TyEmptyList) || (t == Obj.TyLazyseq) || (t == Obj.TyVecseq) || (t == Obj.TyStrseq) || (t == Obj.TyRange) || (t == Obj.TyIterseq) || (t == Obj.TyChunkseq)) {
            return Str.Keyword(rt, null, "list");
        }
        if ((t == Obj.TyClosure) || (t == Obj.TyNativefn) || (t == Obj.TyMultifn)) {
            return Str.Keyword(rt, null, "fn");
        }
        if (t == Obj.TyPort) {
            return Str.Keyword(rt, null, "port");
        }
        if (t == Obj.TyThread) {
            return Str.Keyword(rt, null, "thread");
        }
        if (t == Obj.TyAtom) {
            return Str.Keyword(rt, null, "atom");
        }
        if (t == Obj.TyVar) {
            return Str.Keyword(rt, null, "var");
        }
        if (t == Obj.TyRegex) {
            return Str.Keyword(rt, null, "regex");
        }
        if (t == Obj.TyExinfo) {
            return Str.Keyword(rt, null, "exception");
        }
        if (t == Obj.TyTagged) {
            return Str.Keyword(rt, null, "tagged");
        }
        if (t == Obj.TyOpaque) {
            return Str.Keyword(rt, null, "opaque");
        }
        if ((t == Obj.TyBytes) || (t == Obj.TyBrope) || (t == Obj.TyTbytes)) {
            return Str.Keyword(rt, null, "bytes");
        }
        if (t == Obj.TyDelay) {
            return Str.Keyword(rt, null, "delay");
        }
        if (t == Obj.TyVolatile) {
            return Str.Keyword(rt, null, "volatile");
        }
        if (t == Obj.TySchema) {
            return Str.Keyword(rt, null, "schema");
        }
        if (t == Obj.TyTable) {
            return Str.Keyword(rt, null, "table");
        }
        return Str.Keyword(rt, null, "other");
    }
    /// Is `t` a type a schema may declare?
    public static bool KnownType(Rt rt, long t) {
        if (t == Str.Keyword(rt, null, "int")) {
            return true;
        }
        if (t == Str.Keyword(rt, null, "double")) {
            return true;
        }
        if (t == Str.Keyword(rt, null, "string")) {
            return true;
        }
        if (t == Str.Keyword(rt, null, "bool")) {
            return true;
        }
        if (t == Str.Keyword(rt, null, "keyword")) {
            return true;
        }
        if (t == Str.Keyword(rt, null, "any")) {
            return true;
        }
        return false;
    }
    /// Does `v` belong in a column of type `t`?
    /// 
    /// `:any` TAKES ANYTHING, which is the escape hatch a closed schema needs to
    /// stay usable: a column that genuinely holds mixed values should say so
    /// rather than force the table open.
    public static bool TypeOk(Rt rt, long t, long v) {
        if (t == Str.Keyword(rt, null, "any")) {
            return true;
        }
        // `is-int` and NOT `is-fixnum`: a big integer is an integer, and a
        // column declared `:int` has to take one.
        if (t == Str.Keyword(rt, null, "int")) {
            return Num.IsInt(rt, v);
        }
        if (t == Str.Keyword(rt, null, "double")) {
            return Val.IsDouble(v);
        }
        if (t == Str.Keyword(rt, null, "string")) {
            return Str.IsString(rt, v);
        }
        if (t == Str.Keyword(rt, null, "bool")) {
            return Val.IsBool(v);
        }
        if (t == Str.Keyword(rt, null, "keyword")) {
            return Str.IsKeyword(rt, v);
        }
        return false;
    }
}
