// Generated by kin from the source named below. Do not edit.
// source: flint.rt.vecroots

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;

public static class Vecroots {
    /// A vector of the `n` values rooted at `base`, in that order.
    public static long VecFromRoots(Rt rt, int @base, int n) {
        int mk = rt.Mark();
        long empty = Vec.Empty(rt);
        int vi = rt.Push(empty);
        // HOISTED, as in `list-from-roots`: nesting the constructor
        // inside `push` is two borrows of the runtime at once on Rust.
        for (int i = 0; i < n; i++) {
            long x = rt.R(@base + i);
            long nv = VecConj(rt, rt.R(vi), x);
            rt.SetR(vi, nv);
        }
        long @out = rt.R(vi);
        rt.PopTo(mk);
        return @out;
    }
    /// A map entry as a real two-element vector.
    /// 
    /// For the operations Clojure gives VECTOR semantics to an entry: `conj`
    /// appends and `assoc` replaces, and neither means anything on a pair that
    /// is still a `TY_MAPENTRY`. Slot 0 is the key and slot 1 the value;
    /// reaching for the wrong one gave `(assoc [:a 1] 0 :z)` the answer `[:z]`
    /// on one runtime, which is what named the confusion.
    public static long MapEntryAsVec(Rt rt, long e) {
        int @base = rt.Mark();
        // The two roots are the ARGUMENTS to `vec-from-roots`, so nothing
        // names them: the run is `(base, 2)` and the indices are implied
        // by it. Binding them would be two locals nothing reads.
        rt.Push(rt.Slot(e, 0));
        rt.Push(rt.Slot(e, 1));
        long @out = VecFromRoots(rt, @base, 2);
        rt.PopTo(@base);
        return @out;
    }
}
