// Generated by kin from the source named below. Do not edit.
// source: flint.rt.wirescan

namespace _3sln.Flint.Kgen.Rt;

using System.Numerics;
using global::Flint.Rt;
using static global::Flint.Rt.Obj;
using static global::Flint.Rt.Maps;
using static global::Flint.Rt.Eq;
using static global::Flint.Rt.Seqs;
using static global::Flint.Rt.Vec;
using Rt = global::Flint.Rt.Rt;
using static global::_3sln.Flint.Kgen.Rt.Vecwrite;
using static global::_3sln.Flint.Kgen.Rt.Wirecore;

public static class Wirescan {
    /// Skip a length-prefixed run of bytes: a string, a blob, or a name.
    /// 
    /// `NO_NS` IS NOT A LENGTH. An absent namespace is `ffffffff` followed by
    /// nothing at all, and a walk that treated it as a count would skip four
    /// billion bytes and call the message truncated.
    public static bool WireSkipRun(Rt rt, long rd, bool absentable) {
        if (WireLeft(rt, rd) < 4) {
            return false;
        }
        int n = WireTakeU32(rt, rd, 0);
        if (absentable && (n == Codec.NO_NS)) {
            return true;
        }
        return WireSkip(rt, rd, n);
    }
    /// One value off `rd`, minting any port in it into the vector at `acc`.
    /// 
    /// False on a malformed encoding, which is how a message the format cannot
    /// read stays the HOST's error and is refused at the boundary rather than
    /// handed on to fail later inside a guest that cannot say where it came
    /// from.
    public static bool WireScanAt(Rt rt, long rd, int acc, int depth) {
        if (depth > 128) {
            return false;
        }
        if (WireLeft(rt, rd) < 1) {
            return false;
        }
        int tag = WireTakeU8(rt, rd, 255);
        // NIL, TRUE and FALSE are the tag and nothing else.
        if (tag <= 2) {
            return true;
        }
        // An INT or a DOUBLE is eight bytes of payload, and the walk does
        // not care which number they spell.
        if ((tag == 3) || (tag == 4)) {
            return WireSkip(rt, rd, 8);
        }
        // A STRING or a BLOB: a length and that many bytes. Neither can be
        // absent, so neither gets the `NO_NS` reading.
        if ((tag == 5) || (tag == 14)) {
            return WireSkipRun(rt, rd, false);
        }
        // A KEYWORD or a SYMBOL is a namespace, WHICH MAY BE ABSENT, then
        // a name, which may not.
        if ((tag == 6) || (tag == 7)) {
            if (!WireSkipRun(rt, rd, true)) {
                return false;
            }
            return WireSkipRun(rt, rd, false);
        }
        // A VECTOR, LIST or SET: a count, then that many values.
        if ((tag == 8) || ((tag == 9) || (tag == 11))) {
            if (WireLeft(rt, rd) < 4) {
                return false;
            }
            int n = WireTakeU32(rt, rd, 0);
            int i;
            i = 0;
            while ((uint) i < (uint) n) {
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                i += 1;
            }
            return true;
        }
        // A MAP OPENS TWICE ITS COUNT: `n` pairs are `2n` values.
        if (tag == 10) {
            if (WireLeft(rt, rd) < 4) {
                return false;
            }
            int n = WireTakeU32(rt, rd, 0);
            int i;
            i = 0;
            while ((uint) i < (uint) n) {
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                i += 1;
            }
            return true;
        }
        // A WRAPPER -- a tagged literal or metadata -- is two values.
        if ((tag == 17) || (tag == 19)) {
            if (!WireScanAt(rt, rd, acc, depth + 1)) {
                return false;
            }
            return WireScanAt(rt, rd, acc, depth + 1);
        }
        // A TABLE: a column count, a name and a type per column, then a ROW
        // count, then the cells column by column. The product is taken as
        // an I64 because two counts that each fit `u32` have one that does
        // not -- the same arithmetic the writer bounds.
        if (tag == 18) {
            if (WireLeft(rt, rd) < 4) {
                return false;
            }
            int ncols = WireTakeU32(rt, rd, 0);
            int c;
            c = 0;
            while ((uint) c < (uint) ncols) {
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                c += 1;
            }
            if (WireLeft(rt, rd) < 4) {
                return false;
            }
            int nrows = WireTakeU32(rt, rd, 0);
            long cells = ((long) ncols) * ((long) nrows);
            long k;
            k = 0;
            while (k < cells) {
                if (!WireScanAt(rt, rd, acc, depth + 1)) {
                    return false;
                }
                k += 1;
            }
            return true;
        }
        // AN OPAQUE is a host id and a label. It is an identity like a port
        // and is minted by the decoder rather than here, because unlike a
        // port nothing has to reach it before the guest reads.
        if (tag == 16) {
            if (WireLeft(rt, rd) < 8) {
                return false;
            }
            if (!WireSkip(rt, rd, 8)) {
                return false;
            }
            return WireSkipRun(rt, rd, false);
        }
        // A PORT, which is the whole reason this walk exists.
        if (tag == 15) {
            if (WireLeft(rt, rd) < 4) {
                return false;
            }
            int id = WireTakeU32(rt, rd, 0);
            long p = Conc.MintBridgePort(rt, (long) id);
            // NIL means this sandbox has no ports, so it cannot be
            // being handed one -- the same refusal the decoder gave.
            if (Val.IsNil(p)) {
                return false;
            }
            int pi = rt.Push(p);
            long grown = VecConj(rt, rt.R(acc), rt.R(pi));
            rt.PopTo(pi);
            rt.SetR(acc, grown);
            return true;
        }
        // AN UNKNOWN TAG is refused rather than skipped: there is no length
        // to skip by, so the walk cannot go on and must not pretend to.
        return false;
    }
}
