//! Embed flint's standard library, so a caller does not have to carry it.
//!
//! The artifacts in `dist/` are GENERATED by `bin/build-dist`, not tracked, so
//! this says so rather than letting `include_bytes!` fail with a path.
use std::{env, fs, path::Path};

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let dist = root.join("dist");
    for f in ["flintc.bytecode", "flint-runtime.wasm", "flint-runtime-aot.wasm",
              "slots.json", "slots-aot.json"] {
        if !dist.join(f).exists() {
            panic!("dist/{f} is missing. It is generated: run `bin/build-dist` first.");
        }
    }
    println!("cargo:rerun-if-changed={}", dist.display());
    println!("cargo:rerun-if-changed={}", root.join("lib").display());

    let mut entries: Vec<(String, String)> = Vec::new();
    fn walk(dir: &Path, prefix: &str, out: &mut Vec<(String, String)>) {
        let mut names: Vec<_> = fs::read_dir(dir).unwrap().filter_map(|e| e.ok()).collect();
        names.sort_by_key(|e| e.path());
        for e in names {
            let p = e.path();
            let name = p.file_name().unwrap().to_string_lossy().to_string();
            let rel = if prefix.is_empty() { name.clone() } else { format!("{prefix}/{name}") };
            if p.is_dir() {
                walk(&p, &rel, out);
            } else if rel.ends_with(".cljc") || rel.ends_with(".clj") {
                out.push((rel, fs::read_to_string(&p).unwrap()));
            }
        }
    }
    walk(&root.join("lib"), "", &mut entries);

    let mut src = String::from("[\n");
    for (path, body) in &entries {
        src.push_str(&format!("  ({path:?}, {body:?}),\n"));
    }
    src.push_str("]\n");
    fs::write(Path::new(&env::var("OUT_DIR").unwrap()).join("stdlib.rs"), src).unwrap();
}
