// Generated by kin from the source named below. Do not edit.
// source: flint.rt.collnode

namespace flint.rt;

using System.Numerics;
using Flint.Rt;
using static Flint.Rt.Obj;
using static Flint.Rt.Maps;
using static Flint.Rt.Eq;
using static Flint.Rt.Seqs;
using static flint.rt.Assoc;
using static flint.rt.Champ;
using static flint.rt.Copies;
using static flint.rt.Dissoc;
using static flint.rt.Eq;
using static flint.rt.Eqalloc;
using static flint.rt.Find;
using static flint.rt.Hash;
using static flint.rt.Interns;
using static flint.rt.Merge;
using static flint.rt.Nodeclass;
using static flint.rt.Pike;
using static flint.rt.Seqs;
using static flint.rt.Unsigned;

public static class Collnode {
    static long CnNew(Rt rt, int h, int npairs, long edit) {
        // `edit` is rooted across the allocation and read back after it:
        // `alloc` collects, and a host local does not survive that.
        int e = rt.Push(edit);
        long a = rt.Alloc(Obj.TyCollnode, CN_BASE + (2 * npairs));
        long ed = rt.R(e);
        rt.PopTo(e);
        if (a == 0) {
            return Val.Nil;
        }
        rt.SetSlot(a, CN_EDIT, ed);
        rt.SetSlot(a, CN_HASH, Val.Fixnum(h & 0xFFFFFFFFL));
        return Val.Heap(a);
    }
    static int CnCount(Rt rt, long n) {
        return (Olen(rt, n) - CN_BASE) / 2;
    }
    static int CnHash(Rt rt, long n) {
        return (int) Val.AsFixnum(rt.Slot(n, CN_HASH));
    }
    static long CnKey(Rt rt, long n, int i) {
        return rt.Slot(n, CN_BASE + (2 * i));
    }
    static long CnVal(Rt rt, long n, int i) {
        return rt.Slot(n, (CN_BASE + (2 * i)) + 1);
    }
    /// A BITMAP NODE, allocated and stamped with its two maps.
    public static long BnNew(Rt rt, int datamap, int nodemap, long edit) {
        int ne = System.Numerics.BitOperations.PopCount((uint)(datamap));
        int nn = System.Numerics.BitOperations.PopCount((uint)(nodemap));
        int e = rt.Push(edit);
        long a = rt.Alloc(Obj.TyBmnode, (BN_BASE + (2 * ne)) + nn);
        long ed = rt.R(e);
        rt.PopTo(e);
        if (a == 0) {
            return Val.Nil;
        }
        rt.SetSlot(a, BN_EDIT, ed);
        rt.SetSlot(a, BN_DATAMAP, Val.Fixnum(datamap & 0xFFFFFFFFL));
        rt.SetSlot(a, BN_NODEMAP, Val.Fixnum(nodemap & 0xFFFFFFFFL));
        return Val.Heap(a);
    }
    /// A COLLISION NODE copied with one value replaced.
    public static long CnCopySetVal(Rt rt, long n, int i, long val, long edit) {
        int cnt = CnCount(rt, n);
        int @base = rt.Mark();
        int ni = rt.Push(n);
        int vi = rt.Push(val);
        int ei = rt.Push(edit);
        long @out = CnNew(rt, CnHash(rt, rt.R(ni)), cnt, rt.R(ei));
        if (Val.IsNil(@out)) {
            rt.PopTo(@base);
            return Val.Nil;
        }
        int oi = rt.Push(@out);
        for (int k = 0; k < cnt; k++) {
            rt.SetSlot(Val.AsHeap(rt.R(oi)), CN_BASE + (2 * k), CnKey(rt, rt.R(ni), k));
            rt.SetSlot(Val.AsHeap(rt.R(oi)), (CN_BASE + (2 * k)) + 1, CnVal(rt, rt.R(ni), k));
        }
        rt.SetSlot(Val.AsHeap(rt.R(oi)), (CN_BASE + (2 * i)) + 1, rt.R(vi));
        long res = rt.R(oi);
        rt.PopTo(@base);
        return res;
    }
}
