// Generated by kin from the source named below. Do not edit.
// source: flint.rt.nodeclass

namespace flint.rt;

using System.Numerics;
using Flint.Rt;
using static Flint.Rt.Obj;
using static Flint.Rt.Maps;
using static Flint.Rt.Eq;
using static Flint.Rt.Seqs;
using static flint.rt.Champ;

public static class Nodeclass {
    internal static bool IsBmnode(Rt rt, long n) {
        return Obj.Ty(rt.gc.sp, Val.AsHeap(n)) == Obj.TyBmnode;
    }
    /// EMPTY / ONE / MORE, the CHAMP size predicate that drives collapsing.
    internal static int NodeSizeClass(Rt rt, long n) {
        // A collision node always holds at least two pairs.
        if (!IsBmnode(rt, n)) {
            return 2;
        }
        int dm = BnDatamap(rt, n);
        int nm = BnNodemap(rt, n);
        if (nm != 0) {
            return 2;
        }
        int c = System.Numerics.BitOperations.PopCount((uint)(dm));
        if (c == 0) {
            return 0;
        }
        if (c == 1) {
            return 1;
        }
        return 2;
    }
}
