// Generated by kin from the source named below. Do not edit.
// source: flint.rt.atoms

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Nouns.*;
import static com._3sln.flint.kgen.rt.Seqwalk.*;

public final class Atoms {
    /// A fresh atom holding `v`.
    public static long newAtom(Rt rt, long v) {
        int base = rt.mark();
        int vi = rt.push(v);
        long a = Conc.newObj(rt, TY_ATOM, 2);
        if (Val.isNil(a)) {
            rt.popTo(base);
            return Val.NIL;
        }
        // READ BACK FROM THE ROOT: the allocation may have moved it (0031).
        rt.setSlot(Val.asHeap(a), 0, rt.r(vi));
        rt.setSlot(Val.asHeap(a), 1, Val.NIL);
        rt.popTo(base);
        return a;
    }
    /// Is `at` a box that can be reset -- an atom or a volatile?
    /// 
    /// A DELAY IS NOT. It has no set operation: the whole point is that it is
    /// computed once and then fixed, so `reset!` on one would be undoing the
    /// only guarantee it makes.
    public static boolean isResettable(Rt rt, long at) {
        if (!Val.isHeap(at)) {
            return false;
        }
        int t = ty(rt.gc.sp, Val.asHeap(at));
        return (t == TY_ATOM) || (t == TY_VOLATILE);
    }
    /// Read the box.
    /// 
    /// A DELAY RUNS ITS THUNK ONCE. The thunk slot is cleared BEFORE the result
    /// is stored, so a delay that has run holds no reference to the code that
    /// produced it -- and the cleared slot is also how the next `deref` knows
    /// not to run it again.
    public static long deref(Rt rt, long v) {
        if (Val.isHeap(v)) {
            int t = ty(rt.gc.sp, Val.asHeap(v));
            if ((t == TY_ATOM) || (t == TY_VOLATILE)) {
                return rt.slot(v, 0);
            }
            if (t == TY_DELAY) {
                long thunk = rt.slot(v, 0);
                if (Val.isNil(thunk)) {
                    return rt.slot(v, 1);
                }
                int base = rt.mark();
                int vi = rt.push(v);
                int ti = rt.push(thunk);
                long res = rt.invokeRoots(rt.r(ti), ti, 0);
                if (!Val.isNil(rt.thrown)) {
                    rt.popTo(base);
                    return Val.NIL;
                }
                // THE DELAY IS RE-READ FROM ITS ROOT: running the
                // thunk may have collected, and the box could have
                // moved under a host local.
                rt.setSlot(Val.asHeap(rt.r(vi)), 0, Val.NIL);
                rt.setSlot(Val.asHeap(rt.r(vi)), 1, res);
                rt.popTo(base);
                return res;
            }
        }
        String what = describe(rt, v);
        return rt.throwStr("ClassCastException", "cannot deref " + what);
    }
    /// Set the atom to `next` only if it still holds `expect`.
    /// 
    /// THE PRIMITIVE `swap!` IS BUILT FROM. `swap!` used to be `(reset! a (f
    /// (deref a)))` -- a read-modify-write with no atomicity, which loses
    /// updates the moment two threads are inside it at once, and loses them
    /// SILENTLY: the counter is simply smaller than it should be. That was
    /// invisible while one thread ran a sandbox and became reachable the day two
    /// could (`drivers`).
    /// 
    /// COMPARES BY IDENTITY, as Clojure's does. A value-equal but distinct
    /// object means someone else has been here, and the retry is cheaper than a
    /// deep comparison on every attempt.
    public static long compareAndSetAtom(Rt rt, long at, long expect, long next) {
        if (!isResettable(rt, at)) {
            String what = describe(rt, at);
            return rt.throwStr("ClassCastException", "not an atom: " + what);
        }
        if (rt.slot(at, 0) == expect) {
            rt.setSlot(Val.asHeap(at), 0, next);
            return Val.TRUE;
        }
        return Val.FALSE;
    }
    /// Set the atom, and answer what was set.
    public static long resetAtom(Rt rt, long at, long v) {
        if (!isResettable(rt, at)) {
            String what = describe(rt, at);
            return rt.throwStr("ClassCastException", "not an atom: " + what);
        }
        rt.setSlot(Val.asHeap(at), 0, v);
        return v;
    }
}
