// Generated by kin from the source named below. Do not edit.
// source: flint.rt.bytenode

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Bytecore.*;

public final class Bytenode {
    /// A node over the `n` values already rooted at `base`.
    /// 
    /// THE CALLER PUSHES AND THE CALLER POPS. This roots nothing of its own, so
    /// the kids stay live across the allocation below because the caller's mark
    /// is holding them, not because this function pushed them again.
    /// 
    /// Depth comes off CHILD ZERO and the total is the children's counts added
    /// up -- the one walk a node exists to avoid doing later.
    public static long bNode(Rt rt, int base, int n) {
        int total;
        total = 0;
        for (int i = 0; i < n; i++) {
            total += bCount(rt, rt.r(base + i));
        }
        long a = rt.alloc(TY_BROPE, Bytes.BB_KIDS + n);
        if (a == 0) {
            return Val.NIL;
        }
        rt.setSlot(a, Bytes.BB_BYTES, Val.fixnum(total & 0xFFFFFFFFL));
        // NIL, not absent: `BB_FLAT` is the cached flattening and
        // `BB_HASH` the cached content hash, and both are computed on
        // demand. A slot left at whatever the allocator had is the bug
        // the probe fixtures were changed to make visible.
        rt.setSlot(a, Bytes.BB_FLAT, Val.NIL);
        rt.setSlot(a, Bytes.BB_HASH, Val.NIL);
        rt.setSlot(a, Bytes.BB_DEPTH, Val.fixnum((bDepth(rt, rt.r(base)) + 1) & 0xFFFFFFFFL));
        for (int i = 0; i < n; i++) {
            rt.setSlot(a, Bytes.BB_KIDS + i, rt.r(base + i));
        }
        return Val.heap(a);
    }
    /// `v`, wrapped in single-child nodes until it is `d` deep.
    /// 
    /// A leaf joining a deeper node is PROMOTED rather than sitting beside
    /// subtrees, because a node's children must all be the same depth.
    /// 
    /// NIL WHEN THE HEAP IS FULL, and without that this LOOPED FOREVER.
    /// `b-node` answers NIL when `alloc` fails; `b-depth` of NIL is 0, because
    /// NIL is not a heap value; so the loop below re-read a depth of 0 against
    /// a `d` it could never reach and span. A hang rather than a crash, in a
    /// runtime that meters untrusted code and therefore treats an exhausted
    /// heap as an ordinary condition.
    /// 
    /// `rope-lift` -- the same function for string trees -- has always checked
    /// (`kin/ropenode.kin`). This is the sibling that did not, found by
    /// diffing the two.
    public static long bWrapTo(Rt rt, long v, int d) {
        int base = rt.mark();
        int ci = rt.push(v);
        while (bDepth(rt, rt.r(ci)) < d) {
            // The cursor lives in the ROOT across `b-node`, which allocates.
            long wrapped = bNode(rt, ci, 1);
            if (Val.isNil(wrapped)) {
                rt.popTo(base);
                return Val.NIL;
            }
            rt.setR(ci, wrapped);
        }
        long out = rt.r(ci);
        rt.popTo(base);
        return out;
    }
}
