// Generated by kin from the source named below. Do not edit.
// source: flint.rt.byteflat

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Bytecore.*;

public final class Byteflat {
    /// Append every byte of `v` to the sink `s`.
    /// 
    /// Answers nothing: the bytes are the answer, and they go where the caller
    /// said. A value that is not a byte string appends nothing rather than
    /// refusing -- every caller here has already decided what `v` is.
    public static void bAppend(Rt rt, long v, int s) {
        if (!Val.isHeap(v)) {
            return;
        }
        int t = ty(rt.gc.sp, Val.asHeap(v));
        if (t == TY_BYTES) {
            rt.sinkPutRun(s, Val.asHeap(v) + Obj.HDR, olen(rt, v));
            return;
        }
        if (t != TY_BROPE) {
            return;
        }
        // ALREADY FLATTENED: one run rather than a descent.
        long flat = rt.slot(v, Bytes.BB_FLAT);
        if (!Val.isNil(flat)) {
            rt.sinkPutRun(s, Val.asHeap(flat) + Obj.HDR, olen(rt, flat));
            return;
        }
        int n = olen(rt, v) - Bytes.BB_KIDS;
        for (int i = 0; i < n; i++) {
            bAppend(rt, rt.slot(v, Bytes.BB_KIDS + i), s);
        }
    }
    /// Append bytes `[from, to)` of `v` to the sink `s`.
    /// 
    /// The range walk, and the reason it is not `b-append` over a slice: a slice
    /// allocates nodes to describe what to copy, and every caller here is about
    /// to copy anyway. Descending with the range instead costs nothing.
    /// 
    /// Both bounds are clamped INSIDE the leaf, because the descent narrows them
    /// per child and the arithmetic that does it can land outside a leaf whose
    /// recorded count disagrees with its length. That is a corrupt tree rather
    /// than a reachable input, and clamping answers wrong bytes where indexing
    /// off the end would answer whatever is next in the heap.
    public static void bAppendRange(Rt rt, long v, int from, int to, int s) {
        if (!Val.isHeap(v)) {
            return;
        }
        if (from >= to) {
            return;
        }
        int t = ty(rt.gc.sp, Val.asHeap(v));
        if (t == TY_BYTES) {
            // `leafn` and not `n`: C# refuses a local whose name is used in
            // an enclosing scope, even from a sibling branch, where Rust and
            // Java both allow it. One name per function is the portable
            // rule, and the emitter cannot rename for you without changing
            // what the source says.
            int leafn = olen(rt, v);
            int hi;
            int lo;
            hi = to;
            if (hi > leafn) {
                hi = leafn;
            }
            lo = from;
            if (lo > hi) {
                lo = hi;
            }
            rt.sinkPutRun(s, (Val.asHeap(v) + Obj.HDR) + lo, hi - lo);
            return;
        }
        if (t != TY_BROPE) {
            return;
        }
        long flat = rt.slot(v, Bytes.BB_FLAT);
        if (!Val.isNil(flat)) {
            bAppendRange(rt, flat, from, to, s);
            return;
        }
        int n = olen(rt, v) - Bytes.BB_KIDS;
        int pos;
        pos = 0;
        for (int i = 0; i < n; i++) {
            if (pos < to) {
                long k = rt.slot(v, Bytes.BB_KIDS + i);
                int kn = bCount(rt, k);
                if ((pos + kn) > from) {
                    int klo;
                    int khi;
                    klo = 0;
                    if (from > pos) {
                        klo = from - pos;
                    }
                    khi = to - pos;
                    if (khi > kn) {
                        khi = kn;
                    }
                    bAppendRange(rt, k, klo, khi, s);
                }
                pos += kn;
            }
        }
    }
    /// `v` as one flat leaf, CACHED in the node so the next ask is a slot read.
    /// 
    /// A leaf is already flat and answers itself. The cache is what makes
    /// repeated reads of one rope cheap rather than repeatedly O(n) -- and it is
    /// what `b-at` and `b-append` short-circuit through.
    public static long bFlatten(Rt rt, long v) {
        if (!Val.isHeap(v)) {
            return v;
        }
        if (ty(rt.gc.sp, Val.asHeap(v)) == TY_BYTES) {
            return v;
        }
        long cached = rt.slot(v, Bytes.BB_FLAT);
        if (!Val.isNil(cached)) {
            return cached;
        }
        // `v` LIVES IN THE ROOT across the allocation: `sink-bytes` allocates
        // the leaf, and the node this is about to write into would be stale
        // if it had been read into a host local before that.
        int base = rt.mark();
        int vi = rt.push(v);
        int s = rt.sinkOpen();
        bAppend(rt, rt.r(vi), s);
        long flat = rt.sinkBytes(s);
        rt.sinkClose(s);
        if (Val.isHeap(flat)) {
            rt.setSlot(Val.asHeap(rt.r(vi)), Bytes.BB_FLAT, flat);
        }
        rt.popTo(base);
        return flat;
    }
    /// `a` followed by `b`, copied into one flat leaf.
    /// 
    /// The tier below `FLAT_MAX`, where a tree costs more in metadata than the
    /// copy saves -- and the tier that makes building a byte string one piece at
    /// a time quadratic, which is what the transient is for.
    public static long bCopyConcat(Rt rt, long a, long b) {
        int s = rt.sinkOpen();
        bAppend(rt, a, s);
        bAppend(rt, b, s);
        long out = rt.sinkBytes(s);
        rt.sinkClose(s);
        return out;
    }
    /// Bytes `[from, to)` of `v`, copied into a fresh leaf.
    /// 
    /// What `SLICE_MIN` forces for a small range: a slice that SHARED would keep
    /// the whole section it came from alive, so below the threshold the range is
    /// copied on purpose. This is policy, not a fallback.
    public static long bCopyRange(Rt rt, long v, int from, int to) {
        int s = rt.sinkOpen();
        bAppendRange(rt, v, from, to, s);
        long out = rt.sinkBytes(s);
        rt.sinkClose(s);
        return out;
    }
}
