// Generated by kin from the source named below. Do not edit.
// source: flint.rt.collgen

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Bytecore.*;
import static com._3sln.flint.kgen.rt.Mapcore.*;
import static com._3sln.flint.kgen.rt.Maptrans.*;
import static com._3sln.flint.kgen.rt.Nouns.*;
import static com._3sln.flint.kgen.rt.Ropemeas.*;
import static com._3sln.flint.kgen.rt.Seqcore.*;
import static com._3sln.flint.kgen.rt.Seqwalk.*;
import static com._3sln.flint.kgen.rt.Setcore.*;
import static com._3sln.flint.kgen.rt.Tablemeta.*;
import static com._3sln.flint.kgen.rt.Tabletrans.*;
import static com._3sln.flint.kgen.rt.Vecassoc.*;
import static com._3sln.flint.kgen.rt.Vecread.*;
import static com._3sln.flint.kgen.rt.Vectrans.*;

public final class Collgen {
    /// How many things are in it.
    /// 
    /// NIL COUNTS 0, which is the first arm because it is the common one and
    /// because nil is not a heap value: everything below would have to say so
    /// again.
    public static int countOf(Rt rt, long v) {
        if (Val.isNil(v)) {
            return 0;
        }
        if (isString(rt, v)) {
            return sCount(rt, v);
        }
        if (Val.isHeap(v)) {
            int t = ty(rt.gc.sp, Val.asHeap(v));
            if (t == TY_VEC) {
                return Vec.count(rt, v);
            }
            // A MAP ENTRY COUNTS 2, and so does a tagged literal, which
            // reads like a two-key map (`0034`). The ports threw for a map
            // entry -- a value `(seq some-map)` hands out -- so ordinary
            // guest code could not count one.
            if ((t == TY_MAPENTRY) || (t == TY_TAGGED)) {
                return 2;
            }
            if (t == TY_TABLE) {
                return tableCount(rt, v);
            }
            if (t == TY_TTABLE) {
                return ttableCount(rt, v);
            }
            // A REF COUNTS ITS COLUMNS, because it is a map of them.
            if (t == TY_TABLEREF) {
                return schemaLen(rt, rt.slot(v, Table.RF_SCHEMA));
            }
            if ((t == TY_ARRAYMAP) || (t == TY_HASHMAP)) {
                return mapCount(rt, v);
            }
            if (t == TY_SET) {
                return setCount(rt, v);
            }
            if ((t == TY_BYTES) || (t == TY_BROPE)) {
                return bCount(rt, v);
            }
            if (t == TY_TVEC) {
                return tvecCount(rt, v);
            }
            if (t == TY_TMAP) {
                return tmapCount(rt, v);
            }
            if (t == TY_TSET) {
                return tsetCount(rt, v);
            }
            if (t == TY_EMPTY_LIST) {
                return 0;
            }
            if (isSeq(rt, v)) {
                return seqCount(rt, v);
            }
        }
        String what = describe(rt, v);
        rt.throwStr("UnsupportedOperationException", "count over " + what + " needs more of the data structures");
        return 0;
    }
    /// The collection one shorter at the end it is written from.
    /// 
    /// A VECTOR POPS ITS LAST and a list its first, which is the same word for
    /// two ends because it is the same word in Clojure: `pop` takes off
    /// whichever end `conj` puts on.
    public static long popOf(Rt rt, long coll) {
        // NIL POPS TO NIL, which is Clojure: `RT.pop` answers null for null
        // before it casts to `IPersistentStack`. This threw
        // `IllegalStateException: cannot pop nil`, and of the five places
        // flint answered differently from Clojure it was the only one where
        // flint was STRICTER -- and so the only one a working program could
        // meet by accident.
        if (Val.isNil(coll)) {
            return Val.NIL;
        }
        if (Val.isHeap(coll)) {
            int t = ty(rt.gc.sp, Val.asHeap(coll));
            if (t == TY_VEC) {
                if (Vec.count(rt, coll) == 0) {
                    return rt.throwStr("IllegalStateException", "cannot pop an empty vector");
                }
                return vecPop(rt, coll);
            }
            if (t == TY_EMPTY_LIST) {
                return rt.throwStr("IllegalStateException", "cannot pop an empty list");
            }
        }
        return rest(rt, coll);
    }
    /// The thing `pop` would take off, without taking it.
    /// 
    /// ANSWERS NIL RATHER THAN THROWING on an empty collection, which is the
    /// difference between it and `pop`: peeking at nothing is a question with
    /// an answer.
    public static long peekOf(Rt rt, long coll) {
        if (Val.isNil(coll)) {
            return Val.NIL;
        }
        if (Val.isHeap(coll)) {
            int t = ty(rt.gc.sp, Val.asHeap(coll));
            if (t == TY_VEC) {
                int n = Vec.count(rt, coll);
                if (n == 0) {
                    return Val.NIL;
                }
                return vecNth(rt, coll, n - 1, Val.NIL);
            }
            // A STACK OR NOTHING. Clojure's `peek` casts to
            // `IPersistentStack`, which a vector and a LIST are and a set,
            // a map, a string and every SEQ are not -- `(peek #{1})` was 1
            // here and is a ClassCastException there, and so are
            // `(peek (map inc [1]))` and `(peek "ab")`, which the
            // five-divergence table never listed because `seqshapes` only
            // asked about the set.
            // 
            // A CONS IS A LIST HERE. Clojure separates `PersistentList`
            // from `Cons` and refuses the second; flint has one list type
            // and refusing it would break `(peek (conj '(1) 2))`, which
            // Clojure accepts. So the line is drawn at seqs and
            // non-collections, which is where a program notices.
            if (t == TY_CONS) {
                return first(rt, coll);
            }
            if (t == TY_EMPTY_LIST) {
                return Val.NIL;
            }
            return rt.throwStr("ClassCastException", "peek wants a vector or a list");
        }
        return rt.throwStr("ClassCastException", "peek wants a vector or a list");
    }
    /// An empty collection of the same KIND, and NIL when there is no kind.
    /// 
    /// The shared singleton in each case, not a fresh allocation: an empty
    /// vector is three objects, and `(empty v)` is asked for exactly when a
    /// program is about to build something else.
    /// 
    /// A ROW REF ANSWERS THE EMPTY MAP, because a ref is a map. Native sent it
    /// to the empty LIST -- its arm named the two map tags and a ref is
    /// neither -- so `(empty row)` was `{}` on both ports and `()` on wasm.
    /// 
    /// AND THE LIST IS ONLY FOR A SEQ. Native answered `()` for any heap value
    /// it did not otherwise name, so `(empty "abc")` was `()` there and nil
    /// on both ports. Clojure answers nil, which is what a value with no empty
    /// of its own has.
    public static long emptyOf(Rt rt, long coll) {
        if (Val.isHeap(coll)) {
            int t = ty(rt.gc.sp, Val.asHeap(coll));
            if (t == TY_VEC) {
                return Vec.empty(rt);
            }
            if ((t == TY_ARRAYMAP) || (t == TY_HASHMAP)) {
                return com.flint.rt.Maps.empty(rt);
            }
            if (t == TY_TABLEREF) {
                return com.flint.rt.Maps.empty(rt);
            }
            if (t == TY_SET) {
                return Sets.empty(rt);
            }
            if (isSeq(rt, coll)) {
                return com.flint.rt.Seqs.emptyList(rt);
            }
        }
        return Val.NIL;
    }
}
