// Generated by kin from the source named below. Do not edit.
// source: flint.rt.eq

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;

public final class Eq {
    public static int category(Rt rt, long v) {
        if (!Val.isHeap(v)) {
            return CAT_SCALAR;
        }
        switch (ty(rt.gc.sp, Val.asHeap(v))) {
            case TY_CONS: case TY_EMPTY_LIST: case TY_LAZYSEQ: case TY_VECSEQ:
            case TY_STRSEQ: case TY_RANGE: case TY_VEC: case TY_MAPENTRY:
                return CAT_SEQUENTIAL;
            // A ROW REF is in the MAP category: it is `=` to a map with the
            // same entries, and `category` is what decides that
            // (`DECISIONS.md#tables`).
            case TY_ARRAYMAP: case TY_HASHMAP: case TY_TABLEREF:
                return CAT_MAP;
            case TY_SET:
                return CAT_SET;
            default:
                return CAT_SCALAR;
        }
    }
}
