// Generated by kin from the source named below. Do not edit.
// source: flint.rt.mainanswer

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Vecread.*;

public final class Mainanswer {
    /// The answer the thread a host started left behind.
    /// 
    /// THREAD 0 SPEAKS FOR THE PROGRAM. It is the thread the host started, so
    /// its outcome is the program's outcome; anything else still parked when
    /// the scheduler settles is waiting for something that is never coming.
    /// 
    /// A FAILURE GOES BACK ON `thrown`, AND THE ANSWER IS NIL. That is the
    /// whole point: `TH_RESULT` holds the error for a failed thread and the
    /// value for a finished one, so returning it either way hands the host a
    /// value it cannot classify. The boundary looks at `thrown` to decide
    /// status, and this is what puts it there.
    /// 
    /// NO SCHEDULER, OR NO THREAD 0, IS NIL rather than a throw. A program
    /// that never started a thread has no outcome to report, and inventing a
    /// failure for it would make an empty program look like a broken one.
    public static long mainAnswer(Rt rt) {
        long s = Conc.sched(rt);
        if (Val.isNil(s)) {
            return Val.NIL;
        }
        long ts = rt.slot(s, Conc.SC_THREADS);
        long th = vecNth(rt, ts, 0, Val.NIL);
        if (Val.isNil(th)) {
            return Val.NIL;
        }
        long r = rt.slot(th, Conc.TH_RESULT);
        long st = Val.asFixnum(rt.slot(th, Conc.TH_STATUS));
        if (st == Conc.ST_FAILED) {
            // STRAIGHT ACROSS, unwrapped. Nothing allocates between
            // the read and the write, which is what lets a heap value
            // pass through a field no root walk visits.
            rt.thrown = r;
            return Val.NIL;
        }
        return r;
    }
}
