// Generated by kin from the source named below. Do not edit.
// source: flint.rt.numdiv

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Numkind.*;

public final class Numdiv {
    /// Does `x / y` overflow? Only for the most negative integer over -1.
    /// 
    /// There is exactly one such pair, so the guard is a comparison rather
    /// than a host's checked-arithmetic idiom -- and the three hosts' idioms
    /// are what disagreed.
    public static boolean divOverflows(Rt rt, long x, long y) {
        return (x == Long.MIN_VALUE) && (y == -1);
    }
    /// `/`. Integer division that divides EVENLY yields an integer; one that
    /// does not yields a double.
    /// 
    /// That is a documented divergence from Clojure, which yields a Ratio.
    /// `doc/goals` records it; this is only where it happens.
    public static long numDiv(Rt rt, long a, long b) {
        if (bothInts(rt, a, b)) {
            long x = Num.i64Of(rt, a);
            long y = Num.i64Of(rt, b);
            if (y == 0) {
                return rt.throwStr("ArithmeticException", "Divide by zero");
            }
            // BEFORE THE REMAINDER, because `MIN % -1` overflows as surely
            // as `MIN / -1` does. Native asked the remainder first and
            // panicked.
            if (divOverflows(rt, x, y)) {
                return rt.throwStr("ArithmeticException", "integer overflow");
            }
            if ((x % y) == 0) {
                return Num.integer(rt, x / y);
            }
            return Val.ofDouble(((double) x) / ((double) y));
        }
        if (isNumber(rt, a) && isNumber(rt, b)) {
            return Val.ofDouble(Num.f64(rt, a) / Num.f64(rt, b));
        }
        return Num.notNumber(rt, a, b);
    }
    /// `quot`: integer division TOWARD ZERO, and no promotion to a double.
    public static long numQuot(Rt rt, long a, long b) {
        if (bothInts(rt, a, b)) {
            long x = Num.i64Of(rt, a);
            long y = Num.i64Of(rt, b);
            if (y == 0) {
                return rt.throwStr("ArithmeticException", "Divide by zero");
            }
            if (divOverflows(rt, x, y)) {
                return rt.throwStr("ArithmeticException", "integer overflow");
            }
            return Num.integer(rt, x / y);
        }
        if (isNumber(rt, a) && isNumber(rt, b)) {
            double x = Num.f64(rt, a);
            double y = Num.f64(rt, b);
            return Val.ofDouble(Num.trunc(x / y));
        }
        return Num.notNumber(rt, a, b);
    }
    /// `rem`: what `quot` leaves, with the sign of the DIVIDEND.
    /// 
    /// `MIN % -1` IS 0 and does not overflow as a value -- but computing it
    /// does on a host that checks, so the same guard stands and answers 0
    /// directly.
    public static long numRem(Rt rt, long a, long b) {
        if (bothInts(rt, a, b)) {
            long x = Num.i64Of(rt, a);
            long y = Num.i64Of(rt, b);
            if (y == 0) {
                return rt.throwStr("ArithmeticException", "Divide by zero");
            }
            if (divOverflows(rt, x, y)) {
                return Num.integer(rt, 0);
            }
            return Num.integer(rt, x % y);
        }
        if (isNumber(rt, a) && isNumber(rt, b)) {
            double x = Num.f64(rt, a);
            double y = Num.f64(rt, b);
            return Val.ofDouble(x - (Num.trunc(x / y) * y));
        }
        return Num.notNumber(rt, a, b);
    }
    /// Unary minus. The most negative integer has no positive counterpart.
    public static long numNeg(Rt rt, long a) {
        if (isInt(rt, a)) {
            long x = Num.i64Of(rt, a);
            if (x == Long.MIN_VALUE) {
                return rt.throwStr("ArithmeticException", "integer overflow");
            }
            return Num.integer(rt, 0 - x);
        }
        // MULTIPLY, do not subtract from zero. IEEE 754 says 0.0 - 0.0 is
        // +0.0, so negating zero by subtraction LOSES THE SIGN -- `(- 0.0)`
        // answered 0.0 where Clojure answers -0.0, on all three runtimes,
        // because this is generated. Multiplying by -1.0 is right for zero,
        // for NaN and for both infinities.
        if (Val.isDouble(a)) {
            return Val.ofDouble(-1.0 * Num.f64(rt, a));
        }
        return Num.notNumber(rt, a, a);
    }
}
