// Generated by kin from the source named below. Do not edit.
// source: flint.rt.numkind

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;

public final class Numkind {
    /// Is `v` an INTEGER -- a fixnum or a bigint?
    /// 
    /// The fixnum test comes first because it is a test on the value word and
    /// the other needs a tag read, and because almost every integer is one.
    public static boolean isInt(Rt rt, long v) {
        if (Val.isFixnum(v)) {
            return true;
        }
        if (!Val.isHeap(v)) {
            return false;
        }
        return ty(rt.gc.sp, Val.asHeap(v)) == TY_BIGINT;
    }
    /// Is `v` a NUMBER -- either integer tier, or a double?
    /// 
    /// The double first, for the same reason: it is the value-word test.
    public static boolean isNumber(Rt rt, long v) {
        return Val.isDouble(v) || isInt(rt, v);
    }
}
