// Generated by kin from the source named below. Do not edit.
// source: flint.rt.objsize

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;

public final class Objsize {
    /// Which of the three shapes `ty` has.
    /// 
    /// SLOTS UNLESS NAMED OTHERWISE, and the default is the safe one: a type
    /// the allocator has not heard of is laid out as values, so the collector
    /// traces it. Defaulting to RAW would hide a new type's references from
    /// the collector, and the failure would be a freed live object rather than
    /// a wasted word.
    /// 
    /// A STRING IS ITS OWN SHAPE because its bytes do not begin where every
    /// other object's body does -- `STR_DATA` and not `HDR`.
    /// 
    /// THE RAW FIVE ARE THE ALLOCATOR'S OWN, three of which no guest ever
    /// sees: `TY_FREE` is a hole in the old space and `TY_FWD` an object that
    /// has moved. Both are walked by the sweeper, so both must size correctly
    /// or the walk steps into the middle of the next object.
    public static int layoutOf(int ty) {
        if (ty == TY_STR) {
            return Obj.STR;
        }
        if ((ty == TY_BIGINT) || ((ty == TY_RAW) || ((ty == TY_BYTES) || ((ty == TY_FREE) || (ty == TY_FWD))))) {
            return Obj.RAW;
        }
        return Obj.VALS;
    }
    /// How many BYTES an object of `ty` with `len` occupies.
    /// 
    /// `len` MEANS DIFFERENT THINGS PER LAYOUT, which is the whole reason this
    /// is one function and not three call sites. For slots it is a COUNT and
    /// each is eight bytes wide; for the other two it is already a byte count.
    /// Reading it as bytes for a vector would size a ten-element vector at
    /// ten bytes and hand back an object the collector walks off the end of.
    /// 
    /// ONLY THE BYTE LAYOUTS ROUND. A slot count multiplied by eight is
    /// already a multiple of eight, so rounding it is a no-op that would only
    /// hide a mistake in the multiply; the two byte layouts round because a
    /// caller may ask for any length at all.
    /// 
    /// THE ANSWER IS BYTES AND THE CHARGE IS `>> 3`. The caller divides; this
    /// does not, because the sweeper walks in bytes and would step wrong on a
    /// size already divided.
    public static long sizeFor(int ty, int len) {
        int lay = layoutOf(ty);
        // WIDENED BEFORE THE ARITHMETIC. A length is 32-bit and an
        // address is 64; Java and C# widen silently and Rust does not,
        // so the conversion is said here rather than left to whichever
        // target happens to tolerate it. Native's copy says `len as
        // Addr` in the same three places.
        if (lay == Obj.VALS) {
            return Obj.HDR + (len * 8);
        }
        if (lay == Obj.STR) {
            return Obj.align8(Obj.STR_DATA + len);
        }
        return Obj.align8(Obj.HDR + len);
    }
}
