// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropecat

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Ropemeas.*;
import static com._3sln.flint.kgen.rt.Ropenode.*;

public final class Ropecat {
    /// How many children this node has.
    public static int ropeKids(Rt rt, long v) {
        return olen(rt, v) - Str.RP_KIDS;
    }
    /// How many levels of node stand above the leaves, 0 for a leaf itself.
    /// 
    /// Reads CHILD ZERO and recurses, which is exact because a node's children
    /// are all the same height -- the invariant `rope-lift` exists to keep.
    public static int ropeHeight(Rt rt, long v) {
        if (!isRope(rt, v)) {
            return 0;
        }
        return 1 + ropeHeight(rt, rt.slot(v, Str.RP_KIDS));
    }
    /// Graft `piece` onto the EDGE of `node`: the left edge when `front`, the
    /// right edge otherwise. NIL when it does not fit anywhere along that edge.
    /// 
    /// ONE FUNCTION FOR BOTH DIRECTIONS, because they are the same walk. The
    /// prepend side was first written as its own mirror of the append side and
    /// cost 2 090 bytes -- a second recursive descent, a second set of rebuilds
    /// and a second lift, to do the same three things at the other end. Shared,
    /// the second direction is a handful of branches: which child to descend,
    /// which way round the merge concatenates, and which end the new sibling
    /// goes.
    /// 
    /// THREE THINGS IN ORDER, deepest first. Room further down costs no depth;
    /// a leaf that can absorb `piece` costs no node either; and only when
    /// neither holds does it become a sibling, LIFTED to the height its
    /// siblings stand at or the tree goes ragged.
    /// 
    /// NIL when the edge is full at every level, which is the ONLY time
    /// `s-concat` adds one -- so depth grows O(log n) times over n joins
    /// rather than O(n/FANOUT) times.
    public static long ropeGraft(Rt rt, long node, long piece, boolean front) {
        if (!isRope(rt, node)) {
            return Val.NIL;
        }
        int n = ropeKids(rt, node);
        int base = rt.mark();
        int ni = rt.push(node);
        int pi = rt.push(piece);
        int edge;
        edge = n - 1;
        if (front) {
            edge = 0;
        }
        long kid = rt.slot(rt.r(ni), Str.RP_KIDS + edge);
        int ki = rt.push(kid);
        long fixed;
        fixed = Val.NIL;
        // DEEPEST FIRST: room further down costs no depth at all.
        if (isRope(rt, rt.r(ki))) {
            fixed = ropeGraft(rt, rt.r(ki), rt.r(pi), front);
        }
        // THEN MERGE BEFORE CREATE, which is the rule a CHAMP already
        // follows and this did not. `s-concat`'s copy tier asks whether
        // the WHOLE RESULT fits a leaf, so past FLAT_MAX every join,
        // however small, became its own leaf. The question that matters
        // is whether `piece` fits the leaf ALREADY THERE.
        if (Val.isNil(fixed)) {
            if (!isRope(rt, rt.r(ki))) {
                if (!isRope(rt, rt.r(pi))) {
                    if ((sBytes(rt, rt.r(ki)) + sBytes(rt, rt.r(pi))) <= Str.MERGE_MAX) {
                        if (front) {
                            fixed = Str.copyConcat(rt, rt.r(pi), rt.r(ki));
                        } else {
                            fixed = Str.copyConcat(rt, rt.r(ki), rt.r(pi));
                        }
                    }
                }
            }
        }
        if (!Val.isNil(fixed)) {
            int fi = rt.push(fixed);
            int kbase = rt.mark();
            for (int i = 0; i < n; i++) {
                if (i == edge) {
                    rt.push(rt.r(fi));
                } else {
                    rt.push(rt.slot(rt.r(ni), Str.RP_KIDS + i));
                }
            }
            long out = ropeNode(rt, kbase, n);
            rt.popTo(base);
            return out;
        }
        // THEN A SIBLING, if this node has room.
        if (n < Str.FANOUT) {
            int h = ropeHeight(rt, rt.r(ki));
            long lifted = ropeLift(rt, rt.r(pi), h);
            if (Val.isNil(lifted)) {
                rt.popTo(base);
                return Val.NIL;
            }
            int li = rt.push(lifted);
            int kbase = rt.mark();
            if (front) {
                rt.push(rt.r(li));
            }
            for (int i = 0; i < n; i++) {
                rt.push(rt.slot(rt.r(ni), Str.RP_KIDS + i));
            }
            if (!front) {
                rt.push(rt.r(li));
            }
            long out = ropeNode(rt, kbase, n + 1);
            rt.popTo(base);
            return out;
        }
        rt.popTo(base);
        return Val.NIL;
    }
    /// Append `b` into the rightmost subtree of `a` that has room.
    public static long ropeAppend(Rt rt, long a, long b) {
        return ropeGraft(rt, a, b, false);
    }
    /// Prepend `a` into the leftmost subtree of `b` that has room.
    /// 
    /// NOTE THE ARGUMENT ORDER: `a` is the piece and `b` is the tree, which is
    /// the reverse of `rope-append` and follows `s-concat`'s `a` then `b`.
    public static long ropePrepend(Rt rt, long a, long b) {
        return ropeGraft(rt, b, a, true);
    }
    /// `a` followed by `b`, as a string.
    public static long sConcat(Rt rt, long a, long b) {
        if (sBytes(rt, a) == 0) {
            return b;
        }
        if (sBytes(rt, b) == 0) {
            return a;
        }
        // Small enough that a tree would cost more in metadata than the copy
        // saves. This is the tier that must NOT be skipped.
        if ((sBytes(rt, a) + sBytes(rt, b)) <= Str.FLAT_MAX) {
            return Str.copyConcat(rt, a, b);
        }
        long appended = ropeAppend(rt, a, b);
        if (!Val.isNil(appended)) {
            return appended;
        }
        // AND THE OTHER END, before a level is added. Sharing the walk with
        // the append side is what made this affordable -- as its own mirror
        // it cost 2 090 bytes and was removed for it.
        if (!isRope(rt, a)) {
            long prepended = ropePrepend(rt, a, b);
            if (!Val.isNil(prepended)) {
                return prepended;
            }
        }
        // A NEW LEVEL, with THE SHORTER SIDE LIFTED to meet the taller.
        // 
        // This used to lift `b` by `rope-height(a)` outright, which is only
        // right when `b` is a LEAF -- the append case, where `b` is the new
        // piece. Reverse the arguments and it is wrong twice over: a short
        // `a` in front of a tall `b` lifts `b` by ZERO and builds
        // `[leaf, deep-rope]`, which is RAGGED.
        // 
        // That is the exact shape this file's header says was fixed for
        // append -- `[old, new]` with the whole old tree as a child, depth
        // growing linearly -- still live at the other end. Measured in the
        // probe: twelve appends of six bytes give height 3, twelve PREPENDS
        // of six bytes gave height 1 over a right-leaning chain, and
        // `rope-height` could not even report it because it reads child zero
        // and trusts that children are the same height.
        // 
        // AND IT IS NOW REACHABLE. The header says the ragged tree `never
        // showed while nothing indexed a rope, because every path flattened
        // first; the moment indexing descends instead, an O(n)-deep tree
        // makes the walk quadratic in a new place`. `str-index-of` descends
        // now, so this stopped being latent.
        int base = rt.mark();
        int ai = rt.push(a);
        int bi = rt.push(b);
        int ha = ropeHeight(rt, rt.r(ai));
        int hb = ropeHeight(rt, rt.r(bi));
        if (ha < hb) {
            long la = ropeLift(rt, rt.r(ai), hb - ha);
            if (Val.isNil(la)) {
                rt.popTo(base);
                return Val.NIL;
            }
            rt.setR(ai, la);
        }
        if (ha > hb) {
            long lb = ropeLift(rt, rt.r(bi), ha - hb);
            if (Val.isNil(lb)) {
                rt.popTo(base);
                return Val.NIL;
            }
            rt.setR(bi, lb);
        }
        int kbase = rt.mark();
        rt.push(rt.r(ai));
        rt.push(rt.r(bi));
        long out = ropeNode(rt, kbase, 2);
        rt.popTo(base);
        return out;
    }
}
