// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropeeq

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;

public final class Ropeeq {
    /// Do `a` and `b` hold the same bytes, whatever shape they are in?
    public static boolean treeEq(Rt rt, long a, long b) {
        // The same object is the same bytes, and the commonest case.
        if (a == b) {
            return true;
        }
        if (Str.sBytes(rt, a) != Str.sBytes(rt, b)) {
            return false;
        }
        int wa = rt.walkOpen(a);
        int wb = rt.walkOpen(b);
        // The current leaf of each side, and how far into it.
        long la;
        long lb;
        int pa;
        int pb;
        int na;
        int nb;
        boolean same;
        la = Val.NIL;
        lb = Val.NIL;
        pa = 0;
        pb = 0;
        na = 0;
        nb = 0;
        same = true;
        for (;;) {
            if (pa == na) {
                long v = rt.walkNext(wa);
                if (Val.isNil(v)) {
                    break;
                }
                // BOTH AT A BOUNDARY: peek the other side, and if it is
                // about to hand over the same object, skip it on both
                // without reading a byte. Only keep the peek if it paid.
                if (pb == nb) {
                    if (!rt.walkDone(wb)) {
                        int peek = rt.walkDup(wb);
                        long w = rt.walkNext(peek);
                        if (w == v) {
                            // IT PAID. Falling through here instead would
                            // take the leaf on this side and not the other,
                            // and two trees sharing a leaf would compare
                            // unequal -- which is how `b-eq` was wrong.
                            rt.walkTake(wb, peek);
                            rt.walkClose(peek);
                            continue;
                        } else {
                            rt.walkClose(peek);
                        }
                    }
                }
                la = v;
                pa = 0;
                na = rt.leafLen(v);
            }
            if (pb == nb) {
                long v = rt.walkNext(wb);
                if (Val.isNil(v)) {
                    break;
                }
                lb = v;
                pb = 0;
                nb = rt.leafLen(v);
            }
            int ra = na - pa;
            int rb = nb - pb;
            int n;
            n = ra;
            if (rb < n) {
                n = rb;
            }
            if (n > 0) {
                boolean run;
                run = true;
                // THE MEMCMP NEEDS TWO ADDRESSES. An inline leaf has none,
                // so a pair with one on either side goes a byte at a time.
                if (Val.isHeap(la) && Val.isHeap(lb)) {
                    run = rt.runEq((Val.asHeap(la) + Obj.STR_DATA) + pa, (Val.asHeap(lb) + Obj.STR_DATA) + pb, n);
                } else {
                    int i;
                    i = 0;
                    for (;;) {
                        if (i == n) {
                            break;
                        }
                        if (rt.leafByte(la, pa + i) != rt.leafByte(lb, pb + i)) {
                            run = false;
                            break;
                        }
                        i += 1;
                    }
                }
                if (!run) {
                    same = false;
                    break;
                }
                pa += n;
                pb += n;
            }
        }
        // EQUAL means both ran out together AND neither has a leaf part
        // left over. Stopping early on one side is a length difference the
        // count check above cannot see when the trees are ragged.
        boolean ended = (pa == na) && (pb == nb);
        boolean drya = Val.isNil(rt.walkNext(wa));
        boolean dryb = Val.isNil(rt.walkNext(wb));
        rt.walkClose(wa);
        return same && (ended && (drya && dryb));
    }
}
