// Generated by kin from the source named below. Do not edit.
// source: flint.rt.ropecat

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Ropemeas.*;
import static com._3sln.flint.kgen.rt.Ropenode.*;

public final class Ropecat {
    /// How many children this node has.
    public static int ropeKids(Rt rt, long v) {
        return olen(rt, v) - Str.RP_KIDS;
    }
    /// How many levels of node stand above the leaves, 0 for a leaf itself.
    /// 
    /// Reads CHILD ZERO and recurses, which is exact because a node's children
    /// are all the same height -- the invariant `rope-lift` exists to keep.
    public static int ropeHeight(Rt rt, long v) {
        if (!isRope(rt, v)) {
            return 0;
        }
        return 1 + ropeHeight(rt, rt.slot(v, Str.RP_KIDS));
    }
    /// Append `b` into the rightmost subtree of `a` that has room.
    /// 
    /// NIL when the right spine is full at every level, which is the ONLY time
    /// the caller adds one -- so depth grows O(log n) times over n appends
    /// rather than O(n/FANOUT) times.
    /// 
    /// DEEPEST FIRST: room further down costs no depth at all, and only when
    /// nothing below has room does this node take `b` as a sibling.
    public static long ropeAppend(Rt rt, long a, long b) {
        if (!isRope(rt, a)) {
            return Val.NIL;
        }
        int n = ropeKids(rt, a);
        int base = rt.mark();
        int ai = rt.push(a);
        int bi = rt.push(b);
        long last = rt.slot(rt.r(ai), Str.RP_KIDS + (n - 1));
        int li = rt.push(last);
        long deeper;
        deeper = Val.NIL;
        if (isRope(rt, rt.r(li))) {
            deeper = ropeAppend(rt, rt.r(li), rt.r(bi));
        }
        if (!Val.isNil(deeper)) {
            int ni = rt.push(deeper);
            int kbase = rt.mark();
            for (int i = 0; i < n - 1; i++) {
                rt.push(rt.slot(rt.r(ai), Str.RP_KIDS + i));
            }
            rt.push(rt.r(ni));
            long out = ropeNode(rt, kbase, n);
            rt.popTo(base);
            return out;
        }
        // MERGE BEFORE CREATE, which is the rule a CHAMP already follows
        // and this did not. `s-concat`'s copy tier asks whether the WHOLE
        // RESULT fits in a leaf, so it stops firing once the string passes
        // FLAT_MAX -- and from then on every append, however small, became
        // its own leaf. Building a 38 KB string out of 8-byte pieces made
        // 4 000 leaves and cost 19 475 allocations, and allocations PER
        // PIECE grew with the string (2.97 at 100 pieces, 4.87 at 4 000)
        // because each append also rebuilt the right spine.
        // 
        // The question that matters is not whether the result is small; it
        // is whether `b` FITS IN THE LEAF ALREADY THERE.
        // 
        // AND ON ITS OWN THRESHOLD. `FLAT_MAX` is paid ONCE for a result;
        // this bound is paid on EVERY append into the same leaf, so a leaf
        // of T bytes filled from p-byte pieces copies T^2/2p bytes to hold
        // T of them -- 64x at 1024, 16x at 256, 8x at 128. Fewer leaves
        // pull the other way, so `MERGE_MAX` is measured, not assumed.
        // 
        // BEFORE THE FANOUT TEST ON PURPOSE: merging is better than adding
        // a sibling even when there is room for one, and when there is NOT
        // it also avoids returning NIL, which is what grows the depth.
        // 
        // LEAF INTO LEAF ONLY. A rope `b` would need its leftmost leaf
        // merged instead, which is the same rule at the other end and is
        // NOT done here -- see the note in `s-concat`.
        if (Val.isNil(deeper)) {
            if (!isRope(rt, rt.r(li))) {
                if (!isRope(rt, rt.r(bi))) {
                    if ((sBytes(rt, rt.r(li)) + sBytes(rt, rt.r(bi))) <= Str.MERGE_MAX) {
                        long merged = Str.copyConcat(rt, rt.r(li), rt.r(bi));
                        int mi = rt.push(merged);
                        int kbase = rt.mark();
                        for (int i = 0; i < n - 1; i++) {
                            rt.push(rt.slot(rt.r(ai), Str.RP_KIDS + i));
                        }
                        rt.push(rt.r(mi));
                        long out = ropeNode(rt, kbase, n);
                        rt.popTo(base);
                        return out;
                    }
                }
            }
        }
        if (n < Str.FANOUT) {
            // The spine is full below, but this node has room: `b` joins
            // as a sibling, LIFTED to the height its siblings stand at, or
            // the tree goes ragged and the depth grows linearly again.
            int h = ropeHeight(rt, rt.r(li));
            long lifted = ropeLift(rt, rt.r(bi), h);
            if (Val.isNil(lifted)) {
                rt.popTo(base);
                return Val.NIL;
            }
            int ni = rt.push(lifted);
            int kbase = rt.mark();
            for (int i = 0; i < n; i++) {
                rt.push(rt.slot(rt.r(ai), Str.RP_KIDS + i));
            }
            rt.push(rt.r(ni));
            long out = ropeNode(rt, kbase, n + 1);
            rt.popTo(base);
            return out;
        }
        rt.popTo(base);
        return Val.NIL;
    }
    /// `a` followed by `b`, as a string.
    public static long sConcat(Rt rt, long a, long b) {
        if (sBytes(rt, a) == 0) {
            return b;
        }
        if (sBytes(rt, b) == 0) {
            return a;
        }
        // Small enough that a tree would cost more in metadata than the copy
        // saves. This is the tier that must NOT be skipped.
        if ((sBytes(rt, a) + sBytes(rt, b)) <= Str.FLAT_MAX) {
            return Str.copyConcat(rt, a, b);
        }
        long appended = ropeAppend(rt, a, b);
        if (!Val.isNil(appended)) {
            return appended;
        }
        // A NEW LEVEL, and `b` is lifted to stand as tall as the old root so
        // the leaves stay at one depth on this side too.
        int base = rt.mark();
        int ai = rt.push(a);
        int bi = rt.push(b);
        int h = ropeHeight(rt, rt.r(ai));
        long lifted = ropeLift(rt, rt.r(bi), h);
        int li = rt.push(lifted);
        int kbase = rt.mark();
        rt.push(rt.r(ai));
        rt.push(rt.r(li));
        long out = ropeNode(rt, kbase, 2);
        rt.popTo(base);
        return out;
    }
}
