// Generated by kin from the source named below. Do not edit.
// source: flint.rt.setcore

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Mapcore.*;
import static com._3sln.flint.kgen.rt.Mapeq.*;
import static com._3sln.flint.kgen.rt.Mapread.*;
import static com._3sln.flint.kgen.rt.Mapwrite.*;

public final class Setcore {
    /// Is `v` a set?
    public static boolean isSet(Rt rt, long v) {
        if (!Val.isHeap(v)) {
            return false;
        }
        return ty(rt.gc.sp, Val.asHeap(v)) == TY_SET;
    }
    /// A set over `m`, carrying `meta`.
    /// 
    /// REFUSES BY ANSWERING NIL when the heap does, which is what every caller
    /// here checks -- a set that half-exists would be worse than none.
    public static long newSet(Rt rt, long m, long meta) {
        int base = rt.mark();
        int mi = rt.push(m);
        int mt = rt.push(meta);
        long a = rt.alloc(TY_SET, 3);
        // THE MAP AND THE META ARE RE-READ FROM THE ROOTS after the
        // allocation, and that is the whole reason they were pushed: 0031
        // says a value in a host local does not survive one.
        rt.setSlot(a, Sets.S_MAP, rt.r(mi));
        rt.setSlot(a, Sets.S_META, rt.r(mt));
        rt.setSlot(a, Sets.S_HASH, Val.NIL);
        rt.popTo(base);
        return Val.heap(a);
    }
    /// How many elements the set holds.
    public static int setCount(Rt rt, long s) {
        return mapCount(rt, rt.slot(s, Sets.S_MAP));
    }
    /// Is `x` in `s`?
    public static boolean setContains(Rt rt, long s, long x) {
        return mapContains(rt, rt.slot(s, Sets.S_MAP), x);
    }
    /// `get` on a set answers the STORED element, not the probe.
    /// 
    /// The element is its own key AND its own value, so the map's `get` hands
    /// back the one that is in the set. `(get #{[1 2]} [1 2])` is the vector
    /// that was put there, and code that relies on identity gets what it asked
    /// for rather than an equal stranger.
    public static long setGet(Rt rt, long s, long x, long notFound) {
        return mapGet(rt, rt.slot(s, Sets.S_MAP), x, notFound);
    }
    /// `conj` -- and the SET ITSELF when the element was already there.
    /// 
    /// The map answers the same map when nothing changed, so the identity test
    /// here is one comparison and saves an allocation. `(conj s x)` on a set
    /// that already has `x` is `s`, not a copy of it.
    public static long setConj(Rt rt, long s, long x) {
        int base = rt.mark();
        int si = rt.push(s);
        int xi = rt.push(x);
        long m = rt.slot(rt.r(si), Sets.S_MAP);
        long nm = mapAssoc(rt, m, rt.r(xi), rt.r(xi));
        if (nm == rt.slot(rt.r(si), Sets.S_MAP)) {
            long same = rt.r(si);
            rt.popTo(base);
            return same;
        }
        int ni = rt.push(nm);
        long meta = rt.slot(rt.r(si), Sets.S_META);
        long out = newSet(rt, rt.r(ni), meta);
        rt.popTo(base);
        return out;
    }
    /// `disj` -- and the SET ITSELF when the element was not there.
    public static long setDisj(Rt rt, long s, long x) {
        int base = rt.mark();
        int si = rt.push(s);
        int xi = rt.push(x);
        long m = rt.slot(rt.r(si), Sets.S_MAP);
        long nm = mapDissoc(rt, m, rt.r(xi));
        if (nm == rt.slot(rt.r(si), Sets.S_MAP)) {
            long same = rt.r(si);
            rt.popTo(base);
            return same;
        }
        int ni = rt.push(nm);
        long meta = rt.slot(rt.r(si), Sets.S_META);
        long out = newSet(rt, rt.r(ni), meta);
        rt.popTo(base);
        return out;
    }
    /// Two sets are equal exactly when their maps are.
    /// 
    /// THE LAST HAND-WRITTEN THING IN THE SET SURFACE, and it was never a
    /// primitive: a count comparison, two slot reads, and a delegation. Every
    /// part of it was already generated -- `set-count` here, `map-eq` in
    /// `mapeq.kin` -- so the three copies were three spellings of a call.
    /// 
    /// The count first because it is O(1) and settles most inequal pairs
    /// without touching a node.
    public static boolean setEq(Rt rt, long a, long b) {
        if (setCount(rt, a) != setCount(rt, b)) {
            return false;
        }
        return mapEq(rt, rt.slot(a, Sets.S_MAP), rt.slot(b, Sets.S_MAP));
    }
}
