// Generated by kin from the source named below. Do not edit.
// source: flint.rt.tablemigrate

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Mapread.*;
import static com._3sln.flint.kgen.rt.Mapwrite.*;
import static com._3sln.flint.kgen.rt.Tablecell.*;
import static com._3sln.flint.kgen.rt.Tablekind.*;
import static com._3sln.flint.kgen.rt.Tablemeta.*;
import static com._3sln.flint.kgen.rt.Tableref.*;
import static com._3sln.flint.kgen.rt.Tablesay.*;
import static com._3sln.flint.kgen.rt.Valeq.*;
import static com._3sln.flint.kgen.rt.Vecread.*;
import static com._3sln.flint.kgen.rt.Vecwrite.*;

public final class Tablemigrate {
    /// `want` REBASED onto `have`'s column ids.
    /// 
    /// A column both schemas name KEEPS ITS ID, so the chunks that hold it can
    /// be shared unchanged; a column only `want` has gets a fresh one past the
    /// end. The width therefore only ever grows -- a dropped column's slot stays
    /// spoken for, which is what keeps every other column's id stable.
    public static long rebaseSchema(Rt rt, long have, long want) {
        int base = rt.mark();
        int hi = rt.push(have);
        int wi = rt.push(want);
        int n = schemaLen(rt, rt.r(wi));
        long ids0 = Vec.empty(rt);
        int di = rt.push(ids0);
        long idx0 = com.flint.rt.Maps.empty(rt);
        int ii = rt.push(idx0);
        int width;
        width = schemaWidth(rt, rt.r(hi));
        for (int c = 0; c < n; c++) {
            long name = schemaNameAt(rt, rt.r(wi), c);
            int ni = rt.push(name);
            int old = schemaId(rt, rt.r(hi), rt.r(ni));
            int id;
            if (old < schemaWidth(rt, rt.r(hi))) {
                id = old;
            } else {
                id = width;
                width += 1;
            }
            long dv = vecConj(rt, rt.r(di), Val.fixnum(id & 0xFFFFFFFFL));
            rt.setR(di, dv);
            long m = mapAssoc(rt, rt.r(ii), rt.r(ni), Val.fixnum(id & 0xFFFFFFFFL));
            rt.setR(ii, m);
            rt.popTo(ni);
        }
        long sc = Val.heap(rt.alloc(TY_SCHEMA, Table.SC_LEN));
        int si = rt.push(sc);
        rt.setSlot(Val.asHeap(rt.r(si)), Table.SC_NAMES, rt.slot(rt.r(wi), Table.SC_NAMES));
        rt.setSlot(Val.asHeap(rt.r(si)), Table.SC_TYPES, rt.slot(rt.r(wi), Table.SC_TYPES));
        rt.setSlot(Val.asHeap(rt.r(si)), Table.SC_INDEX, rt.r(ii));
        rt.setSlot(Val.asHeap(rt.r(si)), Table.SC_IDS, rt.r(di));
        rt.setSlot(Val.asHeap(rt.r(si)), Table.SC_WIDTH, Val.fixnum(width & 0xFFFFFFFFL));
        long out = rt.r(si);
        rt.popTo(base);
        return out;
    }
    /// The table under a new schema, with `defaults` for the columns it adds.
    /// 
    /// REFUSED FIRST, AND COMPLETELY, before anything is built. A migration that
    /// half-happened would leave a table nobody asked for, and the three ways it
    /// can be refused each say what to do instead: a type change needs a value
    /// per row, an added column needs a default, and a default has to be of the
    /// declared type.
    public static long tableMigrate(Rt rt, long t, long want, long defaults) {
        int base = rt.mark();
        int ti = rt.push(t);
        int wi = rt.push(want);
        int dfi = rt.push(defaults);
        int hi = rt.push(rt.slot(rt.r(ti), Table.TB_SCHEMA));
        int n = schemaLen(rt, rt.r(wi));
        for (int c = 0; c < n; c++) {
            long name = schemaNameAt(rt, rt.r(wi), c);
            int nmi = rt.push(name);
            long wantTy = schemaTypeAt(rt, rt.r(wi), c);
            int old = schemaId(rt, rt.r(hi), rt.r(nmi));
            if (old < schemaWidth(rt, rt.r(hi))) {
                // A CARRIED COLUMN KEEPS ITS VALUES, so it must keep its
                // type. Changing one means computing a value per row, which
                // is a different operation and says so.
                int hc = schemaPosOf(rt, rt.r(hi), rt.r(nmi));
                long haveTy = schemaTypeAt(rt, rt.r(hi), hc);
                if (!valEq(rt, haveTy, wantTy)) {
                    String nm = kwName(rt, rt.r(nmi));
                    String ht = kwName(rt, haveTy);
                    String wt = kwName(rt, wantTy);
                    rt.popTo(base);
                    return rt.throwStr("IllegalArgumentException", "column :" + nm + " holds :" + ht + " and the new schema declares :" + wt + "; a type change needs a value per row, so migrate with a function: (migrate t s (fn [row] ...))");
                }
            } else {
                long dv = mapGet(rt, rt.r(dfi), rt.r(nmi), Val.NOT_FOUND);
                if (dv == Val.NOT_FOUND) {
                    String nm = kwName(rt, rt.r(nmi));
                    rt.popTo(base);
                    return rt.throwStr("IllegalArgumentException", "the new schema adds :" + nm + " and the table has no values for it; give it a default -- (migrate t s {:" + nm + " v}) -- or compute one per row: (migrate t s (fn [row] ...))");
                }
                if (!typeOk(rt, wantTy, dv)) {
                    String nm = kwName(rt, rt.r(nmi));
                    String wt = kwName(rt, wantTy);
                    long gk = rt.kindOf(dv);
                    String gt = kwName(rt, gk);
                    rt.popTo(base);
                    return rt.throwStr("IllegalArgumentException", "the default for :" + nm + " is a " + gt + " and the column holds :" + wt);
                }
            }
            rt.popTo(nmi);
        }
        long rebased = rebaseSchema(rt, rt.r(hi), rt.r(wi));
        int ri = rt.push(rebased);
        int width = schemaWidth(rt, rt.r(ri));
        int ci = rt.push(rt.slot(rt.r(ti), Table.TB_CHUNKS));
        int nch = Vec.count(rt, rt.r(ci));
        long out0 = Vec.empty(rt);
        int oi = rt.push(out0);
        for (int k = 0; k < nch; k++) {
            if (!rt.chargeChecked(1, "migrate")) {
                rt.popTo(base);
                return Val.NIL;
            }
            long ch = vecNth(rt, rt.r(ci), k, Val.NIL);
            int chi = rt.push(ch);
            int rows = chunkRows(rt, rt.r(chi));
            long nc = newChunk(rt, width, rows);
            int ni = rt.push(nc);
            for (int c = 0; c < n; c++) {
                int id = schemaIdAt(rt, rt.r(ri), c);
                long name = schemaNameAt(rt, rt.r(ri), c);
                int old = schemaId(rt, rt.r(hi), name);
                if (old < schemaWidth(rt, rt.r(hi))) {
                    // SHARED, column object and encoding both. Nothing is
                    // copied and nothing is scanned: this is the head-only
                    // edit, and dropping a column is the case where the
                    // loop simply never reaches the old slot.
                    rt.setSlot(Val.asHeap(rt.r(ni)), Table.CH_BASE + id, rt.slot(rt.r(chi), Table.CH_BASE + old));
                    int e = chunkEnc(rt, rt.r(chi), old);
                    rt.setSlot(Val.asHeap(rt.slot(rt.r(ni), Table.CH_ENC)), id, Val.fixnum(e & 0xFFFFFFFFL));
                } else {
                    // AN ADDED COLUMN IS ONE SHARED VALUE for the whole
                    // chunk, so a migration that adds a column costs a
                    // slot per chunk rather than a value per row.
                    long dv = mapGet(rt, rt.r(dfi), name, Val.NIL);
                    rt.setSlot(Val.asHeap(rt.r(ni)), Table.CH_BASE + id, dv);
                    rt.setSlot(Val.asHeap(rt.slot(rt.r(ni), Table.CH_ENC)), id, Val.fixnum(Table.ENC_CONST & 0xFFFFFFFFL));
                }
            }
            long ov = vecConj(rt, rt.r(oi), rt.r(ni));
            rt.setR(oi, ov);
            rt.popTo(chi);
        }
        int count = tableCount(rt, rt.r(ti));
        long nt = Val.heap(rt.alloc(TY_TABLE, Table.TB_LEN));
        int nti = rt.push(nt);
        rt.setSlot(Val.asHeap(rt.r(nti)), Table.TB_SCHEMA, rt.r(ri));
        rt.setSlot(Val.asHeap(rt.r(nti)), Table.TB_CHUNKS, rt.r(oi));
        rt.setSlot(Val.asHeap(rt.r(nti)), Table.TB_COUNT, Val.fixnum(count & 0xFFFFFFFFL));
        rt.setSlot(Val.asHeap(rt.r(nti)), Table.TB_OFFSET, rt.slot(rt.r(ti), Table.TB_OFFSET));
        long out = rt.r(nti);
        rt.popTo(base);
        return out;
    }
}
