// Generated by kin from the source named below. Do not edit.
// source: flint.rt.tablefill

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Tablecell.*;
import static com._3sln.flint.kgen.rt.Tablemeta.*;

public final class Tablefill {
    /// Write row `k` of `ch` from `row`, column by column.
    /// 
    /// The chunk is already the right shape; this only fills it.
    public static void writeRow(Rt rt, long s, long ch, int k, long row) {
        int base = rt.mark();
        int si = rt.push(s);
        int ci = rt.push(ch);
        int ri = rt.push(row);
        int n = schemaLen(rt, rt.r(si));
        rt.chargeWork(n);
        for (int c = 0; c < n; c++) {
            int id = schemaIdAt(rt, rt.r(si), c);
            long v = rowColumn(rt, rt.r(si), rt.r(ri), c);
            long col = rt.slot(rt.r(ci), Table.CH_BASE + id);
            rt.setSlot(Val.asHeap(col), k, v);
        }
        rt.popTo(base);
    }
    /// An OPEN chunk: full-width columns and no rows written yet.
    /// 
    /// The transient fills one of these in place and `seal` copies out only the
    /// rows that were actually written.
    public static long openChunk(Rt rt, long s) {
        int base = rt.mark();
        int si = rt.push(s);
        int width = schemaWidth(rt, rt.r(si));
        long ch = newChunk(rt, width, 0);
        int ci = rt.push(ch);
        int ncols = schemaLen(rt, rt.r(si));
        for (int c = 0; c < ncols; c++) {
            int id = schemaIdAt(rt, rt.r(si), c);
            long col = Conc.newObj(rt, TY_NODE, Table.CHUNK);
            rt.setSlot(Val.asHeap(rt.r(ci)), Table.CH_BASE + id, col);
        }
        long out = rt.r(ci);
        rt.popTo(base);
        return out;
    }
    /// A copy of `ch` with row `k` set from `row`, one row longer when `grow`.
    /// 
    /// ONLY THE COLUMNS THE SCHEMA NAMES ARE CARRIED OVER. A slot the schema has
    /// dropped is left empty, which is where the `data stays resident and
    /// invisible until a chunk is next rewritten` trade in `0026` is paid back:
    /// a migration is head-only, and the first write to a chunk after it is what
    /// actually reclaims.
    /// 
    /// A CONSTANT COLUMN WHOSE NEW VALUE IS THE SAME VALUE STAYS CONSTANT, and
    /// costs nothing to carry. That is the case that makes appending to a table
    /// with a constant column cheap -- not the case that un-does the encoding.
    public static long chunkWithRow(Rt rt, long s, long ch, int k, long row, boolean grow) {
        int base = rt.mark();
        int si = rt.push(s);
        int ci = rt.push(ch);
        int ri = rt.push(row);
        int old = chunkRows(rt, rt.r(ci));
        int take;
        take = old;
        if (grow) {
            take = old + 1;
        }
        // `carry` is how many of the OLD rows survive: the smaller of the
        // two lengths, because a shrinking rewrite must not read past the
        // new column's end.
        int carry;
        carry = old;
        if (carry > take) {
            carry = take;
        }
        int coln;
        coln = take;
        if (coln < 1) {
            coln = 1;
        }
        int width = schemaWidth(rt, rt.r(si));
        long nch = newChunk(rt, width, take);
        int ni = rt.push(nch);
        int ncols = schemaLen(rt, rt.r(si));
        for (int c = 0; c < ncols; c++) {
            int id = schemaIdAt(rt, rt.r(si), c);
            long newv = rowColumn(rt, rt.r(si), rt.r(ri), c);
            int vi = rt.push(newv);
            boolean stays = (chunkEnc(rt, rt.r(ci), id) == Table.ENC_CONST) && com.flint.rt.Eq.eq(rt, rt.slot(rt.r(ci), Table.CH_BASE + id), rt.r(vi));
            if (stays) {
                // THE SLOT IS RE-READ, not carried across `val-eq`.
                // Equality may allocate -- comparing two ropes can
                // flatten one -- and 0031 says a value in a host local
                // does not survive an allocation. The chunk itself is
                // rooted, so reading through it again is always safe.
                rt.setSlot(Val.asHeap(rt.r(ni)), Table.CH_BASE + id, rt.slot(rt.r(ci), Table.CH_BASE + id));
                rt.setSlot(Val.asHeap(rt.slot(rt.r(ni), Table.CH_ENC)), id, Val.fixnum(Table.ENC_CONST & 0xFFFFFFFFL));
                rt.popTo(vi);
                continue;
            }
            long col = Conc.newObj(rt, TY_NODE, coln);
            int cj = rt.push(col);
            // `v` is HOISTED: `set-slot` and `chunk-get` both take
            // `&mut self` in Rust, and an argument is evaluated while
            // the receiver is already borrowed.
            for (int j = 0; j < carry; j++) {
                long v = chunkGet(rt, rt.r(ci), id, j);
                rt.setSlot(Val.asHeap(rt.r(cj)), j, v);
            }
            rt.setSlot(Val.asHeap(rt.r(cj)), k, rt.r(vi));
            rt.setSlot(Val.asHeap(rt.r(ni)), Table.CH_BASE + id, rt.r(cj));
            // REPLACING THE ONE ROW THAT DIFFERED can make a column
            // constant again, so the collapse is checked on the way out
            // as well as on the way in. Without it a table would only
            // ever lose encodings.
            collapse(rt, rt.r(ni), id);
            rt.popTo(vi);
        }
        long out = rt.r(ni);
        rt.popTo(base);
        return out;
    }
    /// Copy the first `rows` rows out of an open chunk into a sealed one.
    /// 
    /// The open chunk's columns are `CHUNK` long whatever was written; the
    /// sealed copy is exactly `rows`, and each column is collapsed on the way.
    public static long seal(Rt rt, long s, long open, int rows) {
        int base = rt.mark();
        int si = rt.push(s);
        int oi = rt.push(open);
        int width = schemaWidth(rt, rt.r(si));
        long ch = newChunk(rt, width, rows);
        int ci = rt.push(ch);
        int ncols = schemaLen(rt, rt.r(si));
        int coln;
        coln = rows;
        if (coln < 1) {
            coln = 1;
        }
        for (int c = 0; c < ncols; c++) {
            int id = schemaIdAt(rt, rt.r(si), c);
            long col = Conc.newObj(rt, TY_NODE, coln);
            int cj = rt.push(col);
            long src = rt.slot(rt.r(oi), Table.CH_BASE + id);
            int sj = rt.push(src);
            for (int k = 0; k < rows; k++) {
                rt.setSlot(Val.asHeap(rt.r(cj)), k, rt.slot(rt.r(sj), k));
            }
            rt.setSlot(Val.asHeap(rt.r(ci)), Table.CH_BASE + id, rt.r(cj));
            collapse(rt, rt.r(ci), id);
            rt.popTo(cj);
        }
        long out = rt.r(ci);
        rt.popTo(base);
        return out;
    }
}
