// Generated by kin from the source named below. Do not edit.
// source: flint.rt.vecread

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Vecnode.*;

public final class Vecread {
    /// How many elements the vector `v` holds.
    /// 
    /// ONE SLOT READ, and it was a linked form -- written once per runtime and
    /// declared to kin as a primitive, beside `char-at` and `s-copy-range`
    /// which really do need the host's memory. This needs a slot and a fixnum,
    /// both of which kin says already. It sat on the linked side because it is
    /// SHORT.
    /// 
    /// It lives in `vecread` because that is the module every other vector and
    /// table source already requires, and because reading a count is reading.
    public static int vecCount(Rt rt, long v) {
        return (int) Val.asFixnum(rt.slot(v, V_CNT));
    }
    /// `vector?` AS THE GUEST SEES IT, which includes a MAP ENTRY.
    /// 
    /// Clojure's `MapEntry` IS a vector -- `vector?` is true, it prints
    /// `[:a 1]`, and `conj` appends -- and flint answered false, printed
    /// `(:a 1)` and consed, on all four runtimes at once.
    /// 
    /// Deliberately NOT the same question as `is-vector`, which guards
    /// `vec-count` and `vec-nth` and has twenty callers in Rust alone. A map
    /// entry does not have the vector LAYOUT, so widening the internal
    /// predicate would hand those functions an object they would read as a
    /// vector head. The guest question and the layout question are different
    /// questions that happened to share an answer.
    /// 
    /// The ports had this only as `rt.typeP(8, v)`, a magic number in a
    /// dispatch switch, until `new-schema` needed it by name -- Rust used the
    /// stricter `is-vector` there, so a schema whose pairs came from a map's
    /// `seq` was accepted on the ports and refused natively.
    public static boolean isVectorLike(Rt rt, long v) {
        if (!Val.isHeap(v)) {
            return false;
        }
        int t = ty(rt.gc.sp, Val.asHeap(v));
        return (t == TY_VEC) || (t == TY_MAPENTRY);
    }
    /// Copy `src` into a fresh node of `newlen` slots owned by `edit`, keeping
    /// as many children as both lengths allow.
    /// 
    /// NO `max(newlen, 1)` FLOOR, and no nil-source arm. Both ports carried the
    /// floor and native did not, so persisting an EMPTY transient built a
    /// two-slot tail node on the ports and a one-slot one here -- the same value
    /// at two different widths, which no gate could see. The only caller that
    /// can ask for zero is that one, `cnt - tailOff` being 0 there.
    /// 
    /// The nil-source arm was the ports' too, and it is dead: a probe over the
    /// whole conformance suite and over `(persistent! (transient []))` never
    /// reached it, and native has run without it since vectors were written.
    public static long nodeClone(Rt rt, long n, int newlen, long edit) {
        int old = rt.push(n);
        int e = rt.push(edit);
        long fresh = newNode(rt, newlen, rt.r(e));
        if (Val.isNil(fresh)) {
            rt.popTo(old);
            return Val.NIL;
        }
        int f = rt.push(fresh);
        int have = nodeLen(rt, rt.r(old));
        // The smaller of the two lengths, spelled with a local and an
        // `if` because kin has no `min` -- and a `min` form would be
        // three templates for what two lines say plainly.
        int copy;
        copy = newlen;
        if (have < copy) {
            copy = have;
        }
        for (int i = 0; i < copy; i++) {
            nodeSet(rt, rt.r(f), i, nodeGet(rt, rt.r(old), i));
        }
        long out = rt.r(f);
        rt.popTo(old);
        return out;
    }
    /// The shift of `v`'s root: how many bits an index is walked down by.
    /// 
    /// `^:inline`, which the hand-written Rust also carried and the first draft
    /// of this file dropped. Moving a private module-local helper into a
    /// generated module makes it PUBLIC and cross-crate-module, and Rust will
    /// not inline across that on its own.
    /// 
    /// NOT `^:pub`, and that is the half that actually mattered. These three
    /// were private `fn`s in Rust, and marking them `^:pub` made them `pub`
    /// where kin's default is `pub(crate)` -- four symbols the linker could no
    /// longer internalise, which grew the runtime 283 bytes and the floor
    /// module 285 (303 740 to 304 025). `^:pub` means part of the CRATE's
    /// public API, not `something outside this file calls it`; the default
    /// already covers the second. Java emits `public` either way, because a
    /// generated module is its own package and Java has nothing between
    /// package-private and public, so nothing is lost on the ports.
    /// 
    /// `vec-shift` and `tail-off` got the mark BACK when `vecwrite` arrived and
    /// referred to them: a require of a non-`^:pub` name does not resolve. So
    /// the rule is not `these were private in Rust` -- it is `nothing outside
    /// this module needs the name`, and that is a fact about the port as it
    /// stands rather than about the function. It changes as the port grows.
    public static int vecShift(Rt rt, long v) {
        return (int) Val.asFixnum(rt.slot(v, V_SHIFT));
    }
    /// Where the tail starts. Below `WIDTH` elements the whole vector IS the
    /// tail, so the answer is 0 and the trie is not consulted at all.
    public static int tailOff(Rt rt, long v) {
        int c = vecCount(rt, v);
        if (c < WIDTH) {
            return 0;
        }
        return ((c - 1) >>> BITS) << BITS;
    }
    /// The leaf node holding index `i`.
    /// 
    /// `ushr` and not a bare right shift: `i` and `level` are both `I32`, so
    /// the shift is logical on every target, but which shift a `>>` MEANS
    /// depends on the host type -- Rust's is unsigned and the ports' is not.
    /// Naming the logical one is how that survives the trip.
    public static long arrayFor(Rt rt, long v, int i) {
        if (i >= tailOff(rt, v)) {
            return rt.slot(v, V_TAIL);
        }
        long node;
        node = rt.slot(v, V_ROOT);
        int level;
        level = vecShift(rt, v);
        while (level > 0) {
            node = nodeGet(rt, node, (i >>> level) & MASK);
            level -= BITS;
        }
        return node;
    }
    /// Element `i` of `v`, or `dflt` when `i` is out of range.
    /// 
    /// A DEFAULT and not an absent value, which is a CONVERGENCE rather than a
    /// port. Rust answered `Option<Value>` and both ports answered a fixed
    /// `NOT_FOUND`, and counting settled it: of 95 call sites in Rust, 70 were
    /// `.unwrap_or(NIL)` and 19 were `.unwrap()` on an index the caller had
    /// already bounds-checked. That is an `Option` being spelled out as a
    /// default 89 times, not an `Option` being used as one.
    /// 
    /// It is `map-get`'s signature, which is the point of choosing it: the two
    /// lookups in the runtime answer absence the same way instead of each
    /// having its own idea. Every port call site passes `NOT_FOUND` and behaves
    /// exactly as before; what changed is that absence is an argument.
    public static long vecNth(Rt rt, long v, int i, long dflt) {
        if (i >= vecCount(rt, v)) {
            return dflt;
        }
        return nodeGet(rt, arrayFor(rt, v, i), i & MASK);
    }
}
