// Generated by kin from the source named below. Do not edit.
// source: flint.rt.vectrans

package com._3sln.flint.kgen.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;
import static com._3sln.flint.kgen.rt.Vecnode.*;
import static com._3sln.flint.kgen.rt.Vecread.*;

public final class Vectrans {
    /// A fresh ownership token: an object whose IDENTITY is the whole of it.
    /// 
    /// `TY_VOLATILE` with one slot, and the slot is never read. What matters is
    /// that no two transients can be handed the same address, which is what
    /// makes `node-edit node == edit` a safe test for `this is mine`.
    public static long newEditToken(Rt rt) {
        long a = rt.alloc(TY_VOLATILE, 1);
        if (a == 0) {
            return Val.NIL;
        }
        return Val.heap(a);
    }
    public static boolean isTransientVector(Rt rt, long v) {
        if (!Val.isHeap(v)) {
            return false;
        }
        return ty(rt.gc.sp, Val.asHeap(v)) == TY_TVEC;
    }
    /// THE FOUR READERS BELOW ARE THE VECTOR'S, AND THAT IS DELIBERATE.
    /// 
    /// A TRANSIENT'S HEADER IS A VECTOR'S HEADER, PREFIX-WISE. A `TY_VEC` is
    /// `cnt, shift, root, tail, meta, hash` and a `TY_TVEC` is
    /// `cnt, shift, root, tail, edit`.
    /// 
    /// NOT WRITTEN AS AN INDENTED BLOCK, which is what it was first. Four
    /// leading spaces in a Rust doc comment is a CODE FENCE, so rustdoc tried
    /// to compile the layout diagram as Rust and `cargo test` failed on a
    /// doctest nobody wrote. Kin doc strings become `///` on one target and
    /// `/// <summary>` on the others, so an indented line is a different thing
    /// in each.
    /// 
    /// `T_CNT`, `T_SHIFT`, `T_ROOT` and `T_TAIL` are 0, 1, 2 and 3 -- the same
    /// numbers as `V_CNT`, `V_SHIFT`, `V_ROOT` and `V_TAIL`. The layouts part
    /// company only at slot 4, where a vector keeps its metadata and a
    /// transient its edit token, and no reader below looks that far.
    /// 
    /// SO THE BODIES WERE IDENTICAL, four of them, differing only in whether
    /// the parameter was called `v` or `t` -- `tvec-shift` was a byte-for-byte
    /// copy of `vec-shift` in a file that ALREADY IMPORTED `vec-shift` and used
    /// it eleven lines further down. The names stay, because `(tvec-count rt t)`
    /// says what `(vec-count rt t)` would only imply, and `^:inline` means
    /// saying it costs nothing.
    /// 
    /// THE PREFIX IS NOW LOAD-BEARING, and it was not written down anywhere
    /// before this comment. `runtime/src/vector.rs` asserts it at COMPILE TIME
    /// rather than trusting the reader: put `T_EDIT` in front of `T_TAIL` one
    /// day and the build stops, instead of four readers quietly returning the
    /// wrong slot.
    public static int tvecCount(Rt rt, long t) {
        return vecCount(rt, t);
    }
    public static int tvecShift(Rt rt, long t) {
        return vecShift(rt, t);
    }
    /// Where the transient's tail starts, on the same rule as a vector's --
    /// which is now the same CODE as a vector's.
    public static int tvecTailOff(Rt rt, long t) {
        return tailOff(rt, t);
    }
    /// Is this transient still usable? `persistent!` clears the token, and a
    /// transient without one has been handed over and must not be written.
    public static boolean tvecAlive(Rt rt, long t) {
        return !Val.isNil(rt.slot(t, T_EDIT));
    }
    /// `transient`: O(1), because nothing is copied until the first write that
    /// reaches a node this transient does not already own.
    /// 
    /// The TAIL is the exception and is widened to a full 32 here, so that
    /// `conj!` can write into it in place rather than copying it one longer on
    /// every append -- which is the copy transients exist to avoid.
    public static long vecTransient(Rt rt, long v) {
        int base = rt.mark();
        int vi = rt.push(v);
        long edit = newEditToken(rt);
        int ei = rt.push(edit);
        long tail = nodeClone(rt, rt.slot(rt.r(vi), V_TAIL), WIDTH, rt.r(ei));
        int ti = rt.push(tail);
        int ri = rt.push(rt.slot(rt.r(vi), V_ROOT));
        long a = rt.alloc(TY_TVEC, 5);
        if (a == 0) {
            rt.popTo(base);
            return Val.NIL;
        }
        long vv = rt.r(vi);
        int cnt = vecCount(rt, vv);
        int shift = vecShift(rt, vv);
        rt.setSlot(a, T_CNT, Val.fixnum(cnt & 0xFFFFFFFFL));
        rt.setSlot(a, T_SHIFT, Val.fixnum(shift & 0xFFFFFFFFL));
        rt.setSlot(a, T_ROOT, rt.r(ri));
        rt.setSlot(a, T_TAIL, rt.r(ti));
        rt.setSlot(a, T_EDIT, rt.r(ei));
        rt.popTo(base);
        return Val.heap(a);
    }
    /// `node` if this transient already owns it, else an owned copy.
    /// 
    /// The one test the whole transient design rests on. A node whose token is
    /// this transient's was made by it and nobody else can see it, so writing
    /// in place is safe; any other node may be shared with a persistent vector
    /// and is copied ONCE, after which the copy is owned.
    public static long ensureEditable(Rt rt, long node, long edit) {
        if (nodeEdit(rt, node) == edit) {
            return node;
        }
        return nodeClone(rt, node, WIDTH, edit);
    }
    /// The leaf holding index `i` of a transient -- the vector's descent, for
    /// the reason at the top of this file.
    public static long tArrayFor(Rt rt, long t, int i) {
        return arrayFor(rt, t, i);
    }
    /// Element `i` of a transient, or `dflt`. Same convergence as `vec-nth`.
    public static long tvecNth(Rt rt, long t, int i, long dflt) {
        return vecNth(rt, t, i, dflt);
    }
}
