// Generated by kin from the source named below. Do not edit.
// source: flint.rt.hash

package flint.rt;

import com.flint.rt.*;
import static com.flint.rt.Obj.*;
import static com.flint.rt.Maps.*;
import static com.flint.rt.Eq.*;
import static com.flint.rt.Seqs.*;
import static com.flint.rt.Vec.*;

public final class Hash {
    public static final int C1 = 0xcc9e2d51;
    public static final int C2 = 0x1b873593;
    public static final int SEED = 0;
    public static int mixK1(int k1) {
        return Integer.rotateLeft(k1 * C1, 15) * C2;
    }
    public static int mixH1(int h1, int k1) {
        return (Integer.rotateLeft(h1 ^ k1, 13) * 5) + 0xe6546b64;
    }
    public static int fmix(int h1, int len) {
        h1 ^= len;
        h1 ^= h1 >>> 16;
        h1 *= 0x85ebca6b;
        h1 ^= h1 >>> 13;
        h1 *= 0xc2b2ae35;
        return h1 ^ (h1 >>> 16);
    }
    public static int hashInt(int input) {
        if (input == 0) {
            return 0;
        }
        return fmix(mixH1(SEED, mixK1(input)), 4);
    }
    public static int hashLong(long input) {
        if (input == 0) {
            return 0;
        }
        int low = (int) input;
        int high = (int) (input >>> 32);
        int h1 = mixH1(SEED, mixK1(low));
        int h2 = mixH1(h1, mixK1(high));
        return fmix(h2, 8);
    }
    public static int hashCombine(int seed, int h) {
        return seed ^ (((h + 0x9e3779b9) + (seed << 6)) + (seed >> 2));
    }
    public static int mixCollHash(int hash, int count) {
        return fmix(mixH1(SEED, mixK1(hash)), count);
    }
    public static int orderedStep(int acc, int itemHash) {
        return (acc * 31) + itemHash;
    }
    public static int unorderedStep(int acc, int itemHash) {
        return acc + itemHash;
    }
    public static final int HASH_TRUE = 1231;
    public static final int HASH_FALSE = 1237;
}
